import re
import sys

def parse_c_file(filename):
    with open(filename, 'r') as f:
        content = f.read()
    return content

def extract_array_content(content, array_name):
    pattern = re.compile(r'static\s+.*?\s+' + array_name + r'\[.*?\]\s*=\s*\{(.*?)\};', re.DOTALL)
    match = pattern.search(content)
    if match:
        return match.group(1)
    return ""

def parse_spacegroup_types(content, array_name):
    raw_data = extract_array_content(content, array_name)
    raw_data = re.sub(r'/\*.*?\*/', '', raw_data)
    entries = []
    pattern = re.compile(r'\{\s*(-?\d+),\s*"([^"]*)",\s*"([^"]*)",\s*"([^"]*)",\s*"([^"]*)",\s*"([^"]*)",\s*"([^"]*)",\s*([A-Z_]+),\s*(\d+)\s*\}')
    for match in pattern.finditer(raw_data):
        entries.append({
            'number': int(match.group(1)),
            'schoenflies': match.group(2),
            'hall_symbol': match.group(3),
            'international': match.group(4),
            'international_full': match.group(5),
            'international_short': match.group(6),
            'choice': match.group(7),
            'centering': match.group(8),
            'pointgroup_number': int(match.group(9))
        })
    return entries

def parse_int_array(content, array_name):
    raw_data = extract_array_content(content, array_name)
    raw_data = re.sub(r'/\*.*?\*/', '', raw_data)
    numbers = [int(x) for x in re.findall(r'-?\d+', raw_data)]
    return numbers

def parse_2d_int_array(content, array_name):
    raw_data = extract_array_content(content, array_name)
    raw_data = re.sub(r'/\*.*?\*/', '', raw_data)
    entries = []
    pattern = re.compile(r'\{\s*(\d+),\s*(\d+)\s*\}')
    for match in pattern.finditer(raw_data):
        entries.append((int(match.group(1)), int(match.group(2))))
    return entries

def map_centering(c_enum):
    mapping = {
        'CENTERING_ERROR': 'Centering::Error',
        'PRIMITIVE': 'Centering::Primitive',
        'BODY': 'Centering::Body',
        'FACE': 'Centering::Face',
        'A_FACE': 'Centering::AFace',
        'B_FACE': 'Centering::BFace',
        'C_FACE': 'Centering::CFace',
        'R_CENTER': 'Centering::RCenter',
    }
    return mapping.get(c_enum, 'Centering::Error')

def generate_rust_code(spg_types, layer_types, sym_ops, sym_op_idx, layer_sym_op_idx):
    rust_code = []
    
    # --- Header ---
    rust_code.append("//! Generated by convert_spg_database.py")
    rust_code.append("//! Based on spg_database.c from spglib")
    rust_code.append("")
    rust_code.append("use crate::mathfunc::{Mat3I, Vec3};")
    rust_code.append("")

    # --- Enums ---
    rust_code.append("#[derive(Debug, Clone, Copy, PartialEq)]")
    rust_code.append("pub enum Centering {")
    rust_code.append("    Error,")
    rust_code.append("    Primitive,")
    rust_code.append("    Body,")
    rust_code.append("    Face,")
    rust_code.append("    AFace,")
    rust_code.append("    BFace,")
    rust_code.append("    CFace,")
    rust_code.append("    RCenter,")
    rust_code.append("}")
    rust_code.append("")
    
    # --- Structs ---
    # Raw struct for static storage (references)
    rust_code.append("struct RawSpacegroupType {")
    rust_code.append("    number: i32,")
    rust_code.append("    schoenflies: &'static str,")
    rust_code.append("    hall_symbol: &'static str,")
    rust_code.append("    international: &'static str,")
    rust_code.append("    international_full: &'static str,")
    rust_code.append("    international_short: &'static str,")
    rust_code.append("    choice: &'static str,")
    rust_code.append("    centering: Centering,")
    rust_code.append("    pointgroup_number: i32,")
    rust_code.append("}")
    rust_code.append("")

    # Public struct (owned Strings, allowing modification/cleaning)
    rust_code.append("#[derive(Debug, Clone)]")
    rust_code.append("pub struct SpacegroupType {")
    rust_code.append("    pub number: i32,")
    rust_code.append("    pub schoenflies: String,")
    rust_code.append("    pub hall_symbol: String,")
    rust_code.append("    pub international: String,")
    rust_code.append("    pub international_full: String,")
    rust_code.append("    pub international_short: String,")
    rust_code.append("    pub choice: String,")
    rust_code.append("    pub centering: Centering,")
    rust_code.append("    pub pointgroup_number: i32,")
    rust_code.append("}")
    rust_code.append("")

    # --- Helper to format struct ---
    def format_spg_entry(e):
        return (f"    RawSpacegroupType {{\n"
                f"        number: {e['number']},\n"
                f"        schoenflies: \"{e['schoenflies']}\",\n"
                f"        hall_symbol: \"{e['hall_symbol']}\",\n"
                f"        international: \"{e['international']}\",\n"
                f"        international_full: \"{e['international_full']}\",\n"
                f"        international_short: \"{e['international_short']}\",\n"
                f"        choice: \"{e['choice']}\",\n"
                f"        centering: {map_centering(e['centering'])},\n"
                f"        pointgroup_number: {e['pointgroup_number']},\n"
                f"    }},")

    # --- Static Data ---
    rust_code.append(f"static SPACEGROUP_TYPES: [RawSpacegroupType; {len(spg_types)}] = [")
    for e in spg_types:
        rust_code.append(format_spg_entry(e))
    rust_code.append("];")
    rust_code.append("")

    rust_code.append(f"static LAYER_GROUP_TYPES: [RawSpacegroupType; {len(layer_types)}] = [")
    for e in layer_types:
        rust_code.append(format_spg_entry(e))
    rust_code.append("];")
    rust_code.append("")

    rust_code.append(f"static SYMMETRY_OPERATIONS: [i32; {len(sym_ops)}] = [")
    chunk_size = 10
    for i in range(0, len(sym_ops), chunk_size):
        chunk = sym_ops[i:i+chunk_size]
        line = ", ".join(map(str, chunk)) + ","
        rust_code.append("    " + line)
    rust_code.append("];")
    rust_code.append("")

    rust_code.append(f"static SYMMETRY_OPERATION_INDEX: [[i32; 2]; {len(sym_op_idx)}] = [")
    for idx in sym_op_idx:
        rust_code.append(f"    [{idx[0]}, {idx[1]}],")
    rust_code.append("];")
    rust_code.append("")

    rust_code.append(f"static LAYER_SYMMETRY_OPERATION_INDEX: [[i32; 2]; {len(layer_sym_op_idx)}] = [")
    for idx in layer_sym_op_idx:
        rust_code.append(f"    [{idx[0]}, {idx[1]}],")
    rust_code.append("];")
    rust_code.append("")

    # --- Functions ---

    # decode_symmetry
    rust_code.append("/// Decode the compressed symmetry operation integer into rotation and translation.")
    rust_code.append("fn decode_symmetry(encoded: i32) -> (Mat3I, Vec3) {")
    rust_code.append("    let mut rot = [[0; 3]; 3];")
    rust_code.append("    let mut trans = [0.0; 3];")
    rust_code.append("    let r = encoded % 19683;")
    rust_code.append("    let mut digit = 6561;")
    rust_code.append("    for i in 0..3 {")
    rust_code.append("        for j in 0..3 {")
    rust_code.append("            rot[i][j] = (r % (digit * 3)) / digit - 1;")
    rust_code.append("            digit /= 3;")
    rust_code.append("        }")
    rust_code.append("    }")
    rust_code.append("    let t = encoded / 19683;")
    rust_code.append("    let mut digit = 144;")
    rust_code.append("    for i in 0..3 {")
    rust_code.append("        trans[i] = ((t % (digit * 12)) / digit) as f64 / 12.0;")
    rust_code.append("        digit /= 12;")
    rust_code.append("    }")
    rust_code.append("    (rot, trans)")
    rust_code.append("}")
    rust_code.append("")

    # spgdb_get_operation
    rust_code.append("/// Get rotation and translation for a specific index in the symmetry operations table.")
    rust_code.append("pub fn spgdb_get_operation(index: usize) -> Option<(Mat3I, Vec3)> {")
    rust_code.append("    if index >= SYMMETRY_OPERATIONS.len() {")
    rust_code.append("        return None;")
    rust_code.append("    }")
    rust_code.append("    Some(decode_symmetry(SYMMETRY_OPERATIONS[index]))")
    rust_code.append("}")
    rust_code.append("")

    # spgdb_get_operation_index
    rust_code.append("/// Get the start index and count of symmetry operations for a given Hall number.")
    rust_code.append("/// Returns Option<[count, start_index]>.")
    rust_code.append("pub fn spgdb_get_operation_index(hall_number: i32) -> Option<[i32; 2]> {")
    rust_code.append("    if hall_number > 0 && (hall_number as usize) < SYMMETRY_OPERATION_INDEX.len() {")
    rust_code.append("        Some(SYMMETRY_OPERATION_INDEX[hall_number as usize])")
    rust_code.append("    } else if hall_number < 0 && (-hall_number as usize) < LAYER_SYMMETRY_OPERATION_INDEX.len() {")
    rust_code.append("        Some(LAYER_SYMMETRY_OPERATION_INDEX[(-hall_number) as usize])")
    rust_code.append("    } else {")
    rust_code.append("        None")
    rust_code.append("    }")
    rust_code.append("}")
    rust_code.append("")

    # Helper for string cleaning
    rust_code.append("fn clean_symbol(s: &str) -> String {")
    rust_code.append("    s.trim().replace('=', \"\\\"\")")
    rust_code.append("}")
    rust_code.append("")

    # spgdb_get_spacegroup_type
    rust_code.append("/// Get the spacegroup type information for a given Hall number.")
    rust_code.append("/// This function performs string cleaning (trimming spaces, replacing '=' with '\"')")
    rust_code.append("/// to match the behavior of the C implementation.")
    rust_code.append("pub fn spgdb_get_spacegroup_type(hall_number: i32) -> Option<SpacegroupType> {")
    rust_code.append("    let raw = if hall_number > 0 && (hall_number as usize) < SPACEGROUP_TYPES.len() {")
    rust_code.append("        &SPACEGROUP_TYPES[hall_number as usize]")
    rust_code.append("    } else if hall_number < 0 && (-hall_number as usize) < LAYER_GROUP_TYPES.len() {")
    rust_code.append("        &LAYER_GROUP_TYPES[(-hall_number) as usize]")
    rust_code.append("    } else {")
    rust_code.append("        // Fallback to index 0 (Error/Empty) if out of range, similar to C logic")
    rust_code.append("        &SPACEGROUP_TYPES[0]")
    rust_code.append("    };")
    rust_code.append("")
    rust_code.append("    if raw.number == 0 && hall_number != 0 { return None; }")
    rust_code.append("")
    rust_code.append("    Some(SpacegroupType {")
    rust_code.append("        number: raw.number,")
    rust_code.append("        schoenflies: clean_symbol(raw.schoenflies),")
    rust_code.append("        hall_symbol: clean_symbol(raw.hall_symbol),")
    rust_code.append("        international: clean_symbol(raw.international),")
    rust_code.append("        international_full: clean_symbol(raw.international_full),")
    rust_code.append("        international_short: clean_symbol(raw.international_short),")
    rust_code.append("        choice: clean_symbol(raw.choice),")
    rust_code.append("        centering: raw.centering,")
    rust_code.append("        pointgroup_number: raw.pointgroup_number,")
    rust_code.append("    })")
    rust_code.append("}")

    return "\n".join(rust_code)

def main():
    input_file = 'spg_database.c'
    output_file = 'spg_database.rs'
    
    try:
        print(f"Reading {input_file}...")
        content = parse_c_file(input_file)
        
        print("Parsing spacegroup_types...")
        spg_types = parse_spacegroup_types(content, 'spacegroup_types')
        
        print("Parsing layer_group_types...")
        layer_types = parse_spacegroup_types(content, 'layer_group_types')
        
        print("Parsing symmetry_operations...")
        sym_ops = parse_int_array(content, 'symmetry_operations')
        
        print("Parsing symmetry_operation_index...")
        sym_op_idx = parse_2d_int_array(content, 'symmetry_operation_index')
        
        print("Parsing layer_symmetry_operation_index...")
        layer_sym_op_idx = parse_2d_int_array(content, 'layer_symmetry_operation_index')
        
        print(f"Generating Rust code...")
        rust_code = generate_rust_code(spg_types, layer_types, sym_ops, sym_op_idx, layer_sym_op_idx)
        
        with open(output_file, 'w') as f:
            f.write(rust_code)
            
        print(f"Successfully generated {output_file}")
        
    except FileNotFoundError:
        print(f"Error: Could not find {input_file}. Please save the C code to this file first.")
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    main()
