//! Subgroup embeddings against the pinned oracle fixture.
//!
//! Task 4 of `docs/full-irrep-subduction-plan.md`.  `tests/data/isotropy/
//! operations.txt` is generated by `scripts/verify_isotropy_operations.py`
//! from the pinned `iso.zip`; it holds, per (space group, irrep, direction)
//! case, the subgroup's printed basis, origin and operations in the parent
//! conventional frame (column-action rotations, exact rational translations).
//!
//! The tests here check that `SubgroupEmbedding` reproduces that fixture
//! exactly, and that the checks it uses have teeth: a transposed basis, a
//! shifted origin, a lost operation or a swapped direction must all fail.

use std::collections::BTreeSet;
use std::path::PathBuf;

use cryspglib::irrep::isotropy::{IsotropyDirection, isotropy_subgroup_for_direction};
use cryspglib::irrep::subduce_irrep;
use cryspglib::irrep::subduction::{
    ExactSeitz, Rat, SubductionError, SubgroupEmbedding, Vec3R, strict_sg_hall_ops,
};

/// One fixture case.
struct Case {
    sg: u8,
    ml: String,
    direction: String,
    subgroup: u8,
    size: i32,
    basis: [[Rat; 3]; 3],
    origin: Vec3R,
    elements: Vec<(String, ExactSeitz)>,
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data")
        .join("isotropy")
        .join("operations.txt")
}

fn rational(token: &str) -> Rat {
    match token.split_once('/') {
        Some((numerator, denominator)) => Rat::new(
            numerator.parse().expect("numerator"),
            denominator.parse().expect("denominator"),
        )
        .expect("valid rational"),
        None => Rat::from_integer(token.parse().expect("integer")),
    }
}

fn vector(token: &str) -> Vec3R {
    let values: Vec<Rat> = token.split(',').map(rational).collect();
    assert_eq!(values.len(), 3, "three components in {token:?}");
    Vec3R::new([values[0], values[1], values[2]])
}

fn rotation(token: &str) -> [[Rat; 3]; 3] {
    let rows: Vec<Vec<Rat>> = token
        .split(';')
        .map(|row| row.split(',').map(rational).collect())
        .collect();
    assert_eq!(rows.len(), 3, "three rows in {token:?}");
    assert!(
        rows.iter().all(|row| row.len() == 3),
        "three columns in {token:?}"
    );
    [
        [rows[0][0], rows[0][1], rows[0][2]],
        [rows[1][0], rows[1][1], rows[1][2]],
        [rows[2][0], rows[2][1], rows[2][2]],
    ]
}

fn parse_fixture() -> Vec<Case> {
    let text = std::fs::read_to_string(fixture_path()).expect("read the operation fixture");
    let mut cases: Vec<Case> = Vec::new();
    for line in text.lines() {
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        let mut parts = line.split_whitespace();
        match parts.next().expect("a token") {
            "case" => {
                cases.push(Case {
                    sg: parts.next().expect("sg").parse().expect("sg"),
                    ml: parts.next().expect("ml").to_string(),
                    direction: parts.next().expect("direction").to_string(),
                    subgroup: parts.next().expect("subgroup").parse().expect("subgroup"),
                    size: parts.next().expect("size").parse().expect("size"),
                    basis: [[Rat::ZERO; 3]; 3],
                    origin: Vec3R::zero(),
                    elements: Vec::new(),
                });
            }
            "basis" => {
                let case = cases.last_mut().expect("a case before its basis");
                // One token holding all three row vectors, `;`-separated.
                case.basis = rotation(parts.next().expect("basis"));
            }
            "origin" => {
                let case = cases.last_mut().expect("a case before its origin");
                case.origin = vector(parts.next().expect("origin"));
            }
            "element" => {
                let case = cases.last_mut().expect("a case before its elements");
                let label = parts.next().expect("label").to_string();
                let matrix = rotation(parts.next().expect("rotation"));
                let translation = vector(parts.next().expect("translation"));
                let integers = [
                    [
                        matrix[0][0].to_i32().unwrap(),
                        matrix[0][1].to_i32().unwrap(),
                        matrix[0][2].to_i32().unwrap(),
                    ],
                    [
                        matrix[1][0].to_i32().unwrap(),
                        matrix[1][1].to_i32().unwrap(),
                        matrix[1][2].to_i32().unwrap(),
                    ],
                    [
                        matrix[2][0].to_i32().unwrap(),
                        matrix[2][1].to_i32().unwrap(),
                        matrix[2][2].to_i32().unwrap(),
                    ],
                ];
                case.elements
                    .push((label, ExactSeitz::new(integers, translation)));
            }
            other => panic!("unknown fixture directive {other:?}"),
        }
    }
    assert_eq!(
        cases.len(),
        14,
        "the fixture includes four compound self-restrictions"
    );
    cases
}

/// Canonical `(rotation, translation)` keys of an operation set modulo the
/// embedding's **subgroup** lattice `L_H`: two subgroup operations are the same
/// element exactly when they differ by a vector of `L_H`.
///
/// Reducing modulo the parent lattice `L_G` instead hid the SG 139 defect: the
/// inversion `(-I | 5/2,5/2,5/2)` of the #126 embedding lies in `L_G` up to
/// translation zero for the I-centred parent, so a parent-lattice key reported
/// `0` where the subgroup's own coset representative is `(1/2,1/2,1/2)`.
fn keys(embedding: &SubgroupEmbedding, operations: &[ExactSeitz]) -> BTreeSet<(String, String)> {
    operations
        .iter()
        .map(|operation| {
            let reduced = operation
                .reduce(embedding.subgroup_lattice())
                .expect("reduce modulo the subgroup lattice");
            let rotation = reduced
                .rotation()
                .iter()
                .map(|row| format!("{row:?}"))
                .collect::<Vec<_>>()
                .join(";");
            let translation = reduced
                .translation()
                .as_array()
                .iter()
                .map(|value| value.to_string())
                .collect::<Vec<_>>()
                .join(",");
            (rotation, translation)
        })
        .collect()
}

fn fixture_keys(
    embedding: &SubgroupEmbedding,
    elements: &[(String, ExactSeitz)],
) -> BTreeSet<(String, String)> {
    keys(
        embedding,
        &elements
            .iter()
            .map(|(_, operation)| *operation)
            .collect::<Vec<_>>(),
    )
}

fn embedding_for(case: &Case) -> SubgroupEmbedding {
    let subgroup = isotropy_subgroup_for_direction(
        case.sg,
        &case.ml,
        IsotropyDirection::Label(&case.direction),
    )
    .unwrap_or_else(|error| panic!("SG {} {} {}: {error}", case.sg, case.ml, case.direction));
    SubgroupEmbedding::from_isotropy_subgroup(&subgroup)
        .unwrap_or_else(|error| panic!("SG {} {} {}: {error}", case.sg, case.ml, case.direction))
}

/// Everything the fixture pins about one case, as a boolean "matches" answer so
/// the negative tests can mutate the expectation and require a failure.
fn matches_fixture(embedding: &SubgroupEmbedding, case: &Case) -> Result<(), String> {
    if embedding.subgroup_sg() != case.subgroup {
        return Err(format!(
            "subgroup {} != fixture {}",
            embedding.subgroup_sg(),
            case.subgroup
        ));
    }
    // `Size` is the index of the subgroup lattice in the parent lattice, i.e.
    // the volume ratio in the parent conventional frame.
    let determinant = embedding
        .subgroup_lattice()
        .determinant()
        .map_err(|error| error.to_string())?;
    let parent_determinant = embedding
        .parent_lattice()
        .determinant()
        .map_err(|error| error.to_string())?;
    let index = determinant
        .checked_div(parent_determinant)
        .map_err(|error| error.to_string())?;
    if index.numerator().abs() != i128::from(case.size) || index.denominator() != 1 {
        return Err(format!("size {index} != fixture {}", case.size));
    }
    // The printed basis is in the parent conventional frame; its lattice must be
    // the subgroup lattice, and the printed origin must be the embedding's.
    for row in &case.basis {
        let vector = Vec3R::new(*row);
        if !embedding
            .subgroup_lattice()
            .contains(&vector)
            .map_err(|error| error.to_string())?
        {
            return Err(format!(
                "fixture basis row {vector} is not in the subgroup lattice"
            ));
        }
    }
    if embedding.transform().origin() != &case.origin {
        return Err(format!(
            "origin {} != fixture {}",
            embedding.transform().origin(),
            case.origin
        ));
    }
    let expected = fixture_keys(embedding, &case.elements);
    let found = keys(embedding, embedding.representatives());
    if found != expected {
        return Err(format!(
            "operation sets differ: {} missing, {} unexpected",
            expected.difference(&found).count(),
            found.difference(&expected).count()
        ));
    }
    Ok(())
}

#[test]
fn every_fixture_case_is_reproduced_exactly() {
    let cases = parse_fixture();
    let mut elements = 0usize;
    for case in &cases {
        let embedding = embedding_for(case);
        assert_eq!(
            embedding.representatives().len(),
            case.elements.len(),
            "SG {} {} {}: representative count",
            case.sg,
            case.ml,
            case.direction
        );
        matches_fixture(&embedding, case).unwrap_or_else(|error| {
            panic!("SG {} {} {}: {error}", case.sg, case.ml, case.direction)
        });
        elements += case.elements.len();
        // Every mapped operation must be an actual operation of the strict
        // parent Hall group modulo `L_G`.  The previous check only asserted
        // that `Lattice::reduce` returned `Ok`, which is vacuous for exact
        // rationals; this compares against the parent's own operation set.
        // (`operations()` holds the full Hall set, e.g. 8 for the C-centred
        // #12, while the fixture lists its 4 coset representatives.)
        let parent_operations: Vec<ExactSeitz> = strict_sg_hall_ops(case.sg)
            .expect("strict parent Hall operations")
            .operations
            .iter()
            .map(|operation| {
                operation
                    .reduce(embedding.parent_lattice())
                    .expect("reduce modulo the parent lattice")
            })
            .collect();
        for operation in embedding.operations() {
            assert!(
                parent_operations.contains(operation),
                "SG {} {} {}: mapped operation {operation:?} is not in the strict \
                 parent operation set modulo L_G",
                case.sg,
                case.ml,
                case.direction
            );
        }
    }
    assert_eq!(elements, 90, "coset representatives in the fixture");
}

#[test]
fn the_fixture_checks_reject_a_transposed_basis() {
    let cases = parse_fixture();
    let case = cases
        .iter()
        .find(|case| case.sg == 167)
        .expect("the 167 case");
    let embedding = embedding_for(case);
    matches_fixture(&embedding, case).expect("baseline matches");

    let mut transposed = Case {
        sg: case.sg,
        ml: case.ml.clone(),
        direction: case.direction.clone(),
        subgroup: case.subgroup,
        size: case.size,
        basis: case.basis,
        origin: case.origin,
        elements: case.elements.clone(),
    };
    transposed.basis = [
        [case.basis[0][0], case.basis[1][0], case.basis[2][0]],
        [case.basis[0][1], case.basis[1][1], case.basis[2][1]],
        [case.basis[0][2], case.basis[1][2], case.basis[2][2]],
    ];
    // The printed basis is asymmetric, and its transpose is not a basis of the
    // subgroup lattice, so the lattice check must reject it.
    assert!(matches_fixture(&embedding, &transposed).is_err());
}

#[test]
fn the_fixture_checks_reject_a_shifted_origin_or_a_lost_operation() {
    let cases = parse_fixture();
    let case = cases
        .iter()
        .find(|case| case.sg == 139)
        .expect("the 139 case");
    let embedding = embedding_for(case);
    matches_fixture(&embedding, case).expect("baseline matches");

    let shifted = Case {
        sg: case.sg,
        ml: case.ml.clone(),
        direction: case.direction.clone(),
        subgroup: case.subgroup,
        size: case.size,
        basis: case.basis,
        origin: Vec3R::new([
            case.origin.get(0),
            case.origin.get(1),
            case.origin.get(2).checked_add(Rat::ONE).expect("shift"),
        ]),
        elements: case.elements.clone(),
    };
    assert!(
        matches_fixture(&embedding, &shifted).is_err(),
        "adding one to the origin must fail"
    );

    let mut deleted = Case {
        sg: case.sg,
        ml: case.ml.clone(),
        direction: case.direction.clone(),
        subgroup: case.subgroup,
        size: case.size,
        basis: case.basis,
        origin: case.origin,
        elements: case.elements.clone(),
    };
    deleted.elements.pop();
    assert!(
        matches_fixture(&embedding, &deleted).is_err(),
        "a missing operation must fail"
    );

    let mut renamed = Case {
        sg: case.sg,
        ml: case.ml.clone(),
        direction: case.direction.clone(),
        subgroup: case.subgroup,
        size: case.size,
        basis: case.basis,
        origin: case.origin,
        elements: case.elements.clone(),
    };
    renamed.subgroup = 125;
    assert!(
        matches_fixture(&embedding, &renamed).is_err(),
        "a different subgroup number must fail"
    );
}

#[test]
fn swapping_the_two_cm_directions_is_detected() {
    let cases = parse_fixture();
    let c1 = cases
        .iter()
        .find(|case| case.sg == 225 && case.direction == "C1")
        .expect("C1 case");
    let c2 = cases
        .iter()
        .find(|case| case.sg == 225 && case.direction == "C2")
        .expect("C2 case");
    // Both records select #8 Cm with Size 1, but different bases and different
    // operations: each embedding must reproduce its own fixture and not the
    // other one.
    let embedding_c1 = embedding_for(c1);
    let embedding_c2 = embedding_for(c2);
    matches_fixture(&embedding_c1, c1).expect("C1 matches C1");
    matches_fixture(&embedding_c2, c2).expect("C2 matches C2");
    assert!(
        matches_fixture(&embedding_c1, c2).is_err(),
        "the C1 embedding must not match the C2 fixture"
    );
    assert!(
        matches_fixture(&embedding_c2, c1).is_err(),
        "the C2 embedding must not match the C1 fixture"
    );
    assert_ne!(
        embedding_c1.transform().matrix(),
        embedding_c2.transform().matrix(),
        "the two records use different embeddings"
    );
}

#[test]
fn embeddings_refuse_records_that_do_not_validate() {
    let subgroup = isotropy_subgroup_for_direction(221, "GM4+", IsotropyDirection::Label("P1"))
        .expect("golden record");
    assert!(SubgroupEmbedding::from_isotropy_subgroup(&subgroup).is_ok());

    // A hand-built record that agrees with the table cannot be distinguished,
    // but every mismatch must be caught before any operation is mapped.
    let mut moved = subgroup;
    moved.ordinal += 1;
    assert!(matches!(
        SubgroupEmbedding::from_isotropy_subgroup(&moved),
        Err(SubductionError::StaleIsotropyRecord { .. })
    ));
    let mut tampered = subgroup;
    tampered.record.origin = [1, 0, 0, 1];
    assert!(matches!(
        SubgroupEmbedding::from_isotropy_subgroup(&tampered),
        Err(SubductionError::StaleIsotropyRecord { .. })
    ));
    let mut wrong_parent = subgroup;
    wrong_parent.parent_sg = 0;
    assert!(matches!(
        SubgroupEmbedding::from_isotropy_subgroup(&wrong_parent),
        Err(SubductionError::InvalidSpaceGroup { .. })
    ));
}

#[test]
fn gamma_subduction_of_the_golden_case_is_complete() {
    // The end-to-end deliverable of task 5: 221 GM4+ condenses along P1 into
    // #83 P4/m, and the parent's GM3+ subduces to GM1+ + GM2+.
    let subgroup = isotropy_subgroup_for_direction(221, "GM4+", IsotropyDirection::Label("P1"))
        .expect("condensing record");
    assert_eq!(subgroup.ordinal, 12400);
    assert_eq!(subgroup.record.sg, 83);
    let decomposition = subduce_irrep(&subgroup, "GM3+").expect("decomposition");
    assert_eq!(decomposition.parent_sg(), 221);
    assert_eq!(decomposition.parent_ml(), "GM3+");
    assert_eq!(decomposition.parent_dimension(), 2);
    assert_eq!(decomposition.subgroup_sg(), 83);
    assert_eq!(decomposition.ordinal(), 12400);
    let terms: Vec<(&str, u8, u32)> = decomposition
        .targets()
        .iter()
        .map(|target| (target.ml, target.dimension, target.multiplicity))
        .collect();
    assert_eq!(terms, [("GM1+", 1, 1), ("GM2+", 1, 1)]);
    assert_eq!(decomposition.multiplicity("GM1+"), 1);
    assert_eq!(decomposition.multiplicity("GM2+"), 1);
    for absent in ["GM1-", "GM2-", "GM3+GM4+", "GM3-GM4-"] {
        assert_eq!(decomposition.multiplicity(absent), 0, "{absent}");
    }
    // 2 = 1 + 1 on the nose, and every operation's character is rebuilt.
    let (parent, rebuilt) = decomposition.reconstruction();
    assert_eq!(parent.len(), 8);
    for (expected, found) in parent.iter().zip(rebuilt) {
        assert!((expected - found).norm() <= decomposition.tolerance());
    }
    // A different probe is decided by its characters, not by this fixture.
    let trivial = subduce_irrep(&subgroup, "GM1+").expect("trivial decomposition");
    assert_eq!(trivial.multiplicity("GM1+"), 1);
    assert_eq!(trivial.multiplicity("GM2+"), 0);
}

/// The trivial irrep of `sg` at Gamma: its character is 1 on every operation.
fn trivial_gamma_label(sg: u8) -> &'static str {
    for record in cryspglib::irrep::query::irreps_of(sg) {
        if record.spinor || record.kx != 0 || record.ky != 0 || record.kz != 0 {
            continue;
        }
        if let Ok(row) = record.ordinary_scalar_selected_arm_block_trace() {
            let all_one = row.values().iter().all(|value| (value - 1.0).norm() < 1e-9);
            if all_one {
                return record.ml;
            }
        }
    }
    panic!("space group {sg} has no trivial Gamma irrep");
}

fn is_gamma(record: &cryspglib::irrep::types::IrrepRecord) -> bool {
    !record.spinor && record.kx == 0 && record.ky == 0 && record.kz == 0
}

/// Distinct rotations of a space group: the order of its point group.
fn point_group_order(sg: u8) -> usize {
    let mut rotations: Vec<[i32; 9]> = Vec::new();
    for operation in &cryspglib::irrep::subduction::strict_sg_hall_ops(sg)
        .expect("Hall operations")
        .operations
    {
        let rotation = operation.rotation();
        let flat = [
            rotation[0][0],
            rotation[0][1],
            rotation[0][2],
            rotation[1][0],
            rotation[1][1],
            rotation[1][2],
            rotation[2][0],
            rotation[2][1],
            rotation[2][2],
        ];
        if !rotations.contains(&flat) {
            rotations.push(flat);
        }
    }
    rotations.len()
}

/// Frobenius reciprocity against the shipped identity-subduction table.
///
/// For every Gamma isotropy record whose embedding the frozen table pins, the
/// engine's multiplicity of the subgroup's trivial irrep must equal the stored
/// frequency `i(G)`, and
/// `sum_D dim(D) * mult(trivial_H, D|H) == [G_k : H_k]` must hold over the
/// **complete** complex Gamma irrep set of the parent.
///
/// Scope, counted rather than assumed.  The shipped isotropy table has 1895
/// Gamma condensing records -- the historical `1895 条 Γ 记录` -- and this is
/// where that number comes from: it is the count of Gamma records, not a count
/// of verified identities. Of those, 243 have a subgroup covered by a frozen
/// embedding entry, and 14 are actually pinned: the frozen metadata is keyed by
/// `(parent, subgroup)` because the same subgroup reached from another parent is
/// a different embedding, and a setting that works for one parent can otherwise
/// "validate" while pairing the irreps wrongly (the stored frequencies catch
/// exactly that). The other 229 records report `AmbiguousEmbedding` (199) or
/// `NoValidEmbedding` (30); deriving their per-record settings is task 9.
#[test]
fn frobenius_reciprocity_matches_the_stored_identity_subduction() {
    use cryspglib::irrep::isotropy::isotropy_subgroups;
    use cryspglib::irrep::query;
    use cryspglib::irrep::subduce_irrep_with_embedding;
    use cryspglib::irrep::subduction::SubgroupEmbedding;

    const FROZEN_SUBGROUPS: [u8; 12] = [8, 12, 15, 19, 22, 23, 45, 47, 83, 123, 126, 148];
    let mut gamma_records = 0usize;
    let mut frozen_subgroup_records = 0usize;
    let mut pinned = 0usize;
    let mut ambiguous = 0usize;
    let mut unresolved_setting = 0usize;
    let mut errors: Vec<String> = Vec::new();

    for sg in 1..=230u8 {
        for probe in query::irreps_of(sg) {
            if !is_gamma(probe) {
                continue;
            }
            let Ok(subgroups) = isotropy_subgroups(sg, probe.ml) else {
                continue;
            };
            for subgroup in subgroups {
                gamma_records += 1;
                let Ok(subgroup_sg) = u8::try_from(subgroup.record.sg) else {
                    continue;
                };
                if !FROZEN_SUBGROUPS.contains(&subgroup_sg) {
                    continue;
                }
                frozen_subgroup_records += 1;
                let embedding = match SubgroupEmbedding::from_isotropy_subgroup(&subgroup) {
                    Ok(embedding) => embedding,
                    Err(cryspglib::irrep::SubductionError::AmbiguousEmbedding { .. }) => {
                        ambiguous += 1;
                        continue;
                    }
                    // No signed-permutation setting works for this record, so
                    // its real setting (and possibly a child origin shift like
                    // #126's) is not in the frozen table yet.  Task 9 derives
                    // it from the oracle; until then this is an explicit gap,
                    // never a guessed embedding.
                    Err(cryspglib::irrep::SubductionError::NoValidEmbedding { .. }) => {
                        unresolved_setting += 1;
                        continue;
                    }
                    Err(error) => {
                        errors.push(format!(
                            "ordinal {} (SG {sg} {} -> #{subgroup_sg}): {error}",
                            subgroup.ordinal, probe.ml
                        ));
                        continue;
                    }
                };

                // Stored frequencies, one per parent irrep at Gamma; entries
                // for other domains must agree with each other.
                let stored = match subgroup.identity_subduction() {
                    Ok(stored) => stored,
                    Err(error) => {
                        errors.push(format!("ordinal {}: {error}", subgroup.ordinal));
                        continue;
                    }
                };
                let mut stored_frequencies: Vec<(&'static str, u16)> = Vec::new();
                for entry in stored
                    .iter()
                    .filter(|entry| entry.parent_k.numerators == [0, 0, 0])
                {
                    match stored_frequencies
                        .iter()
                        .find(|(ml, _)| *ml == entry.parent_ml)
                    {
                        Some((_, frequency)) if *frequency != entry.frequency => {
                            errors.push(format!(
                                "ordinal {}: {} has frequency {} and {} across domains",
                                subgroup.ordinal, entry.parent_ml, frequency, entry.frequency
                            ))
                        }
                        Some(_) => {}
                        None => stored_frequencies.push((entry.parent_ml, entry.frequency)),
                    }
                }

                let trivial = trivial_gamma_label(subgroup_sg);
                let mut engine_frequencies: Vec<(&'static str, u32)> = Vec::new();
                let mut frobenius_sum = 0i64;
                for candidate in query::irreps_of(sg) {
                    if !is_gamma(candidate) {
                        continue;
                    }
                    let result =
                        match subduce_irrep_with_embedding(&subgroup, &embedding, candidate) {
                            Ok(result) => result,
                            Err(error) => {
                                errors.push(format!(
                                    "ordinal {} probe {}: {error}",
                                    subgroup.ordinal, candidate.ml
                                ));
                                continue;
                            }
                        };
                    let multiplicity = result.multiplicity(trivial);
                    if multiplicity > 0 {
                        engine_frequencies.push((candidate.ml, multiplicity));
                    }
                    frobenius_sum += i64::from(result.parent_dimension()) * i64::from(multiplicity);
                }

                for (ml, frequency) in &stored_frequencies {
                    match engine_frequencies.iter().find(|(label, _)| label == ml) {
                        Some((_, found)) if *found == u32::from(*frequency) => {}
                        Some((_, found)) => errors.push(format!(
                            "ordinal {} {ml}: engine {found} != stored {frequency}",
                            subgroup.ordinal
                        )),
                        None => errors.push(format!(
                            "ordinal {} {ml}: stored frequency {frequency} but the engine \
                             reports none",
                            subgroup.ordinal
                        )),
                    }
                }
                for (ml, found) in &engine_frequencies {
                    if !stored_frequencies.iter().any(|(label, _)| label == ml) {
                        errors.push(format!(
                            "ordinal {} {ml}: engine reports {found} but the stored table \
                             has no entry",
                            subgroup.ordinal
                        ));
                    }
                }

                // The record's own condensing irrep must contain the trivial
                // representation: that is what makes the subgroup its isotropy
                // subgroup, and the stored table agrees.
                if !engine_frequencies.iter().any(|(ml, _)| *ml == probe.ml) {
                    errors.push(format!(
                        "ordinal {}: condensing irrep {} does not subduce the trivial rep",
                        subgroup.ordinal, probe.ml
                    ));
                }

                let index = point_group_order(sg) / embedding.representatives().len();
                if frobenius_sum != index as i64 {
                    errors.push(format!(
                        "ordinal {}: Frobenius sum {frobenius_sum} != index {index}",
                        subgroup.ordinal
                    ));
                }
                pinned += 1;
            }
        }
    }

    println!(
        "Gamma records {gamma_records} | frozen-subgroup records {frozen_subgroup_records} | \
         pinned {pinned} | ambiguous {ambiguous} | settings outside the search {unresolved_setting} \
         | errors {}",
        errors.len()
    );
    assert!(errors.is_empty(), "{}", errors.join("\n"));
    // 1895 is the historical "Gamma records" figure; it counts records, not
    // verified identities, which is why the plan asks for the scope to be
    // recounted rather than reused.
    assert_eq!(
        gamma_records, 1895,
        "Gamma isotropy records in the shipped table"
    );
    assert_eq!(frozen_subgroup_records, 243);
    assert_eq!(pinned, 14, "records pinned by the expanded oracle fixture");
    assert_eq!(
        ambiguous + unresolved_setting,
        229,
        "records whose setting needs task 9's metadata"
    );
    assert_eq!(ambiguous, 199, "records with several consistent settings");
    assert_eq!(
        unresolved_setting, 30,
        "records whose setting is not a signed permutation (or needs a shift)"
    );
    assert!(pinned + ambiguous + unresolved_setting == frozen_subgroup_records);
}

/// The shipped rows carry the Bloch phase of their representatives.
///
/// SG 139 `P1` at k = (1/2,1/2,1/2) has the identity operation at t = 0 with
/// chi = 1 and the same element at the I-centring vector (1/2,1/2,1/2) with
/// chi = -i.  That fixes the convention to
/// `chi(t + L) = chi(t) * exp(+2 pi i k . L)`: `k . L = 3/4`, and `+3/4` gives
/// `-i` while `-3/4` would give `+i`.  A lost or flipped phase is therefore a
/// detectable error, not a convention choice.
#[test]
fn shipped_rows_carry_the_bloch_phase_of_their_representatives() {
    use cryspglib::irrep::query;
    use cryspglib::irrep::subduction::{Rat, Vec3R, bloch_phase};

    let record = query::irreps_of(139)
        .iter()
        .find(|record| record.ml == "P1" && !record.spinor)
        .expect("139 P1");
    assert_eq!((record.kx, record.ky, record.kz, record.kd), (1, 1, 1, 2));
    let row = record
        .ordinary_scalar_selected_arm_block_trace()
        .expect("row");
    let identity = [1, 0, 0, 0, 1, 0, 0, 0, 1];
    let mut at_origin = None;
    let mut at_centring = None;
    for (value, operation) in row.values().iter().zip(row.operations()) {
        if operation.rotation != identity {
            continue;
        }
        if operation.translation == [0.0, 0.0, 0.0] {
            at_origin = Some(*value);
        }
        if operation.translation == [0.5, 0.5, 0.5] {
            at_centring = Some(*value);
        }
    }
    let at_origin = at_origin.expect("identity at the origin");
    let at_centring = at_centring.expect("identity at the centring vector");
    assert!((at_origin - 1.0).norm() < 1e-9);
    assert!((at_centring - num_complex::Complex64::new(0.0, -1.0)).norm() < 1e-9);

    let wave_vector = Vec3R::new([Rat::new(1, 2).unwrap(); 3]);
    let lattice_vector = Vec3R::new([Rat::new(1, 2).unwrap(); 3]);
    let phase = bloch_phase(&wave_vector, &lattice_vector).unwrap();
    assert!(
        (at_origin * phase - at_centring).norm() < 1e-9,
        "the shipped row uses chi(t + L) = chi(t) exp(+2 pi i k.L)"
    );
    assert!(
        (at_origin * phase.conj() - at_centring).norm() > 0.5,
        "the opposite phase sign does not reproduce the shipped row"
    );
}

#[test]
fn non_gamma_probes_decompose_their_folded_block() {
    use cryspglib::irrep::query;
    use cryspglib::irrep::subduce_irrep_with_embedding;
    use cryspglib::irrep::subduction::{SubgroupEmbedding, fold_wave_vector};

    // (parent, condensing irrep, direction, probe, expected folded k, expected targets)
    /// (parent, condensing irrep, direction, probe, folded k, expected targets)
    type FoldCase = (
        u8,
        &'static str,
        &'static str,
        &'static str,
        [(i128, i128); 3],
        &'static [(&'static str, u32)],
    );
    let cases: [FoldCase; 5] = [
        (16, "R1", "P1", "X1", [(1, 1), (0, 1), (0, 1)], &[("T1", 1)]),
        (16, "R1", "P1", "X2", [(1, 1), (0, 1), (0, 1)], &[("T2", 1)]),
        (16, "R1", "P1", "Y1", [(0, 1), (1, 1), (0, 1)], &[("Y1", 1)]),
        (16, "R1", "P1", "Z1", [(0, 1), (0, 1), (1, 1)], &[("Z1", 1)]),
        (
            221,
            "GM4+",
            "P1",
            "R1+",
            [(1, 2), (-1, 2), (1, 2)],
            &[("A1+", 1)],
        ),
    ];
    for (sg, ml, direction, probe_ml, folded, targets) in cases {
        let subgroup = isotropy_subgroup_for_direction(sg, ml, IsotropyDirection::Label(direction))
            .expect("condensing record");
        let embedding = SubgroupEmbedding::from_isotropy_subgroup(&subgroup).expect("embedding");
        let probe = query::irreps_of(sg)
            .iter()
            .find(|record| record.ml == probe_ml && !record.spinor)
            .unwrap_or_else(|| panic!("SG {sg} has no probe {probe_ml}"));
        // The fold itself is T^T k_G, computed here independently.
        let k_g = {
            let denominator = i128::from(probe.kd);
            cryspglib::irrep::subduction::Vec3R::new([
                Rat::new(i128::from(probe.kx), denominator).unwrap(),
                Rat::new(i128::from(probe.ky), denominator).unwrap(),
                Rat::new(i128::from(probe.kz), denominator).unwrap(),
            ])
        };
        let expected: Vec<Rat> = folded
            .iter()
            .map(|(numerator, denominator)| Rat::new(*numerator, *denominator).expect("rational"))
            .collect();
        let computed = fold_wave_vector(embedding.transform(), &k_g).expect("fold");
        assert_eq!(
            computed.as_array(),
            expected.as_slice(),
            "SG {sg} {probe_ml}"
        );

        let result = subduce_irrep_with_embedding(&subgroup, &embedding, probe)
            .unwrap_or_else(|error| panic!("SG {sg} {probe_ml}: {error}"));
        assert_eq!(result.folded_k().as_slice(), expected.as_slice());
        let found: Vec<(&str, u32)> = result
            .targets()
            .iter()
            .map(|target| (target.ml, target.multiplicity))
            .collect();
        assert_eq!(found, targets, "SG {sg} {probe_ml} targets");
        let dimension_sum: u32 = result
            .targets()
            .iter()
            .map(|target| u32::from(target.dimension) * target.multiplicity)
            .sum();
        assert_eq!(
            dimension_sum,
            u32::from(result.parent_dimension()),
            "SG {sg} {probe_ml} dimension sum"
        );
        let (parent, rebuilt) = result.reconstruction();
        assert!(!parent.is_empty());
        for (index, (expected, found)) in parent.iter().zip(rebuilt).enumerate() {
            assert!(
                (expected - found).norm() <= result.tolerance(),
                "SG {sg} {probe_ml} operation {index}: {found} != {expected}"
            );
        }
        // Every reconstructed value must be a genuine character value of the
        // folded block: the magnitudes cannot exceed the dimension.
        for value in parent {
            assert!(value.norm() <= f64::from(result.parent_dimension()) + 1e-9);
        }
    }
}

/// Scanning the frozen pairs, probes split into three outcomes: a folded block
/// with data, a multi-arm star (task 8), or missing subgroup data.  The counts
/// are pinned so a silent change in either direction is visible.
#[test]
fn non_gamma_coverage_is_counted_not_assumed() {
    use cryspglib::irrep::query;
    use cryspglib::irrep::subduction::SubgroupEmbedding;
    use cryspglib::irrep::{SubductionError, subduce_irrep_with_embedding};

    let mut folded = 0usize;
    let mut multi_arm = 0usize;
    let mut missing = 0usize;
    let mut other: Vec<String> = Vec::new();
    for (sg, ml, direction) in [
        (16u8, "R1", "P1"),
        (221, "GM4+", "P1"),
        (221, "GM4+", "P2"),
        (139, "M1-", "P1"),
    ] {
        let subgroup = isotropy_subgroup_for_direction(sg, ml, IsotropyDirection::Label(direction))
            .expect("record");
        let embedding = SubgroupEmbedding::from_isotropy_subgroup(&subgroup).expect("embedding");
        for probe in query::irreps_of(sg) {
            if probe.spinor {
                continue;
            }
            match subduce_irrep_with_embedding(&subgroup, &embedding, probe) {
                Ok(_) => folded += 1,
                Err(SubductionError::UnsupportedMultiArmStar { .. }) => multi_arm += 1,
                Err(SubductionError::MissingIrrepData { .. }) => missing += 1,
                Err(error) => other.push(format!("SG {sg} {}: {error}", probe.ml)),
            }
        }
    }
    println!(
        "non-Gamma probes: folded {folded} | multi-arm {multi_arm} | missing data {missing} | \
         other {}",
        other.len()
    );
    assert!(other.is_empty(), "{}", other.join("\n"));
    assert!(folded > 0 && multi_arm > 0, "both outcomes must occur");
    // Measured over the four sampled pairs.  The SG 139 `M1-` P1 -> #126 pair
    // contributes 20 folded Gamma/M single-arm probes (M1-/M1+/M2+/M2- and the
    // Gamma rows) and 17 genuine multi-arm stars; it is folded at all only
    // because the representatives keep their `L_H` translations.  Missing data
    // does not occur over these four pairs: their folded blocks all exist, and
    // the `MissingIrrepData` gap path is covered by the unit tests instead.
    assert_eq!((folded, multi_arm, missing), (92, 57, 0));
}
