//! Subgroup embeddings against the pinned oracle fixture.
//!
//! Task 4 of `docs/full-irrep-subduction-plan.md`.  `tests/data/isotropy/
//! operations.txt` is generated by `scripts/verify_isotropy_operations.py`
//! from the pinned `iso.zip`; it holds, per (space group, irrep, direction)
//! case, the subgroup's printed basis, origin and operations in the parent
//! conventional frame (column-action rotations, exact rational translations).
//!
//! The tests here check that `SubgroupEmbedding` reproduces that fixture
//! exactly, and that the checks it uses have teeth: a transposed basis, a
//! shifted origin, a lost operation or a swapped direction must all fail.

use std::collections::BTreeSet;
use std::path::PathBuf;

use cryspglib::irrep::isotropy::{isotropy_subgroup_for_direction, IsotropyDirection};
use cryspglib::irrep::subduction::{ExactSeitz, Rat, SubgroupEmbedding, SubductionError, Vec3R};
use cryspglib::irrep::subduce_irrep;

/// One fixture case.
struct Case {
    sg: u8,
    ml: String,
    direction: String,
    subgroup: u8,
    size: i32,
    basis: [[Rat; 3]; 3],
    origin: Vec3R,
    elements: Vec<(String, ExactSeitz)>,
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data")
        .join("isotropy")
        .join("operations.txt")
}

fn rational(token: &str) -> Rat {
    match token.split_once('/') {
        Some((numerator, denominator)) => Rat::new(
            numerator.parse().expect("numerator"),
            denominator.parse().expect("denominator"),
        )
        .expect("valid rational"),
        None => Rat::from_integer(token.parse().expect("integer")),
    }
}

fn vector(token: &str) -> Vec3R {
    let values: Vec<Rat> = token.split(',').map(rational).collect();
    assert_eq!(values.len(), 3, "three components in {token:?}");
    Vec3R::new([values[0], values[1], values[2]])
}

fn rotation(token: &str) -> [[Rat; 3]; 3] {
    let rows: Vec<Vec<Rat>> = token
        .split(';')
        .map(|row| row.split(',').map(rational).collect())
        .collect();
    assert_eq!(rows.len(), 3, "three rows in {token:?}");
    assert!(rows.iter().all(|row| row.len() == 3), "three columns in {token:?}");
    [
        [rows[0][0], rows[0][1], rows[0][2]],
        [rows[1][0], rows[1][1], rows[1][2]],
        [rows[2][0], rows[2][1], rows[2][2]],
    ]
}

fn parse_fixture() -> Vec<Case> {
    let text = std::fs::read_to_string(fixture_path()).expect("read the operation fixture");
    let mut cases: Vec<Case> = Vec::new();
    for line in text.lines() {
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        let mut parts = line.split_whitespace();
        match parts.next().expect("a token") {
            "case" => {
                cases.push(Case {
                    sg: parts.next().expect("sg").parse().expect("sg"),
                    ml: parts.next().expect("ml").to_string(),
                    direction: parts.next().expect("direction").to_string(),
                    subgroup: parts.next().expect("subgroup").parse().expect("subgroup"),
                    size: parts.next().expect("size").parse().expect("size"),
                    basis: [[Rat::ZERO; 3]; 3],
                    origin: Vec3R::zero(),
                    elements: Vec::new(),
                });
            }
            "basis" => {
                let case = cases.last_mut().expect("a case before its basis");
                // One token holding all three row vectors, `;`-separated.
                case.basis = rotation(parts.next().expect("basis"));
            }
            "origin" => {
                let case = cases.last_mut().expect("a case before its origin");
                case.origin = vector(parts.next().expect("origin"));
            }
            "element" => {
                let case = cases.last_mut().expect("a case before its elements");
                let label = parts.next().expect("label").to_string();
                let matrix = rotation(parts.next().expect("rotation"));
                let translation = vector(parts.next().expect("translation"));
                let integers = [
                    [matrix[0][0].to_i32().unwrap(), matrix[0][1].to_i32().unwrap(), matrix[0][2].to_i32().unwrap()],
                    [matrix[1][0].to_i32().unwrap(), matrix[1][1].to_i32().unwrap(), matrix[1][2].to_i32().unwrap()],
                    [matrix[2][0].to_i32().unwrap(), matrix[2][1].to_i32().unwrap(), matrix[2][2].to_i32().unwrap()],
                ];
                case.elements
                    .push((label, ExactSeitz::new(integers, translation)));
            }
            other => panic!("unknown fixture directive {other:?}"),
        }
    }
    assert_eq!(cases.len(), 10, "the fixture holds ten cases");
    cases
}

/// Canonical `(rotation, translation)` keys of an operation set modulo the
/// embedding's parent lattice: the comparison used throughout this file.
fn keys(embedding: &SubgroupEmbedding, operations: &[ExactSeitz]) -> BTreeSet<(String, String)> {
    operations
        .iter()
        .map(|operation| {
            let reduced = operation
                .reduce(embedding.parent_lattice())
                .expect("reduce modulo the parent lattice");
            let rotation = reduced
                .rotation()
                .iter()
                .map(|row| format!("{row:?}"))
                .collect::<Vec<_>>()
                .join(";");
            let translation = reduced
                .translation()
                .as_array()
                .iter()
                .map(|value| value.to_string())
                .collect::<Vec<_>>()
                .join(",");
            (rotation, translation)
        })
        .collect()
}

fn fixture_keys(embedding: &SubgroupEmbedding, elements: &[(String, ExactSeitz)]) -> BTreeSet<(String, String)> {
    keys(
        embedding,
        &elements
            .iter()
            .map(|(_, operation)| *operation)
            .collect::<Vec<_>>(),
    )
}

fn embedding_for(case: &Case) -> SubgroupEmbedding {
    let subgroup = isotropy_subgroup_for_direction(
        case.sg,
        &case.ml,
        IsotropyDirection::Label(&case.direction),
    )
    .unwrap_or_else(|error| panic!("SG {} {} {}: {error}", case.sg, case.ml, case.direction));
    SubgroupEmbedding::from_isotropy_subgroup(&subgroup)
        .unwrap_or_else(|error| panic!("SG {} {} {}: {error}", case.sg, case.ml, case.direction))
}

/// Everything the fixture pins about one case, as a boolean "matches" answer so
/// the negative tests can mutate the expectation and require a failure.
fn matches_fixture(embedding: &SubgroupEmbedding, case: &Case) -> Result<(), String> {
    if embedding.subgroup_sg() != case.subgroup {
        return Err(format!(
            "subgroup {} != fixture {}",
            embedding.subgroup_sg(),
            case.subgroup
        ));
    }
    // `Size` is the index of the subgroup lattice in the parent lattice, i.e.
    // the volume ratio in the parent conventional frame.
    let determinant = embedding
        .subgroup_lattice()
        .determinant()
        .map_err(|error| error.to_string())?;
    let parent_determinant = embedding
        .parent_lattice()
        .determinant()
        .map_err(|error| error.to_string())?;
    let index = determinant
        .checked_div(parent_determinant)
        .map_err(|error| error.to_string())?;
    if index.numerator().abs() != i128::from(case.size) || index.denominator() != 1 {
        return Err(format!("size {index} != fixture {}", case.size));
    }
    // The printed basis is in the parent conventional frame; its lattice must be
    // the subgroup lattice, and the printed origin must be the embedding's.
    for row in &case.basis {
        let vector = Vec3R::new(*row);
        if !embedding
            .subgroup_lattice()
            .contains(&vector)
            .map_err(|error| error.to_string())?
        {
            return Err(format!("fixture basis row {vector} is not in the subgroup lattice"));
        }
    }
    if embedding.transform().origin() != &case.origin {
        return Err(format!(
            "origin {} != fixture {}",
            embedding.transform().origin(),
            case.origin
        ));
    }
    let expected = fixture_keys(embedding, &case.elements);
    let found = keys(embedding, embedding.representatives());
    if found != expected {
        return Err(format!(
            "operation sets differ: {} missing, {} unexpected",
            expected.difference(&found).count(),
            found.difference(&expected).count()
        ));
    }
    Ok(())
}

#[test]
fn every_fixture_case_is_reproduced_exactly() {
    let cases = parse_fixture();
    let mut elements = 0usize;
    for case in &cases {
        let embedding = embedding_for(case);
        assert_eq!(
            embedding.representatives().len(),
            case.elements.len(),
            "SG {} {} {}: representative count",
            case.sg,
            case.ml,
            case.direction
        );
        matches_fixture(&embedding, case).unwrap_or_else(|error| {
            panic!(
                "SG {} {} {}: {error}",
                case.sg, case.ml, case.direction
            )
        });
        elements += case.elements.len();
        // Every mapped operation must be a parent operation: the fixture
        // comparison above only sees representatives, this sees all of them.
        for operation in embedding.operations() {
            assert!(
                embedding.parent_lattice().reduce(operation.translation()).is_ok(),
                "SG {} {} {}: operation is not in the parent frame",
                case.sg,
                case.ml,
                case.direction
            );
        }
    }
    assert_eq!(elements, 70, "coset representatives in the fixture");
}

#[test]
fn the_fixture_checks_reject_a_transposed_basis() {
    let cases = parse_fixture();
    let case = cases
        .iter()
        .find(|case| case.sg == 167)
        .expect("the 167 case");
    let embedding = embedding_for(case);
    matches_fixture(&embedding, case).expect("baseline matches");

    let mut transposed = Case {
        sg: case.sg,
        ml: case.ml.clone(),
        direction: case.direction.clone(),
        subgroup: case.subgroup,
        size: case.size,
        basis: case.basis,
        origin: case.origin,
        elements: case.elements.clone(),
    };
    transposed.basis = [
        [case.basis[0][0], case.basis[1][0], case.basis[2][0]],
        [case.basis[0][1], case.basis[1][1], case.basis[2][1]],
        [case.basis[0][2], case.basis[1][2], case.basis[2][2]],
    ];
    // The printed basis is asymmetric, and its transpose is not a basis of the
    // subgroup lattice, so the lattice check must reject it.
    assert!(matches_fixture(&embedding, &transposed).is_err());
}

#[test]
fn the_fixture_checks_reject_a_shifted_origin_or_a_lost_operation() {
    let cases = parse_fixture();
    let case = cases
        .iter()
        .find(|case| case.sg == 139)
        .expect("the 139 case");
    let embedding = embedding_for(case);
    matches_fixture(&embedding, case).expect("baseline matches");

    let shifted = Case {
        sg: case.sg,
        ml: case.ml.clone(),
        direction: case.direction.clone(),
        subgroup: case.subgroup,
        size: case.size,
        basis: case.basis,
        origin: Vec3R::new([
            case.origin.get(0),
            case.origin.get(1),
            case.origin.get(2).checked_add(Rat::ONE).expect("shift"),
        ]),
        elements: case.elements.clone(),
    };
    assert!(
        matches_fixture(&embedding, &shifted).is_err(),
        "adding one to the origin must fail"
    );

    let mut deleted = Case {
        sg: case.sg,
        ml: case.ml.clone(),
        direction: case.direction.clone(),
        subgroup: case.subgroup,
        size: case.size,
        basis: case.basis,
        origin: case.origin,
        elements: case.elements.clone(),
    };
    deleted.elements.pop();
    assert!(
        matches_fixture(&embedding, &deleted).is_err(),
        "a missing operation must fail"
    );

    let mut renamed = Case {
        sg: case.sg,
        ml: case.ml.clone(),
        direction: case.direction.clone(),
        subgroup: case.subgroup,
        size: case.size,
        basis: case.basis,
        origin: case.origin,
        elements: case.elements.clone(),
    };
    renamed.subgroup = 125;
    assert!(
        matches_fixture(&embedding, &renamed).is_err(),
        "a different subgroup number must fail"
    );
}

#[test]
fn swapping_the_two_cm_directions_is_detected() {
    let cases = parse_fixture();
    let c1 = cases
        .iter()
        .find(|case| case.sg == 225 && case.direction == "C1")
        .expect("C1 case");
    let c2 = cases
        .iter()
        .find(|case| case.sg == 225 && case.direction == "C2")
        .expect("C2 case");
    // Both records select #8 Cm with Size 1, but different bases and different
    // operations: each embedding must reproduce its own fixture and not the
    // other one.
    let embedding_c1 = embedding_for(c1);
    let embedding_c2 = embedding_for(c2);
    matches_fixture(&embedding_c1, c1).expect("C1 matches C1");
    matches_fixture(&embedding_c2, c2).expect("C2 matches C2");
    assert!(
        matches_fixture(&embedding_c1, c2).is_err(),
        "the C1 embedding must not match the C2 fixture"
    );
    assert!(
        matches_fixture(&embedding_c2, c1).is_err(),
        "the C2 embedding must not match the C1 fixture"
    );
    assert_ne!(
        embedding_c1.transform().matrix(),
        embedding_c2.transform().matrix(),
        "the two records use different embeddings"
    );
}

#[test]
fn embeddings_refuse_records_that_do_not_validate() {
    let subgroup = isotropy_subgroup_for_direction(221, "GM4+", IsotropyDirection::Label("P1"))
        .expect("golden record");
    assert!(SubgroupEmbedding::from_isotropy_subgroup(&subgroup).is_ok());

    // A hand-built record that agrees with the table cannot be distinguished,
    // but every mismatch must be caught before any operation is mapped.
    let mut moved = subgroup;
    moved.ordinal += 1;
    assert!(matches!(
        SubgroupEmbedding::from_isotropy_subgroup(&moved),
        Err(SubductionError::StaleIsotropyRecord { .. })
    ));
    let mut tampered = subgroup;
    tampered.record.origin = [1, 0, 0, 1];
    assert!(matches!(
        SubgroupEmbedding::from_isotropy_subgroup(&tampered),
        Err(SubductionError::StaleIsotropyRecord { .. })
    ));
    let mut wrong_parent = subgroup;
    wrong_parent.parent_sg = 0;
    assert!(matches!(
        SubgroupEmbedding::from_isotropy_subgroup(&wrong_parent),
        Err(SubductionError::InvalidSpaceGroup { .. })
    ));
}

#[test]
fn gamma_subduction_of_the_golden_case_is_complete() {
    // The end-to-end deliverable of task 5: 221 GM4+ condenses along P1 into
    // #83 P4/m, and the parent's GM3+ subduces to GM1+ + GM2+.
    let subgroup =
        isotropy_subgroup_for_direction(221, "GM4+", IsotropyDirection::Label("P1"))
            .expect("condensing record");
    assert_eq!(subgroup.ordinal, 12400);
    assert_eq!(subgroup.record.sg, 83);
    let decomposition = subduce_irrep(&subgroup, "GM3+").expect("decomposition");
    assert_eq!(decomposition.parent_sg(), 221);
    assert_eq!(decomposition.parent_ml(), "GM3+");
    assert_eq!(decomposition.parent_dimension(), 2);
    assert_eq!(decomposition.subgroup_sg(), 83);
    assert_eq!(decomposition.ordinal(), 12400);
    let terms: Vec<(&str, u8, u32)> = decomposition
        .targets()
        .iter()
        .map(|target| (target.ml, target.dimension, target.multiplicity))
        .collect();
    assert_eq!(terms, [("GM1+", 1, 1), ("GM2+", 1, 1)]);
    assert_eq!(decomposition.multiplicity("GM1+"), 1);
    assert_eq!(decomposition.multiplicity("GM2+"), 1);
    for absent in ["GM1-", "GM2-", "GM3+GM4+", "GM3-GM4-"] {
        assert_eq!(decomposition.multiplicity(absent), 0, "{absent}");
    }
    // 2 = 1 + 1 on the nose, and every operation's character is rebuilt.
    let (parent, rebuilt) = decomposition.reconstruction();
    assert_eq!(parent.len(), 8);
    for (expected, found) in parent.iter().zip(rebuilt) {
        assert!((expected - found).norm() <= decomposition.tolerance());
    }
    // A different probe is decided by its characters, not by this fixture.
    let trivial = subduce_irrep(&subgroup, "GM1+").expect("trivial decomposition");
    assert_eq!(trivial.multiplicity("GM1+"), 1);
    assert_eq!(trivial.multiplicity("GM2+"), 0);
}

/// The trivial irrep of `sg` at Gamma: its character is 1 on every operation.
fn trivial_gamma_label(sg: u8) -> &'static str {
    for record in cryspglib::irrep::query::irreps_of(sg) {
        if record.spinor || record.kx != 0 || record.ky != 0 || record.kz != 0 {
            continue;
        }
        if let Ok(row) = record.ordinary_scalar_selected_arm_block_trace() {
            let all_one = row.values().iter().all(|value| (value - 1.0).norm() < 1e-9);
            if all_one {
                return record.ml;
            }
        }
    }
    panic!("space group {sg} has no trivial Gamma irrep");
}

fn is_gamma(record: &cryspglib::irrep::types::IrrepRecord) -> bool {
    !record.spinor && record.kx == 0 && record.ky == 0 && record.kz == 0
}

/// Distinct rotations of a space group: the order of its point group.
fn point_group_order(sg: u8) -> usize {
    let mut rotations: Vec<[i32; 9]> = Vec::new();
    for operation in &cryspglib::irrep::subduction::strict_sg_hall_ops(sg)
        .expect("Hall operations")
        .operations
    {
        let rotation = operation.rotation();
        let flat = [
            rotation[0][0], rotation[0][1], rotation[0][2],
            rotation[1][0], rotation[1][1], rotation[1][2],
            rotation[2][0], rotation[2][1], rotation[2][2],
        ];
        if !rotations.contains(&flat) {
            rotations.push(flat);
        }
    }
    rotations.len()
}

/// Frobenius reciprocity against the shipped identity-subduction table.
///
/// For every Gamma isotropy record whose embedding the frozen table pins, the
/// engine's multiplicity of the subgroup's trivial irrep must equal the stored
/// frequency `i(G)`, and
/// `sum_D dim(D) * mult(trivial_H, D|H) == [G_k : H_k]` must hold over the
/// **complete** complex Gamma irrep set of the parent.
///
/// Scope, counted rather than assumed.  The shipped isotropy table has 1895
/// Gamma condensing records -- the historical `1895 条 Γ 记录` -- and this is
/// where that number comes from: it is the count of Gamma records, not a count
/// of verified identities.  Of those, 210 have a subgroup covered by a frozen
/// embedding entry, and 10 are actually pinned: the frozen metadata is keyed by
/// `(parent, subgroup)` because the same subgroup reached from another parent is
/// a different embedding, and a setting that works for one parent can otherwise
/// "validate" while pairing the irreps wrongly (the stored frequencies catch
/// exactly that).  The other 200 records report `AmbiguousEmbedding` instead of
/// guessing; deriving their per-record settings offline is task 9.
#[test]
fn frobenius_reciprocity_matches_the_stored_identity_subduction() {
    use cryspglib::irrep::isotropy::isotropy_subgroups;
    use cryspglib::irrep::query;
    use cryspglib::irrep::subduction::SubgroupEmbedding;
    use cryspglib::irrep::subduce_irrep_with_embedding;

    const FROZEN_SUBGROUPS: [u8; 9] = [8, 12, 15, 22, 47, 83, 123, 126, 148];
    let mut gamma_records = 0usize;
    let mut frozen_subgroup_records = 0usize;
    let mut pinned = 0usize;
    let mut ambiguous = 0usize;
    let mut unresolved_setting = 0usize;
    let mut errors: Vec<String> = Vec::new();

    for sg in 1..=230u8 {
        for probe in query::irreps_of(sg) {
            if !is_gamma(probe) {
                continue;
            }
            let Ok(subgroups) = isotropy_subgroups(sg, probe.ml) else {
                continue;
            };
            for subgroup in subgroups {
                gamma_records += 1;
                let Ok(subgroup_sg) = u8::try_from(subgroup.record.sg) else {
                    continue;
                };
                if !FROZEN_SUBGROUPS.contains(&subgroup_sg) {
                    continue;
                }
                frozen_subgroup_records += 1;
                let embedding = match SubgroupEmbedding::from_isotropy_subgroup(&subgroup) {
                    Ok(embedding) => embedding,
                    Err(cryspglib::irrep::SubductionError::AmbiguousEmbedding { .. }) => {
                        ambiguous += 1;
                        continue;
                    }
                    // No signed-permutation setting works for this record, so
                    // its real setting (and possibly a child origin shift like
                    // #126's) is not in the frozen table yet.  Task 9 derives
                    // it from the oracle; until then this is an explicit gap,
                    // never a guessed embedding.
                    Err(cryspglib::irrep::SubductionError::NoValidEmbedding { .. }) => {
                        unresolved_setting += 1;
                        continue;
                    }
                    Err(error) => {
                        errors.push(format!(
                            "ordinal {} (SG {sg} {} -> #{subgroup_sg}): {error}",
                            subgroup.ordinal, probe.ml
                        ));
                        continue;
                    }
                };

                // Stored frequencies, one per parent irrep at Gamma; entries
                // for other domains must agree with each other.
                let stored = match subgroup.identity_subduction() {
                    Ok(stored) => stored,
                    Err(error) => {
                        errors.push(format!("ordinal {}: {error}", subgroup.ordinal));
                        continue;
                    }
                };
                let mut stored_frequencies: Vec<(&'static str, u16)> = Vec::new();
                for entry in stored
                    .iter()
                    .filter(|entry| entry.parent_k.numerators == [0, 0, 0])
                {
                    match stored_frequencies
                        .iter()
                        .find(|(ml, _)| *ml == entry.parent_ml)
                    {
                        Some((_, frequency)) if *frequency != entry.frequency => errors.push(
                            format!(
                                "ordinal {}: {} has frequency {} and {} across domains",
                                subgroup.ordinal, entry.parent_ml, frequency, entry.frequency
                            ),
                        ),
                        Some(_) => {}
                        None => stored_frequencies.push((entry.parent_ml, entry.frequency)),
                    }
                }

                let trivial = trivial_gamma_label(subgroup_sg);
                let mut engine_frequencies: Vec<(&'static str, u32)> = Vec::new();
                let mut frobenius_sum = 0i64;
                for candidate in query::irreps_of(sg) {
                    if !is_gamma(candidate) {
                        continue;
                    }
                    let result = match subduce_irrep_with_embedding(&subgroup, &embedding, candidate)
                    {
                        Ok(result) => result,
                        Err(error) => {
                            errors.push(format!(
                                "ordinal {} probe {}: {error}",
                                subgroup.ordinal, candidate.ml
                            ));
                            continue;
                        }
                    };
                    let multiplicity = result.multiplicity(trivial);
                    if multiplicity > 0 {
                        engine_frequencies.push((candidate.ml, multiplicity));
                    }
                    frobenius_sum +=
                        i64::from(result.parent_dimension()) * i64::from(multiplicity);
                }

                for (ml, frequency) in &stored_frequencies {
                    match engine_frequencies.iter().find(|(label, _)| label == ml) {
                        Some((_, found)) if *found == u32::from(*frequency) => {}
                        Some((_, found)) => errors.push(format!(
                            "ordinal {} {ml}: engine {found} != stored {frequency}",
                            subgroup.ordinal
                        )),
                        None => errors.push(format!(
                            "ordinal {} {ml}: stored frequency {frequency} but the engine \
                             reports none",
                            subgroup.ordinal
                        )),
                    }
                }
                for (ml, found) in &engine_frequencies {
                    if !stored_frequencies.iter().any(|(label, _)| label == ml) {
                        errors.push(format!(
                            "ordinal {} {ml}: engine reports {found} but the stored table \
                             has no entry",
                            subgroup.ordinal
                        ));
                    }
                }

                // The record's own condensing irrep must contain the trivial
                // representation: that is what makes the subgroup its isotropy
                // subgroup, and the stored table agrees.
                if !engine_frequencies
                    .iter()
                    .any(|(ml, _)| *ml == probe.ml)
                {
                    errors.push(format!(
                        "ordinal {}: condensing irrep {} does not subduce the trivial rep",
                        subgroup.ordinal, probe.ml
                    ));
                }

                let index = point_group_order(sg) / embedding.representatives().len();
                if frobenius_sum != index as i64 {
                    errors.push(format!(
                        "ordinal {}: Frobenius sum {frobenius_sum} != index {index}",
                        subgroup.ordinal
                    ));
                }
                pinned += 1;
            }
        }
    }

    println!(
        "Gamma records {gamma_records} | frozen-subgroup records {frozen_subgroup_records} | \
         pinned {pinned} | ambiguous {ambiguous} | settings outside the search {unresolved_setting} \
         | errors {}",
        errors.len()
    );
    assert!(errors.is_empty(), "{}", errors.join("\n"));
    // 1895 is the historical "Gamma records" figure; it counts records, not
    // verified identities, which is why the plan asks for the scope to be
    // recounted rather than reused.
    assert_eq!(gamma_records, 1895, "Gamma isotropy records in the shipped table");
    assert_eq!(frozen_subgroup_records, 210);
    assert_eq!(pinned, 10, "records pinned by the task-2 oracle fixture");
    assert_eq!(
        ambiguous + unresolved_setting,
        200,
        "records whose setting needs task 9's metadata"
    );
    assert_eq!(ambiguous, 171, "records with several consistent settings");
    assert_eq!(
        unresolved_setting, 29,
        "records whose setting is not a signed permutation (or needs a shift)"
    );
    assert!(pinned + ambiguous + unresolved_setting == frozen_subgroup_records);
}
