//! Permanent regressions for two reviewed subduction defects.
//!
//! * **Fix A** (`Lattice::preserves`): wave vectors transform with the
//!   contragredient action `k -> R^-T k`, not the direct-space `R k`.  The two
//!   differ exactly when `R` is not orthogonal in the basis in which `k` is
//!   written, which is why an orthogonal test alone cannot see the defect.
//!   Centred reciprocal lattices must keep their extinctions.
//! * **Fix B** (`subduce_irrep_with_embedding`): a cached embedding, the
//!   isotropy record handed in with it and the probe must all name one context;
//!   a stale record, a foreign probe and a mismatched embedding are rejected.
//! * **Fix C** (SG 139 `M1-` P1 -> #126): coset representatives must be derived
//!   from the *original* mapped operations modulo the subgroup lattice `L_H`,
//!   not from the parent-lattice-reduced ones.  The I-centring vector
//!   `(1/2,1/2,1/2)` lies in `L_G` but not in `L_H`, so the inversion's child
//!   representative is `(-I | 1/2,1/2,1/2)`; the old reduction collapsed it to
//!   zero and rejected the whole embedding.  This also pins the Bloch phase of
//!   the non-Gamma probes that the repaired embedding unlocks.

use cryspglib::irrep::isotropy::{
    IsotropyDirection, IsotropySubgroup, isotropy_subgroup_for_direction,
};
use cryspglib::irrep::query;
use cryspglib::irrep::subduce_irrep;
use cryspglib::irrep::subduce_irrep_with_embedding;
use cryspglib::irrep::subduction::{
    Lattice, Mat3R, Rat, SubductionError, SubgroupEmbedding, Vec3R, strict_sg_hall_ops,
};
use cryspglib::irrep::types::{IrrepRecord, KVector};

fn rat(num: i128, den: i128) -> Rat {
    Rat::new(num, den).expect("a rational with a non-zero denominator")
}

fn subgroup(sg: u8, ml: &str, direction: &str) -> IsotropySubgroup {
    isotropy_subgroup_for_direction(sg, ml, IsotropyDirection::Label(direction))
        .unwrap_or_else(|error| panic!("SG {sg} {ml} {direction}: {error}"))
}

/// A scalar record of the parent's own table, exactly as the API hands it out.
fn probe(sg: u8, ml: &str) -> &'static IrrepRecord {
    query::irreps_of(sg)
        .iter()
        .find(|record| record.ml == ml && !record.spinor)
        .unwrap_or_else(|| panic!("SG {sg} has no scalar irrep {ml}"))
}

// ── Fix A: the reciprocal action of a direct-space rotation ──────────────────

#[test]
fn sg143_c3_fixes_k_through_the_reciprocal_action() {
    // The hexagonal C3 of SG 143 in direct fractional coordinates.  It is not
    // orthogonal (`a1 . a2 = -1`), so `R k` and `R^-T k` are different vectors.
    let rotation = [[0, -1, 0], [1, -1, 0], [0, 0, 1]];
    assert!(
        strict_sg_hall_ops(143)
            .expect("SG 143 Hall operations")
            .operations
            .iter()
            .any(|operation| operation.rotation() == rotation),
        "the witness rotation must be a real SG 143 operation"
    );

    let k = Vec3R::new([rat(1, 3), rat(1, 3), Rat::ZERO]);
    let integer = Lattice::integer();

    // The contragredient image leaves k by the reciprocal lattice vector
    // (-1,0,0): K is fixed by C3, as the hexagonal K point must be.
    let reciprocal_action = Mat3R::from_ints(rotation)
        .inverse()
        .expect("C3 is invertible")
        .transpose();
    let image = reciprocal_action.checked_mul_vector(&k).expect("multiply");
    assert_eq!(
        image.checked_sub(&k).expect("subtract"),
        Vec3R::from_ints([-1, 0, 0])
    );
    assert!(
        integer.preserves(rotation, &k).expect("preserves"),
        "SG 143 C3 must fix K = (1/3,1/3,0) modulo the reciprocal lattice"
    );

    // The direct-space product is what the old implementation evaluated, and
    // its difference is not a reciprocal lattice vector.
    let direct = Mat3R::from_ints(rotation)
        .checked_mul_vector(&k)
        .expect("multiply");
    assert!(
        !integer
            .contains(&direct.checked_sub(&k).expect("subtract"))
            .expect("contains"),
        "R k must not be mistaken for the wave-vector action"
    );
}

#[test]
fn a_centred_reciprocal_lattice_keeps_its_extinctions() {
    // A C-centred direct lattice in primitive rows: its reciprocal lattice is
    // generated by (1,1,0), (-1,1,0), (0,0,1), i.e. the `h + k` even rule of
    // the conventional cell.  Reducing per coordinate would lose it.
    let direct = Lattice::new(Mat3R::new([
        [rat(1, 2), rat(1, 2), Rat::ZERO],
        [rat(-1, 2), rat(1, 2), Rat::ZERO],
        [Rat::ZERO, Rat::ZERO, Rat::ONE],
    ]))
    .expect("C-centred direct lattice");
    let reciprocal = direct.reciprocal().expect("reciprocal lattice");
    assert!(
        reciprocal
            .contains(&Vec3R::from_ints([1, 1, 0]))
            .expect("contains")
    );
    assert!(
        !reciprocal
            .contains(&Vec3R::from_ints([1, 0, 0]))
            .expect("contains")
    );

    // A mirror of the lattice sends k = (-1/2,0,0) to (1/2,0,0).  The
    // difference (1,0,0) is a primitive reciprocal lattice vector but has
    // `h + k` odd, so the C-centring extinction rejects it: the two k points
    // are genuinely different modulo L*.  A per-coordinate (Z^3) test would
    // wrongly call this k point fixed.
    let rotation = [[-1, 0, 0], [0, 1, 0], [0, 0, 1]];
    let k = Vec3R::new([rat(-1, 2), Rat::ZERO, Rat::ZERO]);
    assert!(
        !reciprocal.preserves(rotation, &k).expect("preserves"),
        "the centred reciprocal lattice must keep the h + k even extinction"
    );
    assert!(
        Lattice::integer()
            .preserves(rotation, &k)
            .expect("preserves"),
        "the primitive lattice has no such extinction, so this separates the two"
    );
}

// ── Fix B: one context per cached embedding ──────────────────────────────────

#[test]
fn cached_embedding_rejects_a_different_direction_context() {
    // SG 221 GM4+ condenses along P1 into #83 (ordinal 12400) and along P2 into
    // #12 (ordinal 12401).  The P1 embedding folded in the P2 context would
    // silently produce #83's decomposition for a #12 request.
    let p1 = subgroup(221, "GM4+", "P1");
    let p2 = subgroup(221, "GM4+", "P2");
    assert_eq!((p1.ordinal, p1.record.sg), (12400, 83));
    assert_eq!((p2.ordinal, p2.record.sg), (12401, 12));
    let embedding = SubgroupEmbedding::from_isotropy_subgroup(&p1).expect("P1 embedding");

    let error = subduce_irrep_with_embedding(&p2, &embedding, probe(221, "GM3+"))
        .expect_err("the P2 request must not be folded in the P1 embedding");
    assert!(
        matches!(
            error,
            SubductionError::EmbeddingContextMismatch {
                parent_sg: 221,
                ordinal: 12401,
                subgroup_sg: 12,
                embedding_parent_sg: 221,
                embedding_ordinal: 12400,
                embedding_subgroup_sg: 83,
            }
        ),
        "{error:?}"
    );

    // The same guard fires in the other direction: P1 with the P3 embedding.
    let p3 = subgroup(221, "GM4+", "P3");
    let embedding_p3 = SubgroupEmbedding::from_isotropy_subgroup(&p3).expect("P3 embedding");
    let error = subduce_irrep_with_embedding(&p1, &embedding_p3, probe(221, "GM3+"))
        .expect_err("the P1 request must not be folded in the P3 embedding");
    assert!(
        matches!(
            error,
            SubductionError::EmbeddingContextMismatch {
                ordinal: 12400,
                embedding_subgroup_sg: 148,
                ..
            }
        ),
        "{error:?}"
    );
}

#[test]
fn a_foreign_probe_is_rejected_by_identity_not_by_label() {
    let context = subgroup(221, "GM4+", "P1");
    let embedding = SubgroupEmbedding::from_isotropy_subgroup(&context).expect("P1 embedding");
    assert!(subduce_irrep_with_embedding(&context, &embedding, probe(221, "GM3+")).is_ok());

    // Same label, different space group: the record is a different object and
    // its characters live in another group's operator order.
    let foreign = probe(83, "GM1+");
    assert_eq!(foreign.ml, "GM1+");
    let error = subduce_irrep_with_embedding(&context, &embedding, foreign)
        .expect_err("a record of SG 83 is not a probe of SG 221");
    assert!(
        matches!(
            error,
            SubductionError::ForeignProbe {
                sg: 221,
                ml: "GM1+"
            }
        ),
        "{error:?}"
    );

    // A copy of the parent's own record is a different object as well, even
    // though every field and label matches: identity is the table position.
    let copy: &'static IrrepRecord = Box::leak(Box::new(*probe(221, "GM3+")));
    let error = subduce_irrep_with_embedding(&context, &embedding, copy)
        .expect_err("a copied record is not the table's record");
    assert!(
        matches!(error, SubductionError::ForeignProbe { sg: 221, .. }),
        "{error:?}"
    );
}

#[test]
fn an_invalid_condensing_context_is_rejected_when_building_the_embedding() {
    let context = subgroup(221, "GM4+", "P1");
    let mut wrong_k = context;
    wrong_k.k = KVector::new([1, 1, 1], 2);
    assert!(matches!(
        SubgroupEmbedding::from_isotropy_subgroup(&wrong_k),
        Err(SubductionError::StaleIsotropyRecord { ordinal: 12400 })
    ));

    let spinor = query::irreps_of(221)
        .iter()
        .find(|record| record.spinor)
        .unwrap();
    let mut wrong_irrep = context;
    wrong_irrep.irrep_ml = spinor.ml;
    wrong_irrep.k = spinor.k_vector();
    // Reject before calling the scalar-only subgroups() accessor, which panics
    // when handed a spinor record.
    assert!(matches!(
        SubgroupEmbedding::from_isotropy_subgroup(&wrong_irrep),
        Err(SubductionError::StaleIsotropyRecord { ordinal: 12400 })
    ));
}

#[test]
fn stale_or_fabricated_subgroup_context_is_rejected() {
    let context = subgroup(221, "GM4+", "P1");
    let embedding = SubgroupEmbedding::from_isotropy_subgroup(&context).expect("P1 embedding");
    let gamma = probe(221, "GM3+");
    // The baseline must stay accepted, otherwise the negative cases below prove
    // nothing about the guard.
    assert!(subduce_irrep_with_embedding(&context, &embedding, gamma).is_ok());

    // One mutated record field with an unchanged ordinal: an ordinal-only guard
    // would accept this, the record is rechecked against the generated table.
    let mut tampered_record = context;
    tampered_record.record.origin = [1, 0, 0, 1];
    let error = subduce_irrep_with_embedding(&tampered_record, &embedding, gamma)
        .expect_err("a mutated record must be rejected");
    assert!(
        matches!(
            error,
            SubductionError::StaleIsotropyRecord { ordinal: 12400 }
        ),
        "{error:?}"
    );

    // A moved ordinal that does land on another stored record.
    let mut moved = context;
    moved.ordinal = 12401;
    let error = subduce_irrep_with_embedding(&moved, &embedding, gamma)
        .expect_err("a shifted ordinal must be rejected");
    assert!(
        matches!(
            error,
            SubductionError::StaleIsotropyRecord { ordinal: 12401 }
        ),
        "{error:?}"
    );

    // The same record claimed for a different parent irrep is a different
    // context (here GM3+ does not list the GM4+ record).
    let mut wrong_irrep = context;
    wrong_irrep.irrep_ml = "GM3+";
    let error = subduce_irrep_with_embedding(&wrong_irrep, &embedding, gamma)
        .expect_err("a record must belong to the named parent irrep");
    assert!(
        matches!(
            error,
            SubductionError::StaleIsotropyRecord { ordinal: 12400 }
        ),
        "{error:?}"
    );

    // A wrong k for the named irrep.
    let mut wrong_k = context;
    wrong_k.k = KVector::new([1, 1, 1], 2);
    let error = subduce_irrep_with_embedding(&wrong_k, &embedding, gamma)
        .expect_err("the condensing k must match the named irrep");
    assert!(
        matches!(
            error,
            SubductionError::StaleIsotropyRecord { ordinal: 12400 }
        ),
        "{error:?}"
    );

    // A parent that does not own the embedding at all.
    let global = subgroup(225, "GM4-", "C1");
    let global_embedding =
        SubgroupEmbedding::from_isotropy_subgroup(&global).expect("SG 225 embedding");
    let error = subduce_irrep_with_embedding(&context, &global_embedding, gamma)
        .expect_err("another parent's embedding must be rejected");
    assert!(
        matches!(
            error,
            SubductionError::EmbeddingContextMismatch {
                parent_sg: 221,
                ordinal: 12400,
                embedding_parent_sg: 225,
                ..
            }
        ),
        "{error:?}"
    );
}

// ── Fix C: child-lattice representatives and the SG 139 probes ───────────────

/// The inversion of the SG 139 `M1-` P1 -> #126 embedding must keep its child
/// lattice translation.
#[test]
fn sg139_inversion_keeps_the_child_lattice_translation() {
    let context = subgroup(139, "M1-", "P1");
    assert_eq!(context.record.sg, 126);
    let embedding = SubgroupEmbedding::from_isotropy_subgroup(&context).expect("SG 139 embedding");
    assert_eq!(embedding.subgroup_sg(), 126);
    // The isotropy record uses the other ITA origin choice of #126, so the
    // frozen (1/4,1/4,1/4) shift is part of this embedding.
    assert_eq!(
        *embedding.child_shift(),
        Vec3R::new([rat(1, 4); 3]),
        "the frozen #126 child-frame origin shift"
    );

    let inversion = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]];
    let half = Vec3R::new([rat(1, 2); 3]);
    let mut child_representatives = Vec::new();
    for operation in embedding.representatives() {
        if operation.rotation() == inversion {
            child_representatives.push(
                *operation
                    .reduce(embedding.subgroup_lattice())
                    .expect("reduce modulo L_H")
                    .translation(),
            );
        }
    }
    // -I occurs once in the point group; the 16 representatives are the full
    // coset set, one per point operation.
    assert_eq!(child_representatives.len(), 1);
    assert_eq!(embedding.representatives().len(), 16);
    assert!(
        child_representatives.contains(&half),
        "the inversion's L_H representative must be (1/2,1/2,1/2), found {child_representatives:?}"
    );

    // The parent-lattice view is what `operations()` exposes and what parent
    // membership uses; there the same inversion genuinely reduces to zero
    // because (1/2,1/2,1/2) is an I-centring vector of SG 139.  Keeping both
    // views is the point of the fix.
    let parent_inversions = embedding
        .operations()
        .iter()
        .filter(|operation| operation.rotation() == inversion)
        .collect::<Vec<_>>();
    assert_eq!(parent_inversions.len(), 1);
    assert!(
        parent_inversions
            .iter()
            .all(|operation| operation.translation().is_zero())
    );
}

/// The non-Gamma probes the repaired SG 139 embedding unlocks, pinned by value.
#[test]
fn sg139_non_gamma_probes_decompose_to_expected_child_irreps() {
    let context = subgroup(139, "M1-", "P1");
    let embedding = SubgroupEmbedding::from_isotropy_subgroup(&context).expect("SG 139 embedding");
    let probe_of = |ml: &str| probe(139, ml);

    // M1- is the condensing irrep: it contains the child's trivial rep GM1+.
    // M1+ subduces to GM1- while the Gamma identity GM1+ subduces to itself:
    // the pairing follows the Bloch phase and the child origin, not the label.
    for (ml, expected) in [
        ("M1-", "GM1+"),
        ("M1+", "GM1-"),
        ("M2+", "GM2-"),
        ("M2-", "GM2+"),
        ("GM1+", "GM1+"),
        ("GM1-", "GM1-"),
    ] {
        let result = subduce_irrep_with_embedding(&context, &embedding, probe_of(ml))
            .unwrap_or_else(|error| panic!("{ml}: {error}"));
        let targets: Vec<(&str, u32)> = result
            .targets()
            .iter()
            .map(|target| (target.ml, target.multiplicity))
            .collect();
        assert_eq!(targets, [(expected, 1)], "{ml} targets");
        assert_eq!(u32::from(result.parent_dimension()), 1);
        let dimension_sum: u32 = result
            .targets()
            .iter()
            .map(|target| u32::from(target.dimension) * target.multiplicity)
            .sum();
        assert_eq!(dimension_sum, 1, "{ml} dimension sum");
        // Every reconstructed character must match the parent's, operation by
        // operation: a lost or wrong child translation cannot pass this.
        let (parent, rebuilt) = result.reconstruction();
        assert!(!parent.is_empty(), "{ml} has no active operations");
        for (index, (expected, found)) in parent.iter().zip(rebuilt).enumerate() {
            assert!(
                (expected - found).norm() <= result.tolerance(),
                "{ml} operation {index}: {found} != {expected}"
            );
        }
    }
}

#[test]
fn a_valid_embedding_is_still_reusable_across_probes() {
    // The cache exists for exactly this: one embedding, many probes, same
    // answer as rebuilding it each time.
    let context = subgroup(221, "GM4+", "P1");
    let embedding = SubgroupEmbedding::from_isotropy_subgroup(&context).expect("P1 embedding");

    let gamma = probe(221, "GM3+");
    let cached = subduce_irrep_with_embedding(&context, &embedding, gamma).expect("cached reuse");
    let rebuilt = subduce_irrep(&context, "GM3+").expect("rebuilt");
    assert_eq!(cached.targets(), rebuilt.targets());
    assert_eq!(cached.ordinal(), 12400);
    assert_eq!(cached.subgroup_sg(), 83);

    let trivial = probe(221, "GM1+");
    let cached_trivial =
        subduce_irrep_with_embedding(&context, &embedding, trivial).expect("second reuse");
    let rebuilt_trivial = subduce_irrep(&context, "GM1+").expect("rebuilt trivial");
    assert_eq!(cached_trivial.targets(), rebuilt_trivial.targets());
    assert_eq!(cached_trivial.multiplicity("GM1+"), 1);

    // A non-Gamma probe of the same parent is the same context too: R1+ folds
    // to (1/2,-1/2,1/2) and decomposes into A1+.
    let non_gamma = probe(221, "R1+");
    let folded =
        subduce_irrep_with_embedding(&context, &embedding, non_gamma).expect("non-Gamma reuse");
    assert_eq!(
        folded.folded_k().as_slice(),
        [rat(1, 2), rat(-1, 2), rat(1, 2)]
    );
    assert_eq!(
        folded
            .targets()
            .iter()
            .map(|target| (target.ml, target.multiplicity))
            .collect::<Vec<_>>(),
        [("A1+", 1)]
    );
}
