//! Anchors for the frozen little-group character tables of the parametric-k
//! irreps behind `other_wave_vector_subduction`.
//!
//! The tables are generated by `scripts/freeze_w_little_characters.py` from the
//! pinned ISOTROPY archive: the Gamma irreps' compatibility rows for a k line
//! (`GM4: DT1 DT2 DT2`) give one exact rational equation per point operation,
//! and solving them jointly recovers the line irreps' characters.  That route
//! fixes 65 of the 73 sources; SG 202/203/209/210 `DT3`/`DT4` only ever appear
//! as the sum `DT3 + DT4`, so the generator closes them with the little
//! cogroup's source ordering (`cogroup_pair_route`).
//!
//! This test does not recompute the tables (that needs the shipped `iso`
//! binary).  It pins the values the gate produced, the structure every table
//! must have, the cogroup pairing of the cubic `DT` lines, and -- independently
//! of the Gamma route -- the SG 202 tables against the archived CIR characters
//! of the compatible X-point irreps, which is the cross-check that makes the
//! eight cogroup-derived sources falsifiable inside this crate.

use cryspglib::irrep::query;
use cryspglib::irrep::w_little_characters_data::{
    LittleCharacterTable, W_LITTLE_CHARACTERS, W_LITTLE_CHARACTERS_UNRESOLVED,
};

fn table_of(space_group: u8, label: &str) -> &'static LittleCharacterTable {
    W_LITTLE_CHARACTERS
        .iter()
        .find(|table| table.space_group == space_group && table.label == label)
        .unwrap_or_else(|| panic!("SG {space_group} {label} is not in the frozen table"))
}

/// Characters of one table, in the order the generator stored them, as exact
/// `(real, imaginary)` integer parts.
fn characters(table: &LittleCharacterTable) -> Vec<[i32; 2]> {
    table.operations.iter().map(|op| op.character).collect()
}

/// The real characters of a table, for the sources that have no imaginary part.
fn real_characters(table: &LittleCharacterTable) -> Vec<i32> {
    table
        .operations
        .iter()
        .map(|op| {
            assert_eq!(op.character[1], 0, "SG {} {}", table.space_group, table.label);
            op.character[0]
        })
        .collect()
}

/// Rotation part of a frozen operation, row major, as the record stores it.
fn flat_rotation(operation: &cryspglib::irrep::w_little_characters_data::LittleOperation) -> [i32; 9] {
    let mut flat = [0i32; 9];
    for row in 0..3 {
        for column in 0..3 {
            flat[3 * row + column] = i32::from(operation.rotation[row][column]);
        }
    }
    flat
}

#[test]
fn frozen_tables_cover_every_source() {
    assert_eq!(
        W_LITTLE_CHARACTERS.len(),
        73,
        "every parametric-k source now has a character table"
    );
    assert!(
        W_LITTLE_CHARACTERS_UNRESOLVED.is_empty(),
        "no source may stay open: {:?}",
        W_LITTLE_CHARACTERS_UNRESOLVED
    );
    let mut seen = std::collections::HashSet::new();
    for table in W_LITTLE_CHARACTERS {
        assert!(
            seen.insert((table.space_group, table.label)),
            "duplicate table SG {} {}",
            table.space_group,
            table.label
        );
    }
}

#[test]
fn every_table_starts_at_the_identity_with_its_own_dimension() {
    for table in W_LITTLE_CHARACTERS {
        let identity = table.operations[0];
        assert_eq!(
            identity.element, "x,y,z",
            "SG {} {} does not start at the identity",
            table.space_group, table.label
        );
        assert_eq!(identity.rotation, [[1, 0, 0], [0, 1, 0], [0, 0, 1]]);
        assert_eq!(
            identity.character,
            [i32::from(table.dimension), 0],
            "SG {} {}: identity character is the little dimension",
            table.space_group,
            table.label
        );
        for op in table.operations {
            let [real, imaginary] = op.character;
            assert!(
                real * real + imaginary * imaginary
                    <= i32::from(table.dimension) * i32::from(table.dimension),
                "SG {} {}: character {op:?} exceeds the dimension {}",
                table.space_group,
                table.label,
                table.dimension
            );
        }
    }
}

#[test]
fn sg196_dt_and_sm_characters_are_pinned() {
    // `GM1: DT1`, `GM2GM3: DT1`, `GM4: DT1 DT2 DT2` with chi_GM4(C2y) = -1 for
    // SG 196 force these values: the DT little group is {E, C2y}.
    let dt1 = table_of(196, "DT1");
    assert_eq!(dt1.dimension, 1);
    assert_eq!(dt1.k_label, "DT");
    assert_eq!(dt1.direction, ["0", "2", "0"]);
    assert_eq!(real_characters(dt1), vec![1, 1]);

    let dt2 = table_of(196, "DT2");
    assert_eq!(real_characters(dt2), vec![1, -1]);

    // The SM line has a trivial little group: `SM1` is the trivial character.
    let sm1 = table_of(196, "SM1");
    assert_eq!(sm1.dimension, 1);
    assert_eq!(sm1.k_label, "SM");
    assert_eq!(real_characters(sm1), vec![1]);

    // The two DT little irreps are distinct: one is odd on the two-fold.
    assert_ne!(real_characters(dt1), real_characters(dt2));
}

#[test]
fn cubic_parents_carry_their_expected_label_sets() {
    for (space_group, expected) in [
        (196u8, vec!["DT1", "DT2", "SM1"]),
        (225, vec!["DT1", "DT2", "DT3", "DT4", "DT5", "SM1", "SM2", "SM3", "SM4"]),
        (227, vec!["DT1", "DT2", "DT3", "DT4", "DT5", "SM1", "SM2", "SM3", "SM4"]),
        (202, vec!["DT1", "DT2", "DT3", "DT4", "SM1", "SM2"]),
        (203, vec!["DT1", "DT2", "DT3", "DT4", "SM1", "SM2"]),
        (209, vec!["DT1", "DT2", "DT3", "DT4", "SM1", "SM2"]),
        (210, vec!["DT1", "DT2", "DT3", "DT4", "SM1", "SM2"]),
    ] {
        let mut labels: Vec<&str> = W_LITTLE_CHARACTERS
            .iter()
            .filter(|table| table.space_group == space_group)
            .map(|table| table.label)
            .collect();
        labels.sort_unstable();
        let mut wanted = expected.clone();
        wanted.sort_unstable();
        assert_eq!(labels, wanted, "SG {space_group} label set");
    }
}

/// The cubic `DT` line has the little cogroup `C2v = {E, C2, m1, m2}` for the
/// parents with a mirror class and `C4 = {E, C2, R, R^3}` for the two whose
/// little group carries a four-fold rotation instead.  The four
/// one-dimensional line irreps are pinned as the standard table: `DT1`, `DT2`
/// are the first two rows, which the Gamma compatibility data fixes by itself,
/// and the `DT3`/`DT4` pair is what the little-cogroup route completes (the two
/// remaining sign characters, or the conjugate pair for `C4`).
#[test]
fn the_cubic_dt_pair_is_the_standard_cogroup_pairing() {
    fn square(rotation: [i32; 9]) -> [i32; 9] {
        let mut product = [0i32; 9];
        for row in 0..3 {
            for column in 0..3 {
                for inner in 0..3 {
                    product[3 * row + column] +=
                        rotation[3 * row + inner] * rotation[3 * inner + column];
                }
            }
        }
        product
    }
    fn multiply(left: [i32; 9], right: [i32; 9]) -> [i32; 9] {
        let mut product = [0i32; 9];
        for row in 0..3 {
            for column in 0..3 {
                for inner in 0..3 {
                    product[3 * row + column] +=
                        left[3 * row + inner] * right[3 * inner + column];
                }
            }
        }
        product
    }
    const ONE: [i32; 9] = [1, 0, 0, 0, 1, 0, 0, 0, 1];

    for space_group in [202u8, 203, 209, 210] {
        let dt1 = table_of(space_group, "DT1");
        let dt2 = table_of(space_group, "DT2");
        let dt3 = table_of(space_group, "DT3");
        let dt4 = table_of(space_group, "DT4");
        for table in [dt1, dt2, dt3, dt4] {
            assert_eq!(table.dimension, 1, "SG {space_group} {}", table.label);
            assert_eq!(table.k_label, "DT");
            assert_eq!(table.direction, ["0", "2", "0"]);
            assert_eq!(table.operations.len(), 4, "SG {space_group} {}", table.label);
            let rotations: Vec<[i32; 9]> = table.operations.iter().map(flat_rotation).collect();
            assert_eq!(rotations[0], ONE, "SG {space_group} {}", table.label);
            // One-dimensional characters of an abelian cogroup of order four:
            // three non-identity operations, closed under the product rule of
            // either C2v (three involutions) or C4 (one generator of order 4).
            assert_eq!(square(rotations[1]), ONE, "SG {space_group} {}", table.label);
            let c2v = square(rotations[2]) == ONE
                && square(rotations[3]) == ONE
                && multiply(rotations[2], rotations[3]) == rotations[1];
            let c4 = square(rotations[2]) == rotations[1]
                && square(rotations[3]) == rotations[1]
                && multiply(rotations[2], rotations[3]) == ONE;
            assert!(
                c2v || c4,
                "SG {space_group} {}: the cogroup is neither C2v nor C4",
                table.label
            );
        }
        assert_eq!(real_characters(dt1), vec![1, 1, 1, 1], "SG {space_group} DT1");
        assert_eq!(real_characters(dt2), vec![1, 1, -1, -1], "SG {space_group} DT2");
        // `C2v`: all three non-identity operations are involutions.  `C4`: only
        // the two-fold square is, the other two generate the order-four class.
        let involutions = (1..4)
            .filter(|index| square(flat_rotation(&dt3.operations[*index])) == ONE)
            .count();
        assert!(
            involutions == 3 || involutions == 1,
            "SG {space_group}: {involutions} involutions in the cogroup"
        );
        let expected = if involutions == 3 {
            (
                vec![[1, 0], [-1, 0], [1, 0], [-1, 0]],
                vec![[1, 0], [-1, 0], [-1, 0], [1, 0]],
            )
        } else {
            (
                vec![[1, 0], [-1, 0], [0, 1], [0, -1]],
                vec![[1, 0], [-1, 0], [0, -1], [0, 1]],
            )
        };
        // SG 209 is the one parent whose conjugate pair the round-41 ordering
        // convention got backwards; the engine's block route pins it (its X
        // compatibility rows pair DT3 with DT4, so nothing else could).
        let expected = if space_group == 209 {
            (expected.1, expected.0)
        } else {
            expected
        };
        assert_eq!(characters(dt3), expected.0, "SG {space_group} DT3");
        assert_eq!(characters(dt4), expected.1, "SG {space_group} DT4");
        // The pair is exactly what the Gamma rows determine: the sum carries
        // the whole `C2` entry and cancels on the two remaining operations.
        let sum: Vec<[i32; 2]> = characters(dt3)
            .iter()
            .zip(characters(dt4))
            .map(|(left, right)| [left[0] + right[0], left[1] + right[1]])
            .collect();
        assert_eq!(sum, vec![[2, 0], [-2, 0], [0, 0], [0, 0]], "SG {space_group} DT3 + DT4");
    }
}

/// The compatibility rows the generator reads also say which X-point irrep
/// restricts to which line irrep (`X3+: DT3`, `X2+: DT4`, ...).  The archived CIR
/// characters of those X-point irreps are a second, independent source for the
/// same tables: dividing out the Bloch phase of the X point must reproduce the
/// frozen characters operation by operation.
#[test]
fn archived_cir_characters_confirm_the_sg202_dt_pairing() {
    const PAIRS: &[(&str, &str)] = &[
        ("X1+", "DT1"),
        ("X4-", "DT1"),
        ("X4+", "DT2"),
        ("X1-", "DT2"),
        ("X3+", "DT3"),
        ("X2-", "DT3"),
        ("X2+", "DT4"),
        ("X3-", "DT4"),
    ];
    let mut checked = 0;
    for (point_label, line_label) in PAIRS {
        let table = table_of(202, line_label);
        let mut expected = std::collections::HashMap::new();
        for op in table.operations {
            expected.insert(flat_rotation(op), op.character);
        }
        assert!(
            expected.values().all(|character| character[1] == 0),
            "SG 202 {line_label}: the SG 202 tables are real"
        );
        let record = query::irreps_of(202)
            .iter()
            .find(|record| record.ml == *point_label && record.k_vector().numerators == [0, 1, 0])
            .unwrap_or_else(|| panic!("SG 202 {point_label} at the X point is missing"));
        let trace = record
            .ordinary_scalar_selected_arm_block_trace()
            .unwrap_or_else(|error| panic!("SG 202 {point_label}: {error:?}"));
        let k = record.k_vector();
        let mut seen: std::collections::HashMap<[i32; 9], i32> = std::collections::HashMap::new();
        for index in 0..trace.len() {
            let Some((value, operation)) = trace.entry(index) else {
                continue;
            };
            // Only the operations that fix the line direction belong to the
            // line's little group; the rest are other star arms.
            if operation.rotation[1] != 0 || operation.rotation[4] != 1 || operation.rotation[7] != 0
            {
                continue;
            }
            let mut phase = 0.0f64;
            for axis in 0..3 {
                phase += (k.numerators[axis] as f64) / (k.denominator as f64)
                    * operation.translation[axis];
            }
            let phase = std::f64::consts::TAU * phase;
            let character = value * num_complex::Complex64::from_polar(1.0, phase);
            assert!(
                character.im.abs() < 1e-8,
                "SG 202 {point_label}: character {character:?} is not real"
            );
            let rounded = character.re.round();
            assert!(
                (character.re - rounded).abs() < 1e-8 && rounded.abs() == 1.0,
                "SG 202 {point_label}: character {character:?} is not a sign"
            );
            let rotation = operation.rotation;
            if let Some(previous) = seen.insert(rotation, rounded as i32) {
                assert_eq!(
                    previous, rounded as i32,
                    "SG 202 {point_label}: lifts of {rotation:?} disagree"
                );
            }
        }
        assert_eq!(
            seen.len(),
            4,
            "SG 202 {point_label}: {} little-group rotations, expected 4",
            seen.len()
        );
        for (rotation, character) in &seen {
            assert_eq!(
                expected.get(rotation),
                Some(&[*character, 0]),
                "SG 202 {point_label} vs {line_label}: character at {rotation:?}"
            );
        }
        checked += 1;
    }
    assert_eq!(checked, PAIRS.len());
}
