//! Anchors for the frozen little-group character tables of the parametric-k
//! irreps behind `other_wave_vector_subduction`.
//!
//! The tables are generated by `scripts/freeze_w_little_characters.py` from the
//! pinned ISOTROPY archive: the Gamma irreps' compatibility rows for a k line
//! (`GM4: DT1 DT2 DT2`) give one exact rational equation per point operation,
//! and solving them jointly recovers the line irreps' characters.  This test
//! does not recompute them (that needs the shipped `iso` binary); it pins the
//! values the gate produced, the structure every table must have, and the set
//! of sources that are deliberately absent.

use cryspglib::irrep::w_little_characters_data::{
    LittleCharacterTable, W_LITTLE_CHARACTERS, W_LITTLE_CHARACTERS_UNRESOLVED,
};

fn table_of(space_group: u8, label: &str) -> &'static LittleCharacterTable {
    W_LITTLE_CHARACTERS
        .iter()
        .find(|table| table.space_group == space_group && table.label == label)
        .unwrap_or_else(|| panic!("SG {space_group} {label} is not in the frozen table"))
}

/// Characters of one table, in the order the generator stored them.
fn characters(table: &LittleCharacterTable) -> Vec<i32> {
    table.operations.iter().map(|op| op.character).collect()
}

#[test]
fn frozen_tables_have_the_expected_size_and_unresolved_set() {
    assert_eq!(W_LITTLE_CHARACTERS.len(), 65, "65 of the 73 sources solve");
    assert_eq!(
        W_LITTLE_CHARACTERS_UNRESOLVED.len(),
        8,
        "SG 202/203/209/210 DT3/DT4 stay open"
    );
    for (space_group, label) in W_LITTLE_CHARACTERS_UNRESOLVED {
        assert!(
            !W_LITTLE_CHARACTERS
                .iter()
                .any(|table| table.space_group == *space_group && table.label == *label),
            "SG {space_group} {label} must not appear as a solved table"
        );
    }
    let mut seen = std::collections::HashSet::new();
    for table in W_LITTLE_CHARACTERS {
        assert!(
            seen.insert((table.space_group, table.label)),
            "duplicate table SG {} {}",
            table.space_group,
            table.label
        );
    }
}

#[test]
fn every_table_starts_at_the_identity_with_its_own_dimension() {
    for table in W_LITTLE_CHARACTERS {
        let identity = table.operations[0];
        assert_eq!(
            identity.element, "x,y,z",
            "SG {} {} does not start at the identity",
            table.space_group, table.label
        );
        assert_eq!(identity.rotation, [[1, 0, 0], [0, 1, 0], [0, 0, 1]]);
        assert_eq!(
            identity.character,
            i32::from(table.dimension),
            "SG {} {}: identity character is the little dimension",
            table.space_group,
            table.label
        );
        for op in table.operations {
            assert!(
                op.character.abs() <= i32::from(table.dimension),
                "SG {} {}: character {} exceeds the dimension {}",
                table.space_group,
                table.label,
                op.character,
                table.dimension
            );
        }
    }
}

#[test]
fn sg196_dt_and_sm_characters_are_pinned() {
    // `GM1: DT1`, `GM2GM3: DT1`, `GM4: DT1 DT2 DT2` with chi_GM4(C2y) = -1 for
    // SG 196 force these values: the DT little group is {E, C2y}.
    let dt1 = table_of(196, "DT1");
    assert_eq!(dt1.dimension, 1);
    assert_eq!(dt1.k_label, "DT");
    assert_eq!(dt1.direction, ["0", "2", "0"]);
    assert_eq!(characters(dt1), vec![1, 1]);

    let dt2 = table_of(196, "DT2");
    assert_eq!(characters(dt2), vec![1, -1]);

    // The SM line has a trivial little group: `SM1` is the trivial character.
    let sm1 = table_of(196, "SM1");
    assert_eq!(sm1.dimension, 1);
    assert_eq!(sm1.k_label, "SM");
    assert_eq!(characters(sm1), vec![1]);

    // The two DT little irreps are distinct: one is odd on the two-fold.
    assert_ne!(characters(dt1), characters(dt2));
}

#[test]
fn cubic_parents_carry_their_expected_label_sets() {
    for (space_group, expected) in [
        (196u8, vec!["DT1", "DT2", "SM1"]),
        (225, vec!["DT1", "DT2", "DT3", "DT4", "DT5", "SM1", "SM2", "SM3", "SM4"]),
        (227, vec!["DT1", "DT2", "DT3", "DT4", "DT5", "SM1", "SM2", "SM3", "SM4"]),
    ] {
        let mut labels: Vec<&str> = W_LITTLE_CHARACTERS
            .iter()
            .filter(|table| table.space_group == space_group)
            .map(|table| table.label)
            .collect();
        labels.sort_unstable();
        let mut wanted = expected.clone();
        wanted.sort_unstable();
        assert_eq!(labels, wanted, "SG {space_group} label set");
    }
    // SG 202/203/209/210 keep only the sources the Gamma rows determine.
    for space_group in [202u8, 203, 209, 210] {
        let mut labels: Vec<&str> = W_LITTLE_CHARACTERS
            .iter()
            .filter(|table| table.space_group == space_group)
            .map(|table| table.label)
            .collect();
        labels.sort_unstable();
        assert_eq!(labels, vec!["DT1", "DT2", "SM1", "SM2"], "SG {space_group}");
    }
}
