//! Exact parameter-domain census for the frozen parametric-k line sources.
//!
//! A frozen source lives on the line `k(t) = t . v`.  Its **frozen** little
//! character table is the little group of the *direction*, i.e. the group of the
//! generic point: the operations `R` with `R^-T v = v` modulo the parent
//! reciprocal lattice.  At isolated rational parameters additional operations
//! fix `k(t)` as well, the little group is strictly larger there, and the frozen
//! table describes an induced value rather than the actual line irrep (the
//! engine labels those parameters `ParameterKind::Formal`, see
//! [`super::decompose::LineSubduction::parameter_kind`]).
//!
//! This module answers **where** those parameters are, exactly, instead of
//! sampling denominators: for one operation `R` the condition is
//! `R^-T k(t) - k(t) = t . w_R  in  L*_parent` with `w_R = R^-T v - v`, and the
//! solution set of `t . w  in  L*` is a subgroup of `Q`, so it is generated by
//! one exact rational step.  The exceptional parameters in `[0, 1)` are the
//! residues of that step, a finite set per operation.
//!
//! Everything here is exact `i128` rational arithmetic on the twelfth grid the
//! rest of the subduction layer uses; no floating point and no grid search whose
//! cost grows with a denominator.  The derivation of the step:
//!
//! 1. `t . w in Z^3` holds exactly for `t in c Z`, where `c` is the least
//!    common multiple of the rationals `q_i / p_i` taken over the nonzero
//!    components `w_i = p_i / q_i` in lowest terms (a component with `w_i = 0`
//!    constrains nothing).
//! 2. Writing `t = c j` and `u = c w in Z^3`, the centring conditions of `L*`
//!    are congruences on `j`: the set of valid `j` is `n Z` with `n | e`, where
//!    `e` is the exponent of `L*` over `Z^3` (`e = 1` for P, `2` for A/B/C/I/F,
//!    `3` for R).  `n` is found by scanning `j = 1 ..= 6`, so the scan bound is a
//!    property of the centring type, not of the cocycle.
//! 3. The step is `c n` and the exceptional parameters are its residues
//!    `j (c n) mod 1` for `j = 0 .. denominator(c n) - 1`.
//!
//! The step is returned together with an internal consistency check: every
//! scanned hit above the minimum must be a multiple of it (otherwise the set
//! would not be a subgroup and this module reports
//! [`SubductionError::DomainCensusInconsistent`] rather than a wrong domain).
//!
//! Scope: the frozen corpus (73 sources, cubic parent point groups) plus any
//! direction whose operations are read in the parent's conventional reciprocal
//! frame, which is the frame of the frozen `direction` field.  The child-side
//! census below is the same computation after folding `v` through the embedding,
//! so it covers the folded little co-group of every isotropy record of a source.

use crate::irrep::line_monodromy::line_direction;
use crate::irrep::w_little_characters_data::LittleCharacterTable;

use super::{
    Lattice, Mat3I, Mat3R, Rat, SubductionError, SubgroupEmbedding, Vec3R, exact_primitive_basis,
    fold_wave_vector, strict_sg_hall_ops,
};

/// Scan bound for the congruence on `j`; it only has to cover the possible
/// exponents of a reciprocal lattice over `Z^3` (1 for P, 2 for A/B/C/I/F,
/// 3 for R), so it is a constant of the centring classification.
const CENTRING_SCAN: i128 = 6;

/// One parameter at which the little group of `k(t)` is strictly larger than the
/// frozen one.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExceptionalParameter {
    /// The exact parameter in `[0, 1)`.
    pub parameter: Rat,
    /// Order of the little co-group at this parameter (number of distinct parent
    /// rotations that fix `k(t)` modulo the parent reciprocal lattice).
    pub order: usize,
    /// `order - generic_order`: how many operations join the frozen little
    /// group here.
    pub added: usize,
}

/// The parameter domain of one frozen line source, before any child is chosen.
#[derive(Debug, Clone)]
pub struct ParentDomain {
    /// Parent space group number.
    pub parent_sg: u8,
    /// Frozen source label, e.g. `DT1`.
    pub label: &'static str,
    /// Frozen direction in the parent's conventional reciprocal basis.
    pub direction: Vec3R,
    /// Order of the little co-group of the direction: the generic stabiliser.
    pub generic_order: usize,
    /// Number of distinct rotations in the parent's point group.
    pub parent_rotations: usize,
    /// Exceptional parameters in `[0, 1)`, ascending.  `t = 0` is always one of
    /// them (every rotation fixes `k = 0`).
    pub exceptional: Vec<ExceptionalParameter>,
}

impl ParentDomain {
    /// Whether `t` is an exceptional parameter of this source.
    ///
    /// The parameter is reduced modulo one first: `k(t + 1) = k(t) + v` with
    /// `v` a parent reciprocal lattice vector, so the little group is periodic in
    /// `t` with period one.
    pub fn is_exceptional(&self, parameter: &Rat) -> bool {
        let reduced = reduce_modulo_one(*parameter);
        self.exceptional
            .iter()
            .any(|entry| entry.parameter == reduced)
    }
}

/// The representative of a rational in `[0, 1)`.
fn reduce_modulo_one(value: Rat) -> Rat {
    let denominator = value.denominator();
    let numerator = value.numerator().rem_euclid(denominator);
    Rat::new(numerator, denominator).unwrap_or(Rat::ZERO)
}

/// The parent's reciprocal lattice in the frame the frozen `direction` lives in
/// (the conventional reciprocal basis).
pub fn parent_reciprocal(parent_sg: u8) -> Result<Lattice, SubductionError> {
    Lattice::new(exact_primitive_basis(parent_sg)?)?.reciprocal()
}

/// Exact scaling of a rational vector.
fn scale(vector: &Vec3R, factor: &Rat) -> Result<Vec3R, SubductionError> {
    let mut values = [Rat::ZERO; 3];
    for (axis, value) in values.iter_mut().enumerate() {
        *value = factor.checked_mul(vector.get(axis))?;
    }
    Ok(Vec3R::new(values))
}

fn gcd(left: i128, right: i128) -> i128 {
    let (mut a, mut b) = (left.abs(), right.abs());
    while b != 0 {
        let next = a % b;
        a = b;
        b = next;
    }
    a
}

fn lcm(left: i128, right: i128) -> Result<i128, SubductionError> {
    if left == 0 || right == 0 {
        return Ok(0);
    }
    let divisor = gcd(left, right);
    let scaled = (left / divisor)
        .checked_mul(right)
        .ok_or(SubductionError::RationalOverflow {
            operation: "parameter-domain lcm",
        })?;
    Ok(scaled.abs())
}

/// The rational step generating `{ t : t . w in lattice }`, or `None` when `w`
/// is zero (the operation fixes every point of the line).
///
/// The returned step `s > 0` generates the solution subgroup, so the parameters
/// in `[0, 1)` are the residues `j s mod 1`, `j = 0 .. denominator - 1`.
pub fn minimal_parameter_step(
    lattice: &Lattice,
    w: &Vec3R,
) -> Result<Option<Rat>, SubductionError> {
    if w.is_zero() {
        return Ok(None);
    }
    // 1. `t . w in Z^3` <=> `t in c Z`, with `c` the lcm of `q_i / p_i` over the
    //    nonzero components `w_i = p_i / q_i` in lowest terms.
    let mut accumulated: Option<Rat> = None;
    for axis in 0..3 {
        let value = w.get(axis);
        if value.is_zero() {
            continue;
        }
        // The generator is taken positive: the solution set is symmetric
        // (`t` and `-t` either both work or both fail), so only its positive
        // generator matters.
        let component = Rat::new(value.denominator().abs(), value.numerator().abs())?;
        accumulated = Some(match accumulated {
            None => component,
            Some(current) => Rat::new(
                lcm(current.numerator(), component.numerator())?,
                gcd(current.denominator(), component.denominator()),
            )?,
        });
    }
    let Some(c) = accumulated else {
        return Ok(None);
    };
    // 2. Centring congruences on `j` for `t = c j`.
    let u = scale(w, &c)?;
    if !u.is_integral() {
        return Err(SubductionError::DomainCensusInconsistent {
            reason: "the integrality step did not clear the denominators",
        });
    }
    let mut n: Option<i128> = None;
    for j in 1..=CENTRING_SCAN {
        let factor = Rat::new(j, 1)?;
        if lattice.contains(&scale(&u, &factor)?)? {
            n = Some(j);
            break;
        }
    }
    let Some(n) = n else {
        return Err(SubductionError::DomainCensusInconsistent {
            reason: "no centring multiple of the integrality step lands in the lattice",
        });
    };
    for j in 1..n {
        let factor = Rat::new(j, 1)?;
        if lattice.contains(&scale(&u, &factor)?)? {
            return Err(SubductionError::DomainCensusInconsistent {
                reason: "the centring scan found a smaller multiple than the minimum",
            });
        }
    }
    let step = c.checked_mul(Rat::new(n, 1)?)?;
    if step.denominator() <= 0 || step.numerator() <= 0 {
        return Err(SubductionError::DomainCensusInconsistent {
            reason: "the parameter step is not positive",
        });
    }
    Ok(Some(step))
}

/// Sort exact rationals by value without floating point.
///
/// `Rat` deliberately does not implement `Ord`, so the parameters are compared
/// through a common denominator: the denominators here are the grid sizes of the
/// census, and an overflow is reported instead of falling back to `f64`.
fn sort_parameters(mut values: Vec<Rat>) -> Result<Vec<Rat>, SubductionError> {
    let mut common: i128 = 1;
    for value in &values {
        common = lcm(common, value.denominator())?;
    }
    let mut keyed: Vec<(i128, Rat)> = Vec::with_capacity(values.len());
    for value in values.drain(..) {
        let scaled = value
            .numerator()
            .checked_mul(common / value.denominator())
            .ok_or(SubductionError::RationalOverflow {
                operation: "parameter-domain ordering",
            })?;
        keyed.push((scaled, value));
    }
    keyed.sort_by_key(|(key, _)| *key);
    Ok(keyed.into_iter().map(|(_, value)| value).collect())
}

/// The residues of a step in `[0, 1)`.
fn residues_of(step: Rat) -> Result<Vec<Rat>, SubductionError> {
    let denominator = step.denominator();
    let mut out = Vec::with_capacity(usize::try_from(denominator).unwrap_or(0));
    for j in 0..denominator {
        let factor = Rat::new(j, 1)?;
        out.push(reduce_modulo_one(step.checked_mul(factor)?));
    }
    Ok(out)
}

/// Result of the brute-force cross-check of one exact enumeration.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GridCheck {
    /// Number of `(rotation, grid parameter)` predicates recomputed.
    pub checks: usize,
    /// Predicates where the direct group computation disagreed with the
    /// enumeration.  A non-zero value disproves the census's arithmetic.
    pub mismatches: usize,
}

/// Recompute `R fixes k(t)` directly from the group on a uniform grid and
/// compare it with the exact enumeration.
///
/// This is the census's independent control: the enumeration derives *where* an
/// operation joins the little group from a solution subgroup of `Q`, while this
/// check asks the lattice predicate itself at every `t = k / denominator`.  The
/// two methods share no code path beyond the lattice membership test, so a
/// disagreement is a real finding.  A coarse grid can miss an exceptional
/// parameter (that only weakens the check), but it can never manufacture a
/// mismatch while the enumeration is correct.
pub fn verify_against_grid(
    lattice: &Lattice,
    direction: &Vec3R,
    rotations: &[Mat3I],
    denominator: i128,
) -> Result<GridCheck, SubductionError> {
    let mut check = GridCheck {
        checks: 0,
        mismatches: 0,
    };
    for rotation in rotations {
        let image = Mat3R::from_ints(*rotation)
            .inverse()?
            .transpose()
            .checked_mul_vector(direction)?;
        let w = image.checked_sub(direction)?;
        let residues = match minimal_parameter_step(lattice, &w)? {
            Some(step) => residues_of(step)?,
            // `w = 0`: the operation fixes every parameter.
            None => Vec::new(),
        };
        for k in 0..denominator {
            let parameter = Rat::new(k, denominator)?;
            let actual = lattice.preserves(*rotation, &scale(direction, &parameter)?)?;
            let predicted = if w.is_zero() {
                true
            } else {
                residues.contains(&parameter)
            };
            check.checks += 1;
            if actual != predicted {
                check.mismatches += 1;
            }
        }
    }
    Ok(check)
}

/// The distinct rotations of one space group's data-Hall operations.
pub fn rotation_set(sg: u8) -> Result<Vec<Mat3I>, SubductionError> {
    let hall = strict_sg_hall_ops(sg)?;
    let mut rotations: Vec<Mat3I> = Vec::new();
    for operation in &hall.operations {
        if !rotations.contains(&operation.rotation()) {
            rotations.push(operation.rotation());
        }
    }
    Ok(rotations)
}

/// The exceptional parameters in `[0, 1)` induced by one direction: the union
/// over the given rotations of the residues of their steps.
///
/// `counts` receives, per parameter, the number of rotations fixing `k(t)`; the
/// caller pairs it with the generic order to get the enhancement size.
pub fn exceptional_parameters(
    lattice: &Lattice,
    direction: &Vec3R,
    rotations: &[Mat3I],
) -> Result<Vec<(Rat, usize)>, SubductionError> {
    let mut parameters: Vec<Rat> = vec![Rat::ZERO];
    for rotation in rotations {
        let image = Mat3R::from_ints(*rotation)
            .inverse()?
            .transpose()
            .checked_mul_vector(direction)?;
        let w = image.checked_sub(direction)?;
        let Some(step) = minimal_parameter_step(lattice, &w)? else {
            continue;
        };
        let denominator = step.denominator();
        for j in 0..denominator {
            let factor = Rat::new(j, 1)?;
            let value = reduce_modulo_one(step.checked_mul(factor)?);
            if !parameters.contains(&value) {
                parameters.push(value);
            }
        }
    }
    parameters = sort_parameters(parameters)?;
    let mut out = Vec::with_capacity(parameters.len());
    for parameter in parameters {
        let mut order = 0usize;
        let mut image = [Rat::ZERO; 3];
        for (axis, value) in image.iter_mut().enumerate() {
            *value = parameter.checked_mul(direction.get(axis))?;
        }
        let k = Vec3R::new(image);
        for rotation in rotations {
            if lattice.preserves(*rotation, &k)? {
                order += 1;
            }
        }
        out.push((parameter, order));
    }
    Ok(out)
}

/// The parameter domain of one frozen source: the generic order plus every
/// exceptional parameter in `[0, 1)`.
///
/// `generic_order` is computed from the parent's own operations, so comparing it
/// with `table.operations.len()` cross-checks the frozen table against the
/// group: the frozen table is the little group of the direction, one operation
/// per distinct rotation.
pub fn parent_domain(table: &LittleCharacterTable) -> Result<ParentDomain, SubductionError> {
    let direction = line_direction(table).ok_or(SubductionError::InvalidFrozenDirection {
        sg: table.space_group,
        label: table.label,
    })?;
    let lattice = parent_reciprocal(table.space_group)?;
    let rotations = rotation_set(table.space_group)?;
    let mut generic_order = 0usize;
    for rotation in &rotations {
        let image = Mat3R::from_ints(*rotation)
            .inverse()?
            .transpose()
            .checked_mul_vector(&direction)?;
        if image == direction {
            generic_order += 1;
        }
    }
    let exceptional = exceptional_parameters(&lattice, &direction, &rotations)?
        .into_iter()
        .map(|(parameter, order)| ExceptionalParameter {
            parameter,
            order,
            added: order.saturating_sub(generic_order),
        })
        .collect();
    Ok(ParentDomain {
        parent_sg: table.space_group,
        label: table.label,
        direction,
        generic_order,
        parent_rotations: rotations.len(),
        exceptional,
    })
}

/// The parameters in `[0, 1)` at which the **folded** wave vector of one
/// isotropy record has a strictly larger little co-group than at a generic
/// parameter.
///
/// The folded wave vector is `q(t) = t . T^T v`, so the same exact computation
/// applies in the child's reciprocal lattice with the child's own rotations.
pub fn child_exceptional_parameters(
    embedding: &SubgroupEmbedding,
    direction: &Vec3R,
) -> Result<Vec<(Rat, usize)>, SubductionError> {
    let folded = fold_wave_vector(embedding.transform(), direction)?;
    if folded.is_zero() {
        // A direction folding to the child Gamma point is fixed by every child
        // rotation at every parameter, so the little co-group never changes and
        // there is no exceptional parameter; the caller sees the full child point
        // group at every `t`.
        return Ok(Vec::new());
    }
    let child_cell = Lattice::new(exact_primitive_basis(embedding.subgroup_sg())?)?;
    let child_reciprocal = child_cell.reciprocal()?;
    let rotations = rotation_set(embedding.subgroup_sg())?;
    exceptional_parameters(&child_reciprocal, &folded, &rotations)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::irrep::w_little_characters_data::W_LITTLE_CHARACTERS;

    fn rational(numerator: i128, denominator: i128) -> Rat {
        Rat::new(numerator, denominator).expect("rational")
    }

    /// The frozen tables *are* the little group of the direction: the order
    /// computed from the parent's own operations must equal the number of frozen
    /// operations, for every one of the 73 sources.
    #[test]
    fn the_frozen_tables_are_the_generic_stabiliser() {
        let mut sources = 0usize;
        for table in W_LITTLE_CHARACTERS {
            let domain = parent_domain(table).expect("domain");
            assert_eq!(
                domain.generic_order,
                table.operations.len(),
                "SG {} {}",
                table.space_group,
                table.label
            );
            sources += 1;
        }
        assert_eq!(sources, 73, "the frozen corpus");
    }

    /// The exact partition of the frozen corpus: every source has exceptional
    /// parameters exactly at `t = 0` and `t = 1/2`.
    ///
    /// `t = 0` is fixed by the whole parent point group; `t = 1/2` by a subgroup
    /// of index three.  Both are *measured* facts of these 73 cubic sources, and
    /// the assertion is what makes a change visible instead of silent.
    #[test]
    fn every_frozen_source_is_exceptional_only_at_zero_and_one_half() {
        let mut seen: Vec<(usize, usize, usize)> = Vec::new();
        for table in W_LITTLE_CHARACTERS {
            let domain = parent_domain(table).expect("domain");
            let parameters: Vec<Rat> = domain
                .exceptional
                .iter()
                .map(|entry| entry.parameter)
                .collect();
            assert_eq!(
                parameters,
                vec![Rat::ZERO, rational(1, 2)],
                "SG {} {}",
                table.space_group,
                table.label
            );
            let at_zero = domain.exceptional[0].order;
            let at_half = domain.exceptional[1].order;
            assert_eq!(at_zero, domain.parent_rotations, "t = 0 is the whole point group");
            assert_eq!(
                at_half * 3,
                domain.parent_rotations,
                "t = 1/2 has index three, SG {} {}",
                table.space_group,
                table.label
            );
            assert_eq!(domain.exceptional[0].added, at_zero - domain.generic_order);
            seen.push((domain.parent_rotations, domain.generic_order, at_half));
        }
        seen.sort_unstable();
        seen.dedup();
        assert_eq!(
            seen,
            vec![(12, 1, 4), (12, 2, 4), (24, 2, 8), (24, 4, 8), (48, 4, 16), (48, 8, 16)],
            "the six parent shapes of the frozen corpus"
        );
    }

    /// The step solver on one witness per centring type.
    #[test]
    fn the_minimal_step_covers_every_centring_type() {
        // P: the reciprocal lattice is Z^3.
        let primitive = parent_reciprocal(221).expect("P lattice");
        assert_eq!(
            minimal_parameter_step(&primitive, &Vec3R::from_ints([1, 1, 0])).unwrap(),
            Some(Rat::new(1, 1).unwrap())
        );
        assert_eq!(
            minimal_parameter_step(&primitive, &Vec3R::from_ints([2, 0, 0])).unwrap(),
            Some(Rat::new(1, 2).unwrap())
        );
        // F: all-same-parity integer vectors.
        let face = parent_reciprocal(225).expect("F lattice");
        assert_eq!(
            minimal_parameter_step(&face, &Vec3R::from_ints([1, 1, 1])).unwrap(),
            Some(Rat::new(1, 1).unwrap())
        );
        assert_eq!(
            minimal_parameter_step(&face, &Vec3R::from_ints([1, 1, 0])).unwrap(),
            Some(Rat::new(2, 1).unwrap())
        );
        // I: even coordinate sum.
        let body = parent_reciprocal(229).expect("I lattice");
        assert_eq!(
            minimal_parameter_step(&body, &Vec3R::from_ints([1, 1, 0])).unwrap(),
            Some(Rat::new(1, 1).unwrap())
        );
        assert_eq!(
            minimal_parameter_step(&body, &Vec3R::from_ints([1, 0, 0])).unwrap(),
            Some(Rat::new(2, 1).unwrap())
        );
        // R: in the conventional hexagonal frame of SG 166 the reciprocal
        // lattice is `{ (h, k, l) : -h + k + l = 0 (mod 3) }` (measured on the
        // small vectors, e.g. `(1, 1, 0)` and `(1, 0, -2)` are in it while
        // `(2, 0, 0)` is not).
        let rhombohedral = parent_reciprocal(166).expect("R lattice");
        assert_eq!(
            minimal_parameter_step(&rhombohedral, &Vec3R::from_ints([1, 1, 1])).unwrap(),
            Some(Rat::new(3, 1).unwrap())
        );
        assert_eq!(
            minimal_parameter_step(&rhombohedral, &Vec3R::from_ints([1, 0, 0])).unwrap(),
            Some(Rat::new(3, 1).unwrap())
        );
        // `(1, 0, 1)` already satisfies the congruence, so no centring multiple
        // is needed.
        assert_eq!(
            minimal_parameter_step(&rhombohedral, &Vec3R::from_ints([1, 0, 1])).unwrap(),
            Some(Rat::new(1, 1).unwrap())
        );
        // `(2, 0, 0)` needs `t . 2` integral first, so the step is `3/2`, not 3.
        assert_eq!(
            minimal_parameter_step(&rhombohedral, &Vec3R::from_ints([2, 0, 0])).unwrap(),
            Some(Rat::new(3, 2).unwrap())
        );
        // A zero vector constrains nothing.
        assert_eq!(
            minimal_parameter_step(&primitive, &Vec3R::zero()).unwrap(),
            None
        );
    }

    /// The child-side partition of one witness: SG 196 `DT1` on `#18` is
    /// enhanced exactly on the quarter grid, which is where the pinned child
    /// rows live.
    #[test]
    fn the_child_partition_of_a_witness_is_the_quarter_grid() {
        use crate::irrep::isotropy;
        use crate::irrep::query;
        use crate::irrep::LabelConvention;

        let table = W_LITTLE_CHARACTERS
            .iter()
            .find(|table| table.space_group == 196 && table.label == "DT1")
            .expect("SG 196 DT1");
        let direction = line_direction(table).expect("direction");
        let mut found = 0usize;
        for record in query::irreps_of(196) {
            if record.spinor || record.subgroups().is_empty() {
                continue;
            }
            let subgroups =
                isotropy::isotropy_subgroups(196, record.ml, LabelConvention::Cdml).expect("iso");
            for subgroup in subgroups {
                if subgroup.record.sg != 18 {
                    continue;
                }
                let embedding =
                    SubgroupEmbedding::from_isotropy_subgroup(&subgroup).expect("embedding");
                let parameters =
                    child_exceptional_parameters(&embedding, &direction).expect("child domain");
                let values: Vec<Rat> = parameters.iter().map(|(value, _)| *value).collect();
                assert_eq!(
                    values,
                    vec![
                        Rat::ZERO,
                        rational(1, 4),
                        rational(1, 2),
                        rational(3, 4)
                    ],
                    "ordinal {}",
                    subgroup.ordinal
                );
                assert!(
                    parameters.iter().all(|(_, order)| *order == 4),
                    "ordinal {}: the folded little co-group has order four everywhere on the \
                     quarter grid",
                    subgroup.ordinal
                );
                found += 1;
            }
        }
        assert!(found > 0, "no SG 196 DT1 record onto #18");
    }

    /// The enumeration and a direct group computation agree on a uniform grid,
    /// for every frozen source.
    #[test]
    fn the_enumeration_agrees_with_the_group_on_a_grid() {
        let mut checks = 0usize;
        for table in W_LITTLE_CHARACTERS {
            let domain = parent_domain(table).expect("domain");
            let lattice = parent_reciprocal(table.space_group).expect("lattice");
            let rotations = rotation_set(table.space_group).expect("rotations");
            for denominator in [24i128, 120] {
                let result =
                    verify_against_grid(&lattice, &domain.direction, &rotations, denominator)
                        .expect("grid check");
                assert_eq!(
                    result.mismatches, 0,
                    "SG {} {} grid 1/{denominator}",
                    table.space_group, table.label
                );
                checks += result.checks;
            }
        }
        assert!(checks > 200_000, "the grid check must be broad: {checks}");
    }
}
