//! Exact parameter-domain census for the frozen parametric-k line sources.
//!
//! A frozen source lives on the line `k(t) = t . v`.  Its **frozen** little
//! character table is the little group of the *direction*, i.e. the group of the
//! generic point: the operations `R` with `R^-T v = v` modulo the parent
//! reciprocal lattice.  At isolated rational parameters additional operations
//! fix `k(t)` as well, the little group is strictly larger there, and the frozen
//! table describes an induced value rather than the actual line irrep (the
//! engine labels those parameters `ParameterKind::Formal`, see
//! [`super::decompose::LineSubduction::parameter_kind`]).
//!
//! This module answers **where** those parameters are, exactly, instead of
//! sampling denominators: for one operation `R` the condition is
//! `R^-T k(t) - k(t) = t . w_R  in  L*_parent` with `w_R = R^-T v - v`, and the
//! solution set of `t . w  in  L*` is a subgroup of `Q`, so it is generated by
//! one exact rational step.  The exceptional parameters in `[0, 1)` are the
//! residues of that step, a finite set per operation.
//!
//! Everything here is exact `i128` rational arithmetic on the twelfth grid the
//! rest of the subduction layer uses; no floating point and no grid search whose
//! cost grows with a denominator.  The derivation of the step:
//!
//! 1. `t . w in Z^3` holds exactly for `t in c Z`, where `c` is the least
//!    common multiple of the rationals `q_i / p_i` taken over the nonzero
//!    components `w_i = p_i / q_i` in lowest terms (a component with `w_i = 0`
//!    constrains nothing).
//! 2. Writing `t = c j` and `u = c w in Z^3`, the centring conditions of `L*`
//!    are congruences on `j`: the set of valid `j` is `n Z` with `n | e`, where
//!    `e` is the exponent of `L*` over `Z^3` (`e = 1` for P, `2` for A/B/C/I/F,
//!    `3` for R).  `n` is found by scanning `j = 1 ..= 6`, so the scan bound is a
//!    property of the centring type, not of the cocycle.
//! 3. The step is `c n` and the exceptional parameters are its residues
//!    `j (c n) mod 1` for `j = 0 .. denominator(c n) - 1`.
//!
//! The step comes with two independent controls.  Internally, every hit of the
//! finite scan must be a multiple of the smallest one, otherwise the solution
//! set would not be a subgroup and the module reports
//! [`SubductionError::DomainCensusInconsistent`] instead of a wrong domain.
//! Externally, [`minimal_parameter_step_via_coordinates`] recomputes the same
//! step through the lattice's own coordinate map, an algorithm that shares no
//! arithmetic with the centring scan; the corpus gate compares the two on every
//! `(source, rotation)` pair.
//!
//! Scope: directions that are **reciprocal lattice vectors** of the group they
//! belong to.  Only then is `k(t + 1) = k(t) + v` the same point of the zone, the
//! little group periodic in `t` with period one, and the residue representation
//! of the domain valid.  The frozen corpus satisfies this for all 73 sources and
//! for all 1,006 folded child directions; anything else is rejected with
//! [`SubductionError::ParameterDomainOutOfScope`] instead of being reported in a
//! representation that silently merges distinct parameters.  The child-side
//! census below is the same computation after folding `v` through the embedding,
//! so it covers the folded little co-group of every isotropy record of a source.
//!
//! # The projective class on a domain
//!
//! Decomposing a line source at a parameter `t` needs the **projective**
//! characters of the child little co-group of the folded point `q(t) = t . q1`:
//! its factor system is
//!
//! ```text
//! omega_t(R, S) = chi_{q(t)}(lambda_RS),  lambda_RS = tau_R + R tau_S - tau_RS,
//! ```
//!
//! with one chosen child operation `(R, tau_R)` per rotation and `lambda_RS` the
//! **unreduced** defect, an element of the child lattice `L` (see
//! `subduction_catalogue`).  Whether the class of `omega_t` in `H^2(P, U(1))` can
//! change inside a domain decides whether one representative parameter per domain
//! is enough, so it is the question this section settles.
//!
//! Let `P = { R : R^{-T} q1 = q1 }`, the **exact** stabiliser of the direction,
//! i.e. the rotations with `w_R = R^{-T} q1 - q1 = 0`.  On a domain of the census
//! the little co-group of `q(t)` is exactly `P`: a rotation with `w_R != 0`
//! satisfies `t . w_R in L*` only at the isolated parameters the census lists, so
//! it enters the little co-group, if at all, at an exceptional parameter and never
//! inside a domain.  For `R in P` the defect identity
//! `lambda_RS + lambda_{R S,T} = R lambda_{S,T} + lambda_{R,ST}` together with
//! `(R^T - I) q1 = 0` gives
//!
//! ```text
//! omega_s(R,S) omega_s(RS,T) = omega_s(S,T) omega_s(R,ST)   for every real s,
//! ```
//!
//! so `s -> omega_s` is a family of factor systems on `P`, and `s -> [omega_s]` is
//! a homomorphism from the divisible group `(R, +)` into the finite group
//! `H^2(P, U(1))`; a homomorphism from a divisible group to a finite group is
//! trivial.  Hence:
//!
//! **Theorem.**  On every domain of the census the factor system of the folded
//! direction has **trivial** class in `H^2(P, U(1))`, for every real parameter and
//! not only for the probed ones.  The class is therefore constant on each domain —
//! it is the identity there.  The only parameter dependence left in the
//! decomposition is the **gauge**: the target catalogue is the ordinary irreps of
//! `P` twisted by a gauge solving a linear system with continuous coefficients,
//! and the multiplicities are integer-valued continuous functions of `t`, hence
//! constant on the interval.  A non-coboundary family can therefore be reachable
//! only at an exceptional parameter, where the little co-group is strictly larger
//! and this argument does not apply; those parameters are finitely many and the
//! census probes them exactly.
//!
//! Both premises are checked on the corpus.  Parent side: all 341 operations of
//! the 73 frozen little groups fix their direction exactly
//! (`every_frozen_little_group_fixes_its_whole_direction`, which also asserts
//! `parent_domain`'s `generic_order` counts the same set).  Child side: the census
//! gate counts, for every record and label, the rotations with `w_R = 0` and
//! compares the count with the child order at the generic sample.
//!
//! The first formulation of that child-side check used membership `w_R in L*`
//! instead of exact fixity and was wrong: the constraint `t . w_R in L*` then
//! holds at every parameter (so the rotation *is* in the little co-group
//! everywhere) while `chi_{s q1} . lambda` is a factor system only at the isolated
//! `s` with `s w_R in L*`.  Measured witness: `w = (0, 4, 0)` with step `1/4`,
//! which produced 24,430 gate violations before the check was corrected.

use crate::irrep::line_monodromy::line_direction;
use crate::irrep::w_little_characters_data::LittleCharacterTable;

use super::{
    Lattice, Mat3I, Mat3R, Rat, SubductionError, SubgroupEmbedding, Vec3R, exact_primitive_basis,
    fold_wave_vector, strict_sg_hall_ops,
};

/// Scan bound for the congruence on `j`; it only has to cover the possible
/// exponents of a reciprocal lattice over `Z^3` (1 for P, 2 for A/B/C/I/F,
/// 3 for R), so it is a constant of the centring classification.
const CENTRING_SCAN: i128 = 6;

/// One parameter at which the little group of `k(t)` is strictly larger than the
/// frozen one.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExceptionalParameter {
    /// The exact parameter in `[0, 1)`.
    pub parameter: Rat,
    /// Order of the little co-group at this parameter (number of distinct parent
    /// rotations that fix `k(t)` modulo the parent reciprocal lattice).
    pub order: usize,
    /// `order - generic_order`: how many operations join the frozen little
    /// group here.
    pub added: usize,
}

/// The parameter domain of one frozen line source, before any child is chosen.
#[derive(Debug, Clone)]
pub struct ParentDomain {
    /// Parent space group number.
    pub parent_sg: u8,
    /// Frozen source label, e.g. `DT1`.
    pub label: &'static str,
    /// Frozen direction in the parent's conventional reciprocal basis.
    pub direction: Vec3R,
    /// Order of the little co-group of the direction: the generic stabiliser.
    pub generic_order: usize,
    /// Number of distinct rotations in the parent's point group.
    pub parent_rotations: usize,
    /// Exceptional parameters in `[0, 1)`, ascending.  `t = 0` is always one of
    /// them (every rotation fixes `k = 0`).
    pub exceptional: Vec<ExceptionalParameter>,
}

impl ParentDomain {
    /// Whether `t` is an exceptional parameter of this source.
    ///
    /// The parameter is reduced modulo one first: `k(t + 1) = k(t) + v` with
    /// `v` a parent reciprocal lattice vector, so the little group is periodic in
    /// `t` with period one.
    pub fn is_exceptional(&self, parameter: &Rat) -> bool {
        let reduced = reduce_modulo_one(*parameter);
        self.exceptional
            .iter()
            .any(|entry| entry.parameter == reduced)
    }
}

/// The representative of a rational in `[0, 1)`.
fn reduce_modulo_one(value: Rat) -> Rat {
    let denominator = value.denominator();
    let numerator = value.numerator().rem_euclid(denominator);
    Rat::new(numerator, denominator).unwrap_or(Rat::ZERO)
}

/// The reciprocal lattice of one space group, in the conventional reciprocal
/// frame the frozen `direction` fields live in.
///
/// Fails only for an out-of-range number.  The lattice is the one of the **stored
/// Hall setting** of that space group number ([`exact_primitive_basis`] switches
/// on the centring of `SG_DATA_HALL[sg]`), which is what the frozen directions
/// and the census use; 27 space group numbers have Hall settings with a different
/// centring, so "the reciprocal lattice of SG `n`" is shorthand for that setting.
/// The census uses it on the parent of a line source and on the child a source
/// folds into.
pub fn reciprocal_lattice(sg: u8) -> Result<Lattice, SubductionError> {
    Lattice::new(exact_primitive_basis(sg)?)?.reciprocal()
}

/// Refuse a direction that is not a lattice vector of `lattice`.
///
/// The census represents a domain by the residues of an exact step in `[0, 1)`,
/// which is only the same set of little groups when `k(t + 1) = k(t) + v` with
/// `v` in the reciprocal lattice; see the module documentation.  The frozen
/// corpus passes this for all 73 sources and all 1,006 folded child directions
/// (the census gate re-checks the parent side on every source), so the guard is a
/// scope fence for future sources rather than a live code path.
pub fn require_reciprocal_direction(
    lattice: &Lattice,
    direction: &Vec3R,
    sg: u8,
    label: &'static str,
) -> Result<(), SubductionError> {
    if lattice.contains(direction)? {
        return Ok(());
    }
    Err(SubductionError::ParameterDomainOutOfScope { sg, label })
}

/// Exact scaling of a rational vector.
fn scale(vector: &Vec3R, factor: &Rat) -> Result<Vec3R, SubductionError> {
    let mut values = [Rat::ZERO; 3];
    for (axis, value) in values.iter_mut().enumerate() {
        *value = factor.checked_mul(vector.get(axis))?;
    }
    Ok(Vec3R::new(values))
}

/// `|value|` as a checked operation: `i128::MIN` has no positive counterpart, so
/// the census reports `RationalOverflow` instead of panicking in a debug build.
fn absolute(value: i128) -> Result<i128, SubductionError> {
    value
        .checked_abs()
        .ok_or(SubductionError::RationalOverflow {
            operation: "parameter-domain absolute value",
        })
}

fn gcd(left: i128, right: i128) -> Result<i128, SubductionError> {
    let (mut a, mut b) = (absolute(left)?, absolute(right)?);
    while b != 0 {
        let next = a % b;
        a = b;
        b = next;
    }
    Ok(a)
}

fn lcm(left: i128, right: i128) -> Result<i128, SubductionError> {
    if left == 0 || right == 0 {
        return Ok(0);
    }
    let divisor = gcd(left, right)?;
    let scaled = (left / divisor)
        .checked_mul(right)
        .ok_or(SubductionError::RationalOverflow {
            operation: "parameter-domain lcm",
        })?;
    absolute(scaled)
}

/// The rational step generating `{ t : t . w in lattice }`, or `None` when `w`
/// is zero (the operation fixes every point of the line).
///
/// The returned step `s > 0` generates the solution subgroup.  For `w` **in**
/// `lattice` the parameters in `[0, 1)` are exactly the residues `j s mod 1`,
/// `j = 0 .. denominator - 1`; for `w` outside the lattice the solution set is
/// not periodic in `t`, so those residues are *not* the parameters and the
/// public entry points refuse such a direction (see
/// [`require_reciprocal_direction`]).
///
/// **Precondition:** for `w` different from zero, `lattice` must be contained in
/// `Z^3` in the frame of `w`, and the quotient `Z^3 / lattice` must have exponent
/// at most [`CENTRING_SCAN`].  Both hold for the reciprocal lattice of the stored
/// Hall setting of every space group number (index at most four, exponent at most
/// three; asserted by
/// `every_space_group_reciprocal_lattice_is_integral_with_small_exponent`).  The
/// centring scan integrates first and applies the congruences afterwards, which
/// is only complete under those hypotheses; a lattice with fractional rows would
/// need `Lattice::coordinates` instead.  The first hypothesis is checked for
/// `w != 0` and reported as [`SubductionError::DomainCensusInconsistent`], so a
/// future caller cannot get a silently wrong step.  `w = 0` needs neither: zero is
/// in every lattice, so the answer is `Ok(None)` for any lattice, before the
/// check.  The second hypothesis is sufficient rather than necessary -- the scan
/// errors exactly when the least admissible centring multiple exceeds the bound,
/// which an exponent above [`CENTRING_SCAN`] implies but does not exhaust (a
/// lattice like `diag(4, 3, 1)` still answers many `w` correctly).
pub fn minimal_parameter_step(
    lattice: &Lattice,
    w: &Vec3R,
) -> Result<Option<Rat>, SubductionError> {
    if w.is_zero() {
        return Ok(None);
    }
    // The scan integrates first (`t . w in Z^3`), so it needs a lattice inside
    // the integer lattice; see the precondition in the documentation.
    if !lattice.rows().is_integral() {
        return Err(SubductionError::DomainCensusInconsistent {
            reason: "the centring scan requires a lattice contained in Z^3",
        });
    }
    // 1. `t . w in Z^3` <=> `t in c Z`, with `c` the lcm of `q_i / p_i` over the
    //    nonzero components `w_i = p_i / q_i` in lowest terms.
    let mut accumulated: Option<Rat> = None;
    for axis in 0..3 {
        let value = w.get(axis);
        if value.is_zero() {
            continue;
        }
        // The generator is taken positive: the solution set is symmetric
        // (`t` and `-t` either both work or both fail), so only its positive
        // generator matters.
        let component = Rat::new(absolute(value.denominator())?, absolute(value.numerator())?)?;
        accumulated = Some(match accumulated {
            None => component,
            Some(current) => Rat::new(
                lcm(current.numerator(), component.numerator())?,
                gcd(current.denominator(), component.denominator())?,
            )?,
        });
    }
    let Some(c) = accumulated else {
        return Ok(None);
    };
    // 2. Centring congruences on `j` for `t = c j`.
    let u = scale(w, &c)?;
    if !u.is_integral() {
        return Err(SubductionError::DomainCensusInconsistent {
            reason: "the integrality step did not clear the denominators",
        });
    }
    let mut hits: Vec<i128> = Vec::new();
    for j in 1..=CENTRING_SCAN {
        let factor = Rat::new(j, 1)?;
        if lattice.contains(&scale(&u, &factor)?)? {
            hits.push(j);
        }
    }
    let Some(&n) = hits.first() else {
        return Err(SubductionError::DomainCensusInconsistent {
            reason: "no centring multiple of the integrality step lands in the lattice",
        });
    };
    // The solution set is a subgroup of `Z` here, so every hit of the scan must
    // be a multiple of the smallest one.  A violation disproves the arithmetic
    // behind the scan and is reported rather than smoothed over.
    if hits.iter().any(|hit| *hit % n != 0) {
        return Err(SubductionError::DomainCensusInconsistent {
            reason: "a scanned multiple lands in the lattice without the minimum dividing it",
        });
    }

    let step = c.checked_mul(Rat::new(n, 1)?)?;
    if step.denominator() <= 0 || step.numerator() <= 0 {
        return Err(SubductionError::DomainCensusInconsistent {
            reason: "the parameter step is not positive",
        });
    }
    Ok(Some(step))
}

/// Sort exact rationals by value without floating point.
///
/// `Rat` deliberately does not implement `Ord`, so the parameters are compared
/// through a common denominator: the denominators here are the grid sizes of the
/// census, and an overflow is reported instead of falling back to `f64`.
fn sort_parameters(mut values: Vec<Rat>) -> Result<Vec<Rat>, SubductionError> {
    let mut common: i128 = 1;
    for value in &values {
        common = lcm(common, value.denominator())?;
    }
    let mut keyed: Vec<(i128, Rat)> = Vec::with_capacity(values.len());
    for value in values.drain(..) {
        let scaled = value
            .numerator()
            .checked_mul(common / value.denominator())
            .ok_or(SubductionError::RationalOverflow {
                operation: "parameter-domain ordering",
            })?;
        keyed.push((scaled, value));
    }
    keyed.sort_by_key(|(key, _)| *key);
    Ok(keyed.into_iter().map(|(_, value)| value).collect())
}

/// The residues of a step in `[0, 1)`.
fn residues_of(step: Rat) -> Result<Vec<Rat>, SubductionError> {
    let denominator = step.denominator();
    let mut out = Vec::with_capacity(usize::try_from(denominator).unwrap_or(0));
    for j in 0..denominator {
        let factor = Rat::new(j, 1)?;
        out.push(reduce_modulo_one(step.checked_mul(factor)?));
    }
    Ok(out)
}

/// Result of the brute-force cross-check of one exact enumeration.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GridCheck {
    /// Number of `(rotation, grid parameter)` predicates recomputed.
    pub checks: usize,
    /// Predicates where the direct group computation disagreed with the
    /// enumeration.  A non-zero value disproves the census's arithmetic.
    pub mismatches: usize,
}

/// Recompute `R fixes k(t)` directly from the group on a uniform grid and
/// compare it with the exact enumeration.
///
/// What this check does and does not establish: the *predicate* is recomputed
/// from the group (`Lattice::preserves`, i.e. `contains(R^-T k - k)`) instead of
/// from the residue list, so it validates the geometry of the condition and the
/// residue enumeration.  It shares the step algebra (`minimal_parameter_step`)
/// with the enumeration, so it cannot detect a wrong step; and a grid whose
/// denominator is not a multiple of a step misses that step's parameters
/// entirely, which is why the corpus gate uses denominators that cover the
/// measured grid and why [`minimal_parameter_step_via_coordinates`] exists as a
/// second, arithmetic-independent step.  A coarse grid can only weaken the check;
/// while the enumeration is correct it can never produce a mismatch.
pub fn verify_against_grid(
    lattice: &Lattice,
    direction: &Vec3R,
    rotations: &[Mat3I],
    denominator: i128,
) -> Result<GridCheck, SubductionError> {
    let mut check = GridCheck {
        checks: 0,
        mismatches: 0,
    };
    for rotation in rotations {
        let image = Mat3R::from_ints(*rotation)
            .inverse()?
            .transpose()
            .checked_mul_vector(direction)?;
        let w = image.checked_sub(direction)?;
        let residues = match minimal_parameter_step(lattice, &w)? {
            Some(step) => residues_of(step)?,
            // `w = 0`: the operation fixes every parameter.
            None => Vec::new(),
        };
        for k in 0..denominator {
            let parameter = Rat::new(k, denominator)?;
            let actual = lattice.preserves(*rotation, &scale(direction, &parameter)?)?;
            let predicted = if w.is_zero() {
                true
            } else {
                residues.contains(&parameter)
            };
            check.checks += 1;
            if actual != predicted {
                check.mismatches += 1;
            }
        }
    }
    Ok(check)
}

/// The distinct rotations of one space group's data-Hall operations.
pub fn rotation_set(sg: u8) -> Result<Vec<Mat3I>, SubductionError> {
    let hall = strict_sg_hall_ops(sg)?;
    let mut rotations: Vec<Mat3I> = Vec::new();
    for operation in &hall.operations {
        if !rotations.contains(&operation.rotation()) {
            rotations.push(operation.rotation());
        }
    }
    Ok(rotations)
}

/// The candidate parameters in `[0, 1)` induced by one direction: the union over
/// the given rotations of the residues of their steps, each with the number of
/// rotations fixing `k(t)`.
///
/// **Internal.**  The residue representation is only valid when `direction` is a
/// lattice vector of `lattice`; this function cannot check that (it has no space
/// group for the error text), so the public entry points [`parent_domain`] and
/// [`child_exceptional_parameters`] call [`require_reciprocal_direction`] first
/// and are the only supported way to obtain a domain.
fn exceptional_parameters(
    lattice: &Lattice,
    direction: &Vec3R,
    rotations: &[Mat3I],
) -> Result<Vec<(Rat, usize)>, SubductionError> {
    let mut parameters: Vec<Rat> = vec![Rat::ZERO];
    for rotation in rotations {
        let image = Mat3R::from_ints(*rotation)
            .inverse()?
            .transpose()
            .checked_mul_vector(direction)?;
        let w = image.checked_sub(direction)?;
        let Some(step) = minimal_parameter_step(lattice, &w)? else {
            continue;
        };
        let denominator = step.denominator();
        for j in 0..denominator {
            let factor = Rat::new(j, 1)?;
            let value = reduce_modulo_one(step.checked_mul(factor)?);
            if !parameters.contains(&value) {
                parameters.push(value);
            }
        }
    }
    parameters = sort_parameters(parameters)?;
    let mut out = Vec::with_capacity(parameters.len());
    for parameter in parameters {
        let mut order = 0usize;
        let mut image = [Rat::ZERO; 3];
        for (axis, value) in image.iter_mut().enumerate() {
            *value = parameter.checked_mul(direction.get(axis))?;
        }
        let k = Vec3R::new(image);
        for rotation in rotations {
            if lattice.preserves(*rotation, &k)? {
                order += 1;
            }
        }
        out.push((parameter, order));
    }
    Ok(out)
}

/// The parameter domain of one frozen source: the generic order plus every
/// exceptional parameter in `[0, 1)`.
///
/// `generic_order` is computed from the parent's own operations, so comparing it
/// with `table.operations.len()` cross-checks the frozen table against the
/// group: the frozen table is the little group of the direction, one operation
/// per distinct rotation.
pub fn parent_domain(table: &LittleCharacterTable) -> Result<ParentDomain, SubductionError> {
    let direction = line_direction(table).ok_or(SubductionError::InvalidFrozenDirection {
        sg: table.space_group,
        label: table.label,
    })?;
    let lattice = reciprocal_lattice(table.space_group)?;
    require_reciprocal_direction(&lattice, &direction, table.space_group, table.label)?;
    let rotations = rotation_set(table.space_group)?;
    let mut generic_order = 0usize;
    for rotation in &rotations {
        let image = Mat3R::from_ints(*rotation)
            .inverse()?
            .transpose()
            .checked_mul_vector(&direction)?;
        if image == direction {
            generic_order += 1;
        }
    }
    let exceptional = exceptional_parameters(&lattice, &direction, &rotations)?
        .into_iter()
        .map(|(parameter, order)| ExceptionalParameter {
            parameter,
            order,
            added: order.saturating_sub(generic_order),
        })
        .collect();
    Ok(ParentDomain {
        parent_sg: table.space_group,
        label: table.label,
        direction,
        generic_order,
        parent_rotations: rotations.len(),
        exceptional,
    })
}

/// The **candidate** parameters in `[0, 1)` of one isotropy record's folded
/// wave vector, with the child little co-group order at each.
///
/// The folded wave vector is `q(t) = t . T^T v`, so the same exact computation
/// applies in the child's reciprocal lattice with the child's own rotations.
/// `t = 0` is a solution of *every* operation's condition, so it is always in the
/// returned set (for a child whose point group is trivial it is not an
/// enhancement); use [`little_co_group_order`] to compare the order at any
/// parameter with the generic one.
///
/// The record's frozen direction must fold into a lattice vector of the child's
/// reciprocal lattice, otherwise `t` and `t + 1` are different folded points and
/// the domain is rejected with
/// [`SubductionError::ParameterDomainOutOfScope`].
pub fn child_exceptional_parameters(
    embedding: &SubgroupEmbedding,
    table: &LittleCharacterTable,
) -> Result<Vec<(Rat, usize)>, SubductionError> {
    let direction = line_direction(table).ok_or(SubductionError::InvalidFrozenDirection {
        sg: table.space_group,
        label: table.label,
    })?;
    let folded = fold_wave_vector(embedding.transform(), &direction)?;
    child_candidates(embedding.subgroup_sg(), &folded)
}

/// The candidate parameters of one **folded** direction in the child frame.
///
/// Split out of [`child_exceptional_parameters`] so the degenerate case is
/// testable without fabricating an embedding: `folded = 0` means the line folds
/// onto the child Gamma point, which every child rotation fixes at every
/// parameter, so the little co-group never changes and the candidate set is
/// empty (the caller sees the full child point group throughout).
pub fn child_candidates(
    child_sg: u8,
    folded: &Vec3R,
) -> Result<Vec<(Rat, usize)>, SubductionError> {
    if folded.is_zero() {
        return Ok(Vec::new());
    }
    let child_cell = Lattice::new(exact_primitive_basis(child_sg)?)?;
    let child_reciprocal = child_cell.reciprocal()?;
    require_reciprocal_direction(&child_reciprocal, folded, child_sg, "folded direction")?;
    let rotations = rotation_set(child_sg)?;
    exceptional_parameters(&child_reciprocal, folded, &rotations)
}

/// The order of the little co-group of `k(t) = t . direction` at one exact
/// parameter: how many of `rotations` fix `t . direction` modulo `lattice`.
///
/// This is defined for **every** parameter, including ones the census does not
/// list as candidates, so a caller never has to read an unknown order as zero.
pub fn little_co_group_order(
    lattice: &Lattice,
    direction: &Vec3R,
    rotations: &[Mat3I],
    parameter: Rat,
) -> Result<usize, SubductionError> {
    let k = scale(direction, &parameter)?;
    let mut order = 0usize;
    for rotation in rotations {
        if lattice.preserves(*rotation, &k)? {
            order += 1;
        }
    }
    Ok(order)
}

/// [`minimal_parameter_step`] computed through the lattice's own coordinate map.
///
/// `t . w in L*` is equivalent to `t . (C w) in Z^3` with `C` the lattice
/// coordinate matrix, so the positive generator is the least common multiple of
/// the rationals `q_i / p_i` over the nonzero components of `C w`.  This route
/// uses the lattice basis instead of the membership predicate and the centring
/// scan, so agreement between the two is a real cross-check of the scan (the
/// corpus gate compares them on every `(source, rotation)` pair).
pub fn minimal_parameter_step_via_coordinates(
    lattice: &Lattice,
    w: &Vec3R,
) -> Result<Option<Rat>, SubductionError> {
    if w.is_zero() {
        return Ok(None);
    }
    let coordinates = lattice.coordinates(w)?;
    let mut accumulated: Option<Rat> = None;
    for axis in 0..3 {
        let value = coordinates.get(axis);
        if value.is_zero() {
            continue;
        }
        let component = Rat::new(absolute(value.denominator())?, absolute(value.numerator())?)?;
        accumulated = Some(match accumulated {
            None => component,
            Some(current) => Rat::new(
                lcm(current.numerator(), component.numerator())?,
                gcd(current.denominator(), component.denominator())?,
            )?,
        });
    }
    Ok(accumulated)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::irrep::w_little_characters_data::W_LITTLE_CHARACTERS;

    fn rational(numerator: i128, denominator: i128) -> Rat {
        Rat::new(numerator, denominator).expect("rational")
    }

    /// The frozen tables *are* the little group of the direction: the order
    /// computed from the parent's own operations must equal the number of frozen
    /// operations, for every one of the 73 sources.
    #[test]
    fn the_frozen_tables_are_the_generic_stabiliser() {
        let mut sources = 0usize;
        for table in W_LITTLE_CHARACTERS {
            let domain = parent_domain(table).expect("domain");
            assert_eq!(
                domain.generic_order,
                table.operations.len(),
                "SG {} {}",
                table.space_group,
                table.label
            );
            // The order agreeing is not enough: the *rotation sets* must be the
            // same, otherwise the frozen table would describe a different
            // subgroup of the same size.
            let rotations = rotation_set(table.space_group).expect("rotations");
            let mut generic: Vec<Mat3I> = Vec::new();
            for rotation in &rotations {
                let image = Mat3R::from_ints(*rotation)
                    .inverse()
                    .unwrap()
                    .transpose()
                    .checked_mul_vector(&domain.direction)
                    .unwrap();
                if image == domain.direction {
                    generic.push(*rotation);
                }
            }
            let mut frozen: Vec<Mat3I> = table
                .operations
                .iter()
                .map(|operation| operation.rotation.map(|row| row.map(i32::from)))
                .collect();
            generic.sort_unstable();
            frozen.sort_unstable();
            assert_eq!(
                generic, frozen,
                "SG {} {}: the frozen rotation set is not the generic stabiliser",
                table.space_group, table.label
            );
            sources += 1;
        }
        assert_eq!(sources, 73, "the frozen corpus");
    }

    /// A step of `i128::MIN` numerator cannot be made positive; the census
    /// reports `RationalOverflow` instead of panicking (in a debug build the
    /// lost `abs()` used to abort on negation overflow).
    #[test]
    fn an_extreme_numerator_is_a_typed_error_not_a_panic() {
        let lattice = Lattice::integer();
        let w = Vec3R::new([
            Rat::new(i128::MIN, 1).expect("MIN is a valid numerator"),
            Rat::ZERO,
            Rat::ZERO,
        ]);
        assert!(matches!(
            minimal_parameter_step(&lattice, &w),
            Err(SubductionError::RationalOverflow { .. })
        ));
        assert!(matches!(
            minimal_parameter_step_via_coordinates(&lattice, &w),
            Err(SubductionError::RationalOverflow { .. })
        ));
    }

    /// A folded direction of zero has no candidate parameter: every child
    /// rotation fixes the child Gamma point at every `t`, so the little co-group
    /// never changes.  The branch is unreachable on the frozen corpus and is
    /// covered here directly.
    #[test]
    fn a_zero_folded_direction_has_no_candidate_parameter() {
        for child_sg in [1u8, 2, 18, 123, 221] {
            assert_eq!(
                child_candidates(child_sg, &Vec3R::zero()).expect("candidates"),
                Vec::new(),
                "child #{child_sg}"
            );
        }
    }

    /// The exact partition of the frozen corpus: every source has exceptional
    /// parameters exactly at `t = 0` and `t = 1/2`.
    ///
    /// `t = 0` is fixed by the whole parent point group; `t = 1/2` by a subgroup
    /// of index three.  Both are *measured* facts of these 73 cubic sources, and
    /// the assertion is what makes a change visible instead of silent.
    #[test]
    fn every_frozen_source_is_exceptional_only_at_zero_and_one_half() {
        let mut seen: Vec<(usize, usize, usize)> = Vec::new();
        for table in W_LITTLE_CHARACTERS {
            let domain = parent_domain(table).expect("domain");
            let parameters: Vec<Rat> = domain
                .exceptional
                .iter()
                .map(|entry| entry.parameter)
                .collect();
            assert_eq!(
                parameters,
                vec![Rat::ZERO, rational(1, 2)],
                "SG {} {}",
                table.space_group,
                table.label
            );
            let at_zero = domain.exceptional[0].order;
            let at_half = domain.exceptional[1].order;
            assert_eq!(at_zero, domain.parent_rotations, "t = 0 is the whole point group");
            assert_eq!(
                at_half * 3,
                domain.parent_rotations,
                "t = 1/2 has index three, SG {} {}",
                table.space_group,
                table.label
            );
            assert_eq!(domain.exceptional[0].added, at_zero - domain.generic_order);
            seen.push((domain.parent_rotations, domain.generic_order, at_half));
        }
        seen.sort_unstable();
        seen.dedup();
        assert_eq!(
            seen,
            vec![(12, 1, 4), (12, 2, 4), (24, 2, 8), (24, 4, 8), (48, 4, 16), (48, 8, 16)],
            "the six parent shapes of the frozen corpus"
        );
    }

    /// The centring vectors of one space group: the translation parts of the
    /// pure translations in its stored Hall setting, identity first.
    ///
    /// This reads the group's **own operations**, not the `Centering` table entry
    /// that [`exact_primitive_basis`] switches on, so it is the second route the
    /// per-space-group assertion below compares [`reciprocal_lattice`] with.  The
    /// pure translations of a conventional cell are the centring coset
    /// representatives, so their number is the index of the direct lattice in
    /// `Z^3` and hence also of its dual in `Z^3`.
    fn centring_vectors(sg: u8) -> Vec<Vec3R> {
        let hall = strict_sg_hall_ops(sg).expect("hall operations");
        let mut centring: Vec<Vec3R> = Vec::new();
        for operation in &hall.operations {
            if operation.rotation() != [[1, 0, 0], [0, 1, 0], [0, 0, 1]] {
                continue;
            }
            let translation = *operation.translation();
            if !centring.contains(&translation) {
                centring.push(translation);
            }
        }
        assert!(!centring.is_empty(), "SG {sg}: no pure translation");
        centring
    }

    /// The centring scan's preconditions hold for every space group, not only for
    /// the frozen corpus, and the lattice they are stated for is the one the
    /// group's own operations imply.
    ///
    /// Three exact facts are asserted here instead of being argued in prose.
    /// First, every `L*` is contained in `Z^3` and satisfies the congruence
    /// conditions of the group's **own** pure translations, with the same index as
    /// their number -- containment plus equal index pins the lattice, since both
    /// live in `Z^3`; that is what closes the gap the fifth review round found, in
    /// which a `reciprocal_lattice` corrupted for one space group was invisible to
    /// every control because the census compares it only with itself.  Second, the
    /// quotient `Z^3 / L*` has exponent at most three, so the smallest admissible
    /// centring multiple is never larger than that and the scan bound
    /// ([`CENTRING_SCAN`] = 6) always finds it.  Third, the F-centred groups are
    /// pinned by number, so the claim in the previous sentence is about *those*
    /// lattices and not only about a histogram.
    ///
    /// The **index** is not the quantity the scan bound needs: the F-centred
    /// lattices are the fixed-parity lattice `{h = k = l (mod 2)}` with index four
    /// but exponent two, so an index-based bound of three would be wrong for them.
    #[test]
    fn every_space_group_reciprocal_lattice_is_integral_with_small_exponent() {
        let mut by_index = std::collections::BTreeMap::new();
        let mut by_exponent = std::collections::BTreeMap::new();
        let mut index_four: Vec<u8> = Vec::new();
        for sg in 1..=230u8 {
            let lattice = reciprocal_lattice(sg).expect("reciprocal lattice");
            assert!(
                lattice.rows().is_integral(),
                "SG {sg}: the reciprocal lattice has fractional rows"
            );
            let index = lattice
                .determinant()
                .expect("determinant")
                .to_integer()
                .expect("integer determinant")
                .unsigned_abs();
            assert!(
                (1..=4).contains(&index),
                "SG {sg}: centring index {index} is outside 1..=4"
            );
            *by_index.entry(index).or_insert(0usize) += 1;
            if index == 4 {
                index_four.push(sg);
            }
            // The independent route: the group's own pure translations give the
            // congruences `h . c in Z` that define the dual of its direct lattice.
            let centring = centring_vectors(sg);
            assert_eq!(
                u128::try_from(centring.len()).expect("small count"),
                index,
                "SG {sg}: {} centring vectors but index {index}",
                centring.len()
            );
            for row in 0..3 {
                let generator = Vec3R::new(*lattice.rows().row(row));
                for vector in &centring {
                    let mut product = Rat::ZERO;
                    for axis in 0..3 {
                        let term = generator
                            .get(axis)
                            .checked_mul(vector.get(axis))
                            .expect("product");
                        product = product.checked_add(term).expect("sum");
                    }
                    assert!(
                        product.is_integer(),
                        "SG {sg}: reciprocal row {row} fails the congruence of the centring \
                         vector {vector:?}"
                    );
                }
            }
            // The exponent of `Z^3 / L*`: the smallest `e` with `e Z^3 <= L*`.
            let exponent = (1..=CENTRING_SCAN)
                .find(|candidate| {
                    let step = i32::try_from(*candidate).expect("scan bound fits in i32");
                    (0..3).all(|axis| {
                        let mut unit = [0i32; 3];
                        unit[axis] = step;
                        lattice
                            .contains(&Vec3R::from_ints(unit))
                            .expect("membership")
                    })
                })
                .expect("a centring multiple inside the scan bound");
            // Belt-and-braces: the exact histogram below is the control, this line
            // keeps the scan's margin explicit where it is used.
            assert!(
                exponent <= 3,
                "SG {sg}: the quotient exponent {exponent} exceeds the scan's margin"
            );
            *by_exponent.entry(exponent).or_insert(0usize) += 1;
        }
        assert_eq!(
            by_index,
            std::collections::BTreeMap::from([(1, 149), (2, 58), (3, 7), (4, 16)]),
            "the centring index histogram of the 230 stored settings"
        );
        assert_eq!(
            index_four,
            vec![22, 42, 43, 69, 70, 196, 202, 203, 209, 210, 216, 219, 225, 226, 227, 228],
            "the index-four lattices are exactly the F-centred space groups"
        );
        assert_eq!(
            by_exponent,
            std::collections::BTreeMap::from([(1, 149), (2, 74), (3, 7)]),
            "the exponent is what the scan bound has to cover"
        );
    }

    /// The rotation set of one space group is the one its **stored Hall setting**
    /// prescribes, rebuilt through the crate's independent `SymmetryOps` lookup.
    ///
    /// [`rotation_set`] is the other frame value the census consumes, and the gate
    /// compares it only with itself (`rotation_set(child_sg)` against
    /// `rotation_set(embedding.subgroup_sg())`, after the two space group numbers
    /// are known to agree), so a set corrupted for one space group would be as
    /// invisible as the corrupted lattice of the fifth review round.  This is the
    /// control for it: `strict_sg_hall_ops` reads the stored Hall number through
    /// the subduction loader, `SymmetryOps::from_hall_number` reads the same
    /// number through the crate's own database API.
    #[test]
    fn every_space_group_rotation_set_is_its_stored_hall_settings() {
        for sg in 1..=230u8 {
            let stored = crate::irrep::generated_data::SG_DATA_HALL[usize::from(sg)];
            assert_ne!(stored, 0, "SG {sg}: no stored Hall number");
            let operations = crate::SymmetryOps::from_hall_number(
                crate::HallNumber::try_from(usize::from(stored)).expect("Hall number"),
            )
            .expect("operations");
            let mut expected: Vec<Mat3I> = Vec::new();
            for operation in &operations.operations {
                if !expected.contains(&operation.rotation) {
                    expected.push(operation.rotation);
                }
            }
            let mut actual = rotation_set(sg).expect("rotation set");
            assert_eq!(
                actual.len(),
                expected.len(),
                "SG {sg} (Hall {stored}): rotation-set order"
            );
            actual.sort_unstable();
            expected.sort_unstable();
            assert_eq!(
                actual, expected,
                "SG {sg} (Hall {stored}): rotation set differs from the stored Hall setting"
            );
        }
    }

    /// The A- and C-centred congruence conditions differ, which is what lets the
    /// per-space-group assertion above see a centring swap: an A/C exchange keeps
    /// the index at two, so every index- or order-based control stayed silent on
    /// it (fifth review round).
    #[test]
    fn the_per_space_group_congruences_separate_a_from_c() {
        // SG 38 Amm2 is A-centred: the condition is `k + l` even.
        let a_centred = reciprocal_lattice(38).expect("A-centred lattice");
        assert!(a_centred.contains(&Vec3R::from_ints([0, 1, 1])).unwrap());
        assert!(!a_centred.contains(&Vec3R::from_ints([1, 1, 0])).unwrap());
        // SG 5 C2 is C-centred: the condition is `h + k` even.
        let c_centred = reciprocal_lattice(5).expect("C-centred lattice");
        assert!(c_centred.contains(&Vec3R::from_ints([1, 1, 0])).unwrap());
        assert!(!c_centred.contains(&Vec3R::from_ints([0, 1, 1])).unwrap());
        // Both are index two, so the difference is invisible to the histogram.
        for lattice in [a_centred, c_centred] {
            assert_eq!(
                lattice
                    .determinant()
                    .expect("determinant")
                    .to_integer()
                    .expect("integer"),
                2
            );
        }
    }

    /// The step solver on one witness per centring type.
    #[test]
    fn the_minimal_step_covers_every_centring_type() {
        // P: the reciprocal lattice is Z^3.
        let primitive = reciprocal_lattice(221).expect("P lattice");
        assert_eq!(
            minimal_parameter_step(&primitive, &Vec3R::from_ints([1, 1, 0])).unwrap(),
            Some(Rat::new(1, 1).unwrap())
        );
        assert_eq!(
            minimal_parameter_step(&primitive, &Vec3R::from_ints([2, 0, 0])).unwrap(),
            Some(Rat::new(1, 2).unwrap())
        );
        // F: all-same-parity integer vectors.
        let face = reciprocal_lattice(225).expect("F lattice");
        assert_eq!(
            minimal_parameter_step(&face, &Vec3R::from_ints([1, 1, 1])).unwrap(),
            Some(Rat::new(1, 1).unwrap())
        );
        assert_eq!(
            minimal_parameter_step(&face, &Vec3R::from_ints([1, 1, 0])).unwrap(),
            Some(Rat::new(2, 1).unwrap())
        );
        // I: even coordinate sum.
        let body = reciprocal_lattice(229).expect("I lattice");
        assert_eq!(
            minimal_parameter_step(&body, &Vec3R::from_ints([1, 1, 0])).unwrap(),
            Some(Rat::new(1, 1).unwrap())
        );
        assert_eq!(
            minimal_parameter_step(&body, &Vec3R::from_ints([1, 0, 0])).unwrap(),
            Some(Rat::new(2, 1).unwrap())
        );
        // R: in the conventional hexagonal frame of SG 166 the reciprocal
        // lattice is `{ (h, k, l) : -h + k + l = 0 (mod 3) }` (measured on the
        // small vectors, e.g. `(1, 1, 0)` and `(1, 0, -2)` are in it while
        // `(2, 0, 0)` is not).
        let rhombohedral = reciprocal_lattice(166).expect("R lattice");
        assert_eq!(
            minimal_parameter_step(&rhombohedral, &Vec3R::from_ints([1, 1, 1])).unwrap(),
            Some(Rat::new(3, 1).unwrap())
        );
        assert_eq!(
            minimal_parameter_step(&rhombohedral, &Vec3R::from_ints([1, 0, 0])).unwrap(),
            Some(Rat::new(3, 1).unwrap())
        );
        // `(1, 0, 1)` already satisfies the congruence, so no centring multiple
        // is needed.
        assert_eq!(
            minimal_parameter_step(&rhombohedral, &Vec3R::from_ints([1, 0, 1])).unwrap(),
            Some(Rat::new(1, 1).unwrap())
        );
        // `(2, 0, 0)` needs `t . 2` integral first, so the step is `3/2`, not 3.
        assert_eq!(
            minimal_parameter_step(&rhombohedral, &Vec3R::from_ints([2, 0, 0])).unwrap(),
            Some(Rat::new(3, 2).unwrap())
        );
        // A zero vector constrains nothing.
        assert_eq!(
            minimal_parameter_step(&primitive, &Vec3R::zero()).unwrap(),
            None
        );
    }

    /// The child-side partition of one witness: SG 196 `DT1` on `#18` is
    /// enhanced exactly on the quarter grid, which is where the pinned child
    /// rows live.
    #[test]
    fn the_child_partition_of_a_witness_is_the_quarter_grid() {
        use crate::irrep::isotropy;
        use crate::irrep::query;
        use crate::irrep::LabelConvention;

        let table = W_LITTLE_CHARACTERS
            .iter()
            .find(|table| table.space_group == 196 && table.label == "DT1")
            .expect("SG 196 DT1");
        let mut found = 0usize;
        for record in query::irreps_of(196) {
            if record.spinor || record.subgroups().is_empty() {
                continue;
            }
            let subgroups =
                isotropy::isotropy_subgroups(196, record.ml, LabelConvention::Cdml).expect("iso");
            for subgroup in subgroups {
                if subgroup.record.sg != 18 {
                    continue;
                }
                let embedding =
                    SubgroupEmbedding::from_isotropy_subgroup(&subgroup).expect("embedding");
                let parameters =
                    child_exceptional_parameters(&embedding, table).expect("child domain");
                let values: Vec<Rat> = parameters.iter().map(|(value, _)| *value).collect();
                assert_eq!(
                    values,
                    vec![
                        Rat::ZERO,
                        rational(1, 4),
                        rational(1, 2),
                        rational(3, 4)
                    ],
                    "ordinal {}",
                    subgroup.ordinal
                );
                assert!(
                    parameters.iter().all(|(_, order)| *order == 4),
                    "ordinal {}: the folded little co-group has order four everywhere on the \
                     quarter grid",
                    subgroup.ordinal
                );
                found += 1;
            }
        }
        assert!(found > 0, "no SG 196 DT1 record onto #18");
    }

    /// The step computed by the centring scan equals the step computed through
    /// the lattice's own coordinate map, on every `(source, rotation)` pair and
    /// on synthetic vectors with mixed signs, zeros and large numerators.
    #[test]
    fn the_two_step_algorithms_agree() {
        let mut checked = 0usize;
        for table in W_LITTLE_CHARACTERS {
            let domain = parent_domain(table).expect("domain");
            let lattice = reciprocal_lattice(table.space_group).expect("lattice");
            let rotations = rotation_set(table.space_group).expect("rotations");
            for rotation in &rotations {
                let image = Mat3R::from_ints(*rotation)
                    .inverse()
                    .unwrap()
                    .transpose()
                    .checked_mul_vector(&domain.direction)
                    .unwrap();
                let w = image.checked_sub(&domain.direction).unwrap();
                assert_eq!(
                    minimal_parameter_step(&lattice, &w).unwrap(),
                    minimal_parameter_step_via_coordinates(&lattice, &w).unwrap(),
                    "SG {} {} rotation {rotation:?}",
                    table.space_group,
                    table.label
                );
                checked += 1;
            }
        }
        assert!(checked >= 2_000, "the cross-check must be broad: {checked}");
        // Synthetic vectors over every centring type, including mixed signs and
        // large numerators.  `w = 0` is the only case with no constraint.
        for sg in [221u8, 225, 229, 166, 12, 62] {
            let lattice = reciprocal_lattice(sg).expect("lattice");
            for w in [
                [0, 0, 0],
                [1, 0, 0],
                [-1, 0, 0],
                [2, -3, 0],
                [-4, 6, -8],
                [7, -7, 7],
                [12, 18, -24],
                [1_000_003, -2_000_006, 3_000_009],
            ] {
                let w = Vec3R::from_ints(w);
                assert_eq!(
                    minimal_parameter_step(&lattice, &w).unwrap(),
                    minimal_parameter_step_via_coordinates(&lattice, &w).unwrap(),
                    "SG {sg} w={w:?}"
                );
            }
        }
    }

    /// A lattice with fractional rows cannot use the centring scan: the
    /// precondition is checked, and the coordinate route (which has no such
    /// precondition) gives the correct step for the same input.  Witness from the
    /// fourth review round: `diag(1/2, 1/2, 1/2)` with `w = (1, 0, 0)`.
    ///
    /// The unguarded scan is not merely imprecise here, it is silently wrong:
    /// replaying it on this input returns the step `1` (residues `{0}`), losing the
    /// parameter `t = 1/2` that the membership test itself accepts, and the
    /// module's internal "every hit is a multiple of the minimum" self-check does
    /// not fire because the hits are `1 ..= 6` with minimum one.
    #[test]
    fn a_fractional_lattice_is_rejected_by_the_centring_scan() {
        let half = rational(1, 2);
        let lattice = Lattice::new(Mat3R::new([
            [half, Rat::ZERO, Rat::ZERO],
            [Rat::ZERO, half, Rat::ZERO],
            [Rat::ZERO, Rat::ZERO, half],
        ]))
        .expect("fractional lattice");
        let w = Vec3R::from_ints([1, 0, 0]);
        // The reason string is part of the public diagnostic, so it is pinned
        // rather than matched as "some inconsistency".
        assert!(matches!(
            minimal_parameter_step(&lattice, &w),
            Err(SubductionError::DomainCensusInconsistent {
                reason: "the centring scan requires a lattice contained in Z^3"
            })
        ));
        assert_eq!(
            minimal_parameter_step_via_coordinates(&lattice, &w).expect("coordinate route"),
            Some(rational(1, 2))
        );
        // `w = 0` is answered *before* the precondition check, because zero is in
        // every lattice: both routes agree on `None` even for this lattice.  The
        // ordering is deliberate; moving the check above it would make the two
        // routes disagree here.
        let zero = Vec3R::zero();
        assert_eq!(minimal_parameter_step(&lattice, &zero).expect("zero w"), None);
        assert_eq!(
            minimal_parameter_step_via_coordinates(&lattice, &zero).expect("zero w"),
            None
        );
        // The other witness of the same shape: a component with denominator two
        // makes the true step `1/4`, and the unguarded scan returns `1/2`.
        let doubled = Vec3R::from_ints([2, 0, 0]);
        assert!(matches!(
            minimal_parameter_step(&lattice, &doubled),
            Err(SubductionError::DomainCensusInconsistent { .. })
        ));
        assert_eq!(
            minimal_parameter_step_via_coordinates(&lattice, &doubled).expect("coordinate route"),
            Some(rational(1, 4))
        );
    }

    /// The premise of the domain theorem, on the parent side: every rotation of a
    /// frozen line's little group fixes the **whole** direction, i.e.
    /// `R^{-T} v = v` exactly, so `w_R = 0`.
    ///
    /// Fixity is the right hypothesis, not membership of `w_R` in the reciprocal
    /// lattice: `chi_{s v} . lambda` is a factor system for *every real* `s` only
    /// when `(R^T - I)v = 0`, and that is what makes the projective class of the
    /// frozen line trivial on the whole line rather than only at sampled
    /// parameters.  (A rotation with `w_R` a nonzero lattice vector satisfies the
    /// little-group condition at every parameter as well, but the factor system
    /// `chi_{s v} . lambda` is then a cocycle only at the isolated `s` with
    /// `s w_R in L*`; the census corpus contains no such frozen rotation, which is
    /// what the equality below asserts.)
    #[test]
    fn every_frozen_little_group_fixes_its_whole_direction() {
        let mut checked = 0usize;
        for table in W_LITTLE_CHARACTERS {
            let domain = parent_domain(table).expect("domain");
            assert_eq!(
                domain.generic_order,
                table.operations.len(),
                "SG {} {}: the frozen table is not the exact stabiliser of the direction",
                table.space_group,
                table.label
            );
            for operation in table.operations {
                let rotation: Mat3I = operation.rotation.map(|row| row.map(i32::from));
                let image = Mat3R::from_ints(rotation)
                    .inverse()
                    .expect("inverse")
                    .transpose()
                    .checked_mul_vector(&domain.direction)
                    .expect("rotation image");
                assert_eq!(
                    image, domain.direction,
                    "SG {} {}: the frozen rotation {rotation:?} does not fix the whole direction",
                    table.space_group, table.label
                );
                checked += 1;
            }
        }
        // 341 frozen little-group operations in total; the same sum appears
        // independently in the census as `682 = 2 x sum of generic orders`.
        assert_eq!(checked, 341, "every frozen little-group operation is checked");
    }

    /// A direction outside the group's reciprocal lattice is rejected instead of
    /// being given a residue domain: without `v in L*` the little group is not
    /// periodic in `t`, so `t` and `t + 1` are different points of the zone.
    ///
    /// The frozen corpus never triggers the guard (all 73 directions are
    /// reciprocal lattice vectors), so the fence is tested directly on a lattice
    /// where both outcomes are available: SG 148's R-centred reciprocal lattice
    /// contains `(1, 0, 1)` but not `(1, 0, 0)`.
    #[test]
    fn a_direction_outside_the_reciprocal_lattice_is_out_of_scope() {
        let lattice = reciprocal_lattice(148).expect("lattice");
        assert!(lattice.contains(&Vec3R::from_ints([1, 0, 1])).unwrap());
        assert!(!lattice.contains(&Vec3R::from_ints([1, 0, 0])).unwrap());
        require_reciprocal_direction(&lattice, &Vec3R::from_ints([1, 0, 1]), 148, "T1")
            .expect("in scope");
        assert!(matches!(
            require_reciprocal_direction(&lattice, &Vec3R::from_ints([1, 0, 0]), 148, "T1"),
            Err(SubductionError::ParameterDomainOutOfScope { sg: 148, .. })
        ));
        // Every frozen source is in scope, so the census's own domain is total on
        // the corpus.
        for table in W_LITTLE_CHARACTERS {
            assert!(
                parent_domain(table).is_ok(),
                "SG {} {}",
                table.space_group,
                table.label
            );
        }
    }

    /// The per-parameter order is defined everywhere, including parameters the
    /// census does not list, and matches the generic order off the exceptional
    /// set.
    #[test]
    fn the_little_co_group_order_is_defined_at_every_parameter() {
        let table = W_LITTLE_CHARACTERS
            .iter()
            .find(|table| table.space_group == 196 && table.label == "DT1")
            .expect("SG 196 DT1");
        let domain = parent_domain(table).expect("domain");
        let lattice = reciprocal_lattice(196).expect("lattice");
        let rotations = rotation_set(196).expect("rotations");
        for (parameter, expected) in [
            (Rat::ZERO, domain.parent_rotations),
            (rational(1, 2), 4),
            (rational(1, 4), domain.generic_order),
            (rational(1, 7), domain.generic_order),
            (rational(3, 8), domain.generic_order),
            (rational(-1, 2), 4),
            (rational(3, 2), 4),
        ] {
            assert_eq!(
                little_co_group_order(&lattice, &domain.direction, &rotations, parameter).unwrap(),
                expected,
                "SG 196 DT1 t={parameter}"
            );
        }
    }

    /// The enumeration and a direct group computation agree on a uniform grid,
    /// for every frozen source.
    #[test]
    fn the_enumeration_agrees_with_the_group_on_a_grid() {
        let mut checks = 0usize;
        for table in W_LITTLE_CHARACTERS {
            let domain = parent_domain(table).expect("domain");
            let lattice = reciprocal_lattice(table.space_group).expect("lattice");
            let rotations = rotation_set(table.space_group).expect("rotations");
            for denominator in [24i128, 120] {
                let result =
                    verify_against_grid(&lattice, &domain.direction, &rotations, denominator)
                        .expect("grid check");
                assert_eq!(
                    result.mismatches, 0,
                    "SG {} {} grid 1/{denominator}",
                    table.space_group, table.label
                );
                checks += result.checks;
            }
        }
        assert!(checks > 200_000, "the grid check must be broad: {checks}");
    }
}
