//! Little-group character tables of the parametric-k irreps behind the
//! `other_wave_vector_subduction` rows.
//!
//! `DO NOT EDIT`: regenerate with
//! `python3 scripts/freeze_w_little_characters.py --json <full.json> --rust src/irrep/w_little_characters_data.rs`.
//!
//! Every table is solved from the pinned ISOTROPY archive
//! `isotropy_subgroup/iso.zip`
//! (SHA-256 `568667bfc8027095537d642297b319c872d00016b868143c666f90d5931d9f7b`),
//! official `iso` 9.6.1: the Gamma irreps' compatibility rows for the line
//! (`SHOW COMPATIBILITY`) fix the little irreps' characters through
//! `sum_i n_Gamma mult(Gamma -> i) D_i(R) = chi_Gamma(R)` at k = Gamma, where
//! no Bloch phase enters.  65 of the 73 sources are fixed that way.
//! The remaining eight (SG 202/203/209/210 `DT3`/`DT4`) appear in every Gamma
//! row only through `DT3 + DT4`, which the same rows do determine; the split
//! uses the pinned source ordering of the little cogroup `C2v` (`DT1`, `DT2`
//! come out as `A1`, `A2`, and the ordering check for `B1`, `B2` is verified
//! against those two sources per space group).  `cogroup_pair_route` in
//! `scripts/freeze_w_little_characters.py` documents the gate, and
//! `tests/w_little_characters.rs` cross-checks the resulting tables against
//! the archived CIR characters of the compatible points.  See
//! `docs/isotropy-data-semantics.md` section 4.

/// One little-group operation of a parametric-k irrep.
#[derive(Debug, Clone, Copy)]
pub struct LittleOperation {
    /// International-Tables spelling, e.g. `-x,y,-z`.
    pub element: &'static str,
    /// Rotation part, row major, in the parent's conventional basis.
    pub rotation: [[i8; 3]; 3],
    /// Translation part in the parent's conventional cell, as fractions.
    pub translation: [&'static str; 3],
    /// Character of the little irrep on this operation, as exact
    /// (real, imaginary) integer parts; the cubic `DT3`/`DT4` pair of
    /// SG 209/210 is the conjugate pair with +-i on the order-four
    /// generator, every other source is real.
    pub character: [i32; 2],
}

/// Character table of one little irrep at a parametric k domain.
#[derive(Debug, Clone, Copy)]
pub struct LittleCharacterTable {
    /// Parent space-group number.
    pub space_group: u8,
    /// Compact little-irrep label, e.g. `DT1`.
    pub label: &'static str,
    /// Program label of the k domain, e.g. `DT`.
    pub k_label: &'static str,
    /// Domain direction in the parent's conventional reciprocal basis.
    pub direction: [&'static str; 3],
    /// Dimension of the little irrep (the identity character).
    pub dimension: u8,
    /// Little-group operations and their characters.
    pub operations: &'static [LittleOperation],
}

/// The 73 little irreps behind the parametric-k subduction rows.
pub static W_LITTLE_CHARACTERS: &[LittleCharacterTable] = &[
    LittleCharacterTable {
        space_group: 196,
        label: "DT1",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 196,
        label: "DT2",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 196,
        label: "SM1",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 202,
        label: "DT1",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 202,
        label: "DT2",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 202,
        label: "DT3",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "-x,y,z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 202,
        label: "DT4",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "-x,y,z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 202,
        label: "SM1",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 202,
        label: "SM2",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 203,
        label: "DT1",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x+3/4,y,-z+3/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["3/4", "0", "3/4"], character: [1, 0] },
            LittleOperation { element: "-x,y+1/4,z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "1/4", "1/4"], character: [1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 203,
        label: "DT2",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x+3/4,y,-z+3/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["3/4", "0", "3/4"], character: [1, 0] },
            LittleOperation { element: "-x,y+1/4,z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "1/4", "1/4"], character: [-1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 203,
        label: "DT3",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x+3/4,y,-z+3/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["3/4", "0", "3/4"], character: [-1, 0] },
            LittleOperation { element: "-x,y+1/4,z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "1/4", "1/4"], character: [1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 203,
        label: "DT4",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x+3/4,y,-z+3/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["3/4", "0", "3/4"], character: [-1, 0] },
            LittleOperation { element: "-x,y+1/4,z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "1/4", "1/4"], character: [-1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 203,
        label: "SM1",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 203,
        label: "SM2",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 209,
        label: "DT1",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z,y,x", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "z,y,-x", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 209,
        label: "DT2",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z,y,x", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "z,y,-x", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 209,
        label: "DT3",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "-z,y,x", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [0, 1] },
            LittleOperation { element: "z,y,-x", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [0, -1] },
        ],
    },
    LittleCharacterTable {
        space_group: 209,
        label: "DT4",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "-z,y,x", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [0, -1] },
            LittleOperation { element: "z,y,-x", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [0, 1] },
        ],
    },
    LittleCharacterTable {
        space_group: 209,
        label: "SM1",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y,x,-z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 209,
        label: "SM2",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y,x,-z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 210,
        label: "DT1",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z+1/4,y+1/4,x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["1/4", "1/4", "1/4"], character: [1, 0] },
            LittleOperation { element: "z+1/4,y+1/4,-x+1/4", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/4", "1/4"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 210,
        label: "DT2",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z+1/4,y+1/4,x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["1/4", "1/4", "1/4"], character: [-1, 0] },
            LittleOperation { element: "z+1/4,y+1/4,-x+1/4", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/4", "1/4"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 210,
        label: "DT3",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "-z+1/4,y+1/4,x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["1/4", "1/4", "1/4"], character: [0, 1] },
            LittleOperation { element: "z+1/4,y+1/4,-x+1/4", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/4", "1/4"], character: [0, -1] },
        ],
    },
    LittleCharacterTable {
        space_group: 210,
        label: "DT4",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "-z+1/4,y+1/4,x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["1/4", "1/4", "1/4"], character: [0, -1] },
            LittleOperation { element: "z+1/4,y+1/4,-x+1/4", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/4", "1/4"], character: [0, 1] },
        ],
    },
    LittleCharacterTable {
        space_group: 210,
        label: "SM1",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/4,x+1/4,-z+1/4", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["1/4", "1/4", "1/4"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 210,
        label: "SM2",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/4,x+1/4,-z+1/4", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["1/4", "1/4", "1/4"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 216,
        label: "DT1",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "z,y,x", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z,y,-x", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 216,
        label: "DT2",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "z,y,x", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "-z,y,-x", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 216,
        label: "DT3DT4",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 2,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [2, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-2, 0] },
            LittleOperation { element: "z,y,x", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [0, 0] },
            LittleOperation { element: "-z,y,-x", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [0, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 216,
        label: "SM1",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y,x,z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 216,
        label: "SM2",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y,x,z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 219,
        label: "DT1",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "z+1/2,y+1/2,x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
            LittleOperation { element: "-z+1/2,y+1/2,-x+1/2", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 219,
        label: "DT2",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "z+1/2,y+1/2,x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
            LittleOperation { element: "-z+1/2,y+1/2,-x+1/2", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 219,
        label: "DT3DT4",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 2,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [2, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-2, 0] },
            LittleOperation { element: "z+1/2,y+1/2,x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [0, 0] },
            LittleOperation { element: "-z+1/2,y+1/2,-x+1/2", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [0, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 219,
        label: "SM1",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/2,x+1/2,z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 219,
        label: "SM2",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/2,x+1/2,z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 225,
        label: "DT1",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z,y,x", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "z,y,-x", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "z,y,x", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z,y,-x", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 225,
        label: "DT2",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z,y,x", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "z,y,-x", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "-x,y,z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "z,y,x", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "-z,y,-x", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 225,
        label: "DT3",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z,y,x", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "z,y,-x", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "-x,y,z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "z,y,x", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z,y,-x", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 225,
        label: "DT4",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z,y,x", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "z,y,-x", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "z,y,x", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "-z,y,-x", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 225,
        label: "DT5",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 2,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [2, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-2, 0] },
            LittleOperation { element: "-z,y,x", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [0, 0] },
            LittleOperation { element: "z,y,-x", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [0, 0] },
            LittleOperation { element: "-x,y,z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [0, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [0, 0] },
            LittleOperation { element: "z,y,x", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [0, 0] },
            LittleOperation { element: "-z,y,-x", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["0", "0", "0"], character: [0, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 225,
        label: "SM1",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y,x,-z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y,x,z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 225,
        label: "SM2",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y,x,-z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y,x,z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 225,
        label: "SM3",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y,x,-z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "y,x,z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 225,
        label: "SM4",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y,x,-z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "y,x,z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 226,
        label: "DT1",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z+1/2,y+1/2,x+1/2", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
            LittleOperation { element: "z+1/2,y+1/2,-x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
            LittleOperation { element: "-x,y,z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "z+1/2,y+1/2,x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
            LittleOperation { element: "-z+1/2,y+1/2,-x+1/2", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 226,
        label: "DT2",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z+1/2,y+1/2,x+1/2", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
            LittleOperation { element: "z+1/2,y+1/2,-x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
            LittleOperation { element: "-x,y,z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "z+1/2,y+1/2,x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
            LittleOperation { element: "-z+1/2,y+1/2,-x+1/2", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 226,
        label: "DT3",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z+1/2,y+1/2,x+1/2", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
            LittleOperation { element: "z+1/2,y+1/2,-x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
            LittleOperation { element: "-x,y,z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "z+1/2,y+1/2,x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
            LittleOperation { element: "-z+1/2,y+1/2,-x+1/2", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 226,
        label: "DT4",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z+1/2,y+1/2,x+1/2", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
            LittleOperation { element: "z+1/2,y+1/2,-x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
            LittleOperation { element: "-x,y,z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "z+1/2,y+1/2,x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
            LittleOperation { element: "-z+1/2,y+1/2,-x+1/2", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 226,
        label: "DT5",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 2,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [2, 0] },
            LittleOperation { element: "-x,y,-z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-2, 0] },
            LittleOperation { element: "-z+1/2,y+1/2,x+1/2", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [0, 0] },
            LittleOperation { element: "z+1/2,y+1/2,-x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [0, 0] },
            LittleOperation { element: "-x,y,z", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [0, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [0, 0] },
            LittleOperation { element: "z+1/2,y+1/2,x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [0, 0] },
            LittleOperation { element: "-z+1/2,y+1/2,-x+1/2", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [0, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 226,
        label: "SM1",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/2,x+1/2,-z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/2,x+1/2,z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 226,
        label: "SM2",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/2,x+1/2,-z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/2,x+1/2,z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 226,
        label: "SM3",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/2,x+1/2,-z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "y+1/2,x+1/2,z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 226,
        label: "SM4",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/2,x+1/2,-z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
            LittleOperation { element: "x,y,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "y+1/2,x+1/2,z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 227,
        label: "DT1",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x+1/4,y,-z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "0", "1/4"], character: [1, 0] },
            LittleOperation { element: "-z,y+1/4,x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["0", "1/4", "1/4"], character: [1, 0] },
            LittleOperation { element: "z+1/4,y+1/4,-x", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/4", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y+1/4,z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "1/4", "1/4"], character: [1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [1, 0] },
            LittleOperation { element: "z,y,x", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z+1/4,y,-x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "0", "1/4"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 227,
        label: "DT2",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x+1/4,y,-z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "0", "1/4"], character: [1, 0] },
            LittleOperation { element: "-z,y+1/4,x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["0", "1/4", "1/4"], character: [-1, 0] },
            LittleOperation { element: "z+1/4,y+1/4,-x", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/4", "0"], character: [-1, 0] },
            LittleOperation { element: "-x,y+1/4,z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "1/4", "1/4"], character: [1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [1, 0] },
            LittleOperation { element: "z,y,x", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "-z+1/4,y,-x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "0", "1/4"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 227,
        label: "DT3",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x+1/4,y,-z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "0", "1/4"], character: [1, 0] },
            LittleOperation { element: "-z,y+1/4,x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["0", "1/4", "1/4"], character: [-1, 0] },
            LittleOperation { element: "z+1/4,y+1/4,-x", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/4", "0"], character: [-1, 0] },
            LittleOperation { element: "-x,y+1/4,z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "1/4", "1/4"], character: [-1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [-1, 0] },
            LittleOperation { element: "z,y,x", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-z+1/4,y,-x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "0", "1/4"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 227,
        label: "DT4",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x+1/4,y,-z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "0", "1/4"], character: [1, 0] },
            LittleOperation { element: "-z,y+1/4,x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["0", "1/4", "1/4"], character: [1, 0] },
            LittleOperation { element: "z+1/4,y+1/4,-x", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/4", "0"], character: [1, 0] },
            LittleOperation { element: "-x,y+1/4,z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "1/4", "1/4"], character: [-1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [-1, 0] },
            LittleOperation { element: "z,y,x", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [-1, 0] },
            LittleOperation { element: "-z+1/4,y,-x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "0", "1/4"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 227,
        label: "DT5",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 2,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [2, 0] },
            LittleOperation { element: "-x+1/4,y,-z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "0", "1/4"], character: [-2, 0] },
            LittleOperation { element: "-z,y+1/4,x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["0", "1/4", "1/4"], character: [0, 0] },
            LittleOperation { element: "z+1/4,y+1/4,-x", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/4", "0"], character: [0, 0] },
            LittleOperation { element: "-x,y+1/4,z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "1/4", "1/4"], character: [0, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [0, 0] },
            LittleOperation { element: "z,y,x", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["0", "0", "0"], character: [0, 0] },
            LittleOperation { element: "-z+1/4,y,-x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "0", "1/4"], character: [0, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 227,
        label: "SM1",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/4,x+1/4,-z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [1, 0] },
            LittleOperation { element: "y,x,z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 227,
        label: "SM2",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/4,x+1/4,-z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [-1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [1, 0] },
            LittleOperation { element: "y,x,z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 227,
        label: "SM3",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/4,x+1/4,-z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [-1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [-1, 0] },
            LittleOperation { element: "y,x,z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 227,
        label: "SM4",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/4,x+1/4,-z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [-1, 0] },
            LittleOperation { element: "y,x,z", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 228,
        label: "DT1",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x+1/4,y,-z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "0", "1/4"], character: [1, 0] },
            LittleOperation { element: "-z+1/2,y+1/4,x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/4", "1/4"], character: [1, 0] },
            LittleOperation { element: "z+1/4,y+1/4,-x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/4", "1/2"], character: [1, 0] },
            LittleOperation { element: "-x,y+1/4,z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "1/4", "1/4"], character: [1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [1, 0] },
            LittleOperation { element: "z+1/2,y+1/2,x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
            LittleOperation { element: "-z+1/4,y+1/2,-x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/2", "1/4"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 228,
        label: "DT2",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x+1/4,y,-z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "0", "1/4"], character: [1, 0] },
            LittleOperation { element: "-z+1/2,y+1/4,x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/4", "1/4"], character: [-1, 0] },
            LittleOperation { element: "z+1/4,y+1/4,-x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/4", "1/2"], character: [-1, 0] },
            LittleOperation { element: "-x,y+1/4,z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "1/4", "1/4"], character: [1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [1, 0] },
            LittleOperation { element: "z+1/2,y+1/2,x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
            LittleOperation { element: "-z+1/4,y+1/2,-x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/2", "1/4"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 228,
        label: "DT3",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x+1/4,y,-z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "0", "1/4"], character: [1, 0] },
            LittleOperation { element: "-z+1/2,y+1/4,x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/4", "1/4"], character: [-1, 0] },
            LittleOperation { element: "z+1/4,y+1/4,-x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/4", "1/2"], character: [-1, 0] },
            LittleOperation { element: "-x,y+1/4,z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "1/4", "1/4"], character: [-1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [-1, 0] },
            LittleOperation { element: "z+1/2,y+1/2,x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
            LittleOperation { element: "-z+1/4,y+1/2,-x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/2", "1/4"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 228,
        label: "DT4",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "-x+1/4,y,-z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "0", "1/4"], character: [1, 0] },
            LittleOperation { element: "-z+1/2,y+1/4,x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/4", "1/4"], character: [1, 0] },
            LittleOperation { element: "z+1/4,y+1/4,-x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/4", "1/2"], character: [1, 0] },
            LittleOperation { element: "-x,y+1/4,z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "1/4", "1/4"], character: [-1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [-1, 0] },
            LittleOperation { element: "z+1/2,y+1/2,x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
            LittleOperation { element: "-z+1/4,y+1/2,-x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/2", "1/4"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 228,
        label: "DT5",
        k_label: "DT",
        direction: ["0", "2", "0"],
        dimension: 2,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [2, 0] },
            LittleOperation { element: "-x+1/4,y,-z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "0", "1/4"], character: [-2, 0] },
            LittleOperation { element: "-z+1/2,y+1/4,x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/4", "1/4"], character: [0, 0] },
            LittleOperation { element: "z+1/4,y+1/4,-x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/4", "1/2"], character: [0, 0] },
            LittleOperation { element: "-x,y+1/4,z+1/4", rotation: [[-1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "1/4", "1/4"], character: [0, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [0, 0] },
            LittleOperation { element: "z+1/2,y+1/2,x+1/2", rotation: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], translation: ["1/2", "1/2", "1/2"], character: [0, 0] },
            LittleOperation { element: "-z+1/4,y+1/2,-x+1/4", rotation: [[0, 0, -1], [0, 1, 0], [-1, 0, 0]], translation: ["1/4", "1/2", "1/4"], character: [0, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 228,
        label: "SM1",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/4,x+1/4,-z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["1/4", "1/4", "1/2"], character: [1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/2,x+1/2,z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 228,
        label: "SM2",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/4,x+1/4,-z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["1/4", "1/4", "1/2"], character: [-1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/2,x+1/2,z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 228,
        label: "SM3",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/4,x+1/4,-z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["1/4", "1/4", "1/2"], character: [-1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [-1, 0] },
            LittleOperation { element: "y+1/2,x+1/2,z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["1/2", "1/2", "1/2"], character: [1, 0] },
        ],
    },
    LittleCharacterTable {
        space_group: 228,
        label: "SM4",
        k_label: "SM",
        direction: ["2", "2", "0"],
        dimension: 1,
        operations: &[
            LittleOperation { element: "x,y,z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]], translation: ["0", "0", "0"], character: [1, 0] },
            LittleOperation { element: "y+1/4,x+1/4,-z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, -1]], translation: ["1/4", "1/4", "1/2"], character: [1, 0] },
            LittleOperation { element: "x+1/4,y+1/4,-z", rotation: [[1, 0, 0], [0, 1, 0], [0, 0, -1]], translation: ["1/4", "1/4", "0"], character: [-1, 0] },
            LittleOperation { element: "y+1/2,x+1/2,z+1/2", rotation: [[0, 1, 0], [1, 0, 0], [0, 0, 1]], translation: ["1/2", "1/2", "1/2"], character: [-1, 0] },
        ],
    },
];

/// Sources the frozen data does not cover (empty when every source is
/// covered by the Gamma rows or by the little-cogroup ordering route).
pub static W_LITTLE_CHARACTERS_UNRESOLVED: &[(u8, &str)] = &[
];
