#!/usr/bin/env python3
"""
将 char_reorder_map.txt 转换为 Rust 静态数组 PER_CHAR_REORDER，
并注入到 generated_data.rs 中。

格式: 每行一个 irrep 的 h_to_pir 映射。
  SG ML_LABEL N_H_OPS N_PIR_OPS [p0 p1 ... pN]
  或 SG ML_LABEL N_H_OPS 0 UNMAPPED

PER_CHAR_REORDER 数组: 对于每个 irrep，连续存储其 h_to_pir 映射。
PER_CHAR_REORDER_INDEX: 231 个 (start, count) 对，按 SG 索引。
"""

import re
import os

MAP_FILE = "char_reorder_map.txt"
GEN_FILE = "src/irrep/generated_data.rs"
OUT_FILE = "src/irrep/reorder_data.rs"  # 单独文件，避免修改 generated_data.rs 太大

def parse_map(path):
    """解析映射文件，返回 {sg: [(ml, h_to_pir)]}"""
    data = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            sg = int(parts[0])
            ml = parts[1]
            n_h = int(parts[2])
            n_pir = int(parts[3])
            if parts[4] in ("UNMAPPED", "SPINOR", "SPINOR_NOSCALAR"):
                h_to_pir = []
            else:
                h_to_pir = [int(x) for x in parts[4:]]
                assert len(h_to_pir) == n_h, f"Expected {n_h} entries, got {len(h_to_pir)} for SG{sg} {ml}"

            if sg not in data:
                data[sg] = []
            data[sg].append((ml, h_to_pir, n_h, n_pir))
    return data

def generate_rust(data, out_path):
    """生成 PER_CHAR_REORDER 数组和索引的 Rust 代码"""

    # 按 SG 编号排序所有 irrep
    all_irreps = []
    for sg in sorted(data.keys()):
        for ml, h_to_pir, n_h, n_pir in data[sg]:
            all_irreps.append((sg, ml, h_to_pir, n_h, n_pir))

    # 构建平面数组: 存储正向映射 h_to_pir[h_idx] = pir_idx
    flat = []
    irrep_records = []  # (start, count, sg, ml, n_pir) for each irrep

    for sg, ml, h_to_pir, n_h, n_pir in all_irreps:
        start = len(flat)
        if h_to_pir:
            # 存储 N_H_OPS 个值: h_to_pir[h_idx] = pir_idx (PIR character index)
            # 用 u16 存 pir_idx，最大值可达 ~100
            flat.extend(h_to_pir)
            count = n_h
        else:
            count = 0
        irrep_records.append((start, count, sg, ml, n_pir))

    # 生成 SG 索引: sg_idx → (start, count) into irrep_records
    sg_index = []  # 231 entries
    irrep_idx = 0
    for sg in range(1, 231):
        start = irrep_idx
        count = 0
        while irrep_idx < len(irrep_records) and irrep_records[irrep_idx][2] == sg:
            count += 1
            irrep_idx += 1
        sg_index.append((start, count))
    # SG 0 (unused)
    sg_index.insert(0, (0, 0))

    with open(out_path, 'w') as f:
        f.write("// Auto-generated character reorder data.\n")
        f.write("// Generated by scripts/apply_char_reorder.py\n")
        f.write("// Do not edit manually.\n\n")

        # IRREP_CHAR_REORDER_INDEX: 每个 irrep 在 PER_CHAR_REORDER 中的 (start, count)
        f.write("/// Per-irrep index into PER_CHAR_REORDER: for each irrep in IRREPS,\n")
        f.write("/// (start, count) where count = N_H_OPS (number of spglib H ops).\n")
        f.write("/// Value at index i is the PIR character index for spglib H_op[i].\n")
        f.write(f"pub static IRREP_CHAR_REORDER_INDEX: [(u32, u16); {len(irrep_records)}] = [\n")
        for start, count, sg, ml, n_pir in irrep_records:
            f.write(f"    ({start}, {count}), // SG{sg} {ml}\n")
        f.write("];\n\n")

        # SG_CHAR_REORDER_INDEX: SG# → (start, count) into IRREP_CHAR_REORDER_INDEX
        f.write("/// SG index into IRREP_CHAR_REORDER_INDEX.\n")
        f.write(f"pub static SG_CHAR_REORDER_INDEX: [(u32, u16); 231] = [\n")
        for sg in range(231):
            s, c = sg_index[sg]
            f.write(f"    ({s}, {c}), // SG {sg}\n")
        f.write("];\n\n")

        # PER_CHAR_REORDER: 平面数组: h_to_pir[h_idx] = pir_idx
        f.write("/// Flat h_to_pir array: for each spglib H op position,\n")
        f.write("/// the corresponding PIR (ISOTROPY) character index.\n")
        f.write(f"pub static PER_CHAR_REORDER: [u16; {len(flat)}] = [\n")
        for i in range(0, len(flat), 50):
            chunk = flat[i:i+50]
            f.write("    " + ", ".join(str(v) for v in chunk) + ",\n")
        f.write("];\n")

    print(f"Generated {out_path}:")
    print(f"  {len(irrep_records)} irrep records")
    print(f"  {len(flat)} forward mapping entries (h_to_pir)")
    print(f"  {sum(1 for v in flat if v < 65535)} mapped entries")

if __name__ == "__main__":
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    data = parse_map(MAP_FILE)
    generate_rust(data, OUT_FILE)
    print("Done. Now add `mod reorder_data;` and `include!(\"reorder_data.rs\");` to generated_data.rs")
