#!/usr/bin/env python3
"""
Extract per-SG setting data (basis matrix + origin vector) from ISOTROPY iso.zip
and generate Rust static arrays for src/irrep/generated_data.rs.

Output: settings_data.rs (to be appended to generated_data.rs)
"""

import zipfile, re, os, sys

ISO_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "isotropy_subgroup")

def parse_section(lines, start_name):
    """Parse a named section, return flat list of string values."""
    for i, line in enumerate(lines):
        if line.strip() == start_name:
            vals = []
            j = i + 1
            while j < len(lines) and lines[j].strip() \
                  and not re.match(r'^[a-z_]+$', lines[j].strip()):
                vals.extend(lines[j].strip().split())
                j += 1
            return vals
    return []

def main():
    with zipfile.ZipFile(f'{ISO_DIR}/iso.zip') as z:
        # Parse data_irreps.txt
        with z.open('data_irreps.txt') as f:
            content = f.read().decode('utf-8', errors='replace')
        ir_lines = content.split('\n')

        # Parse data_isotropy.txt
        with z.open('data_isotropy.txt') as f:
            content = f.read().decode('utf-8', errors='replace')
        iso_lines = content.split('\n')

    # Irrep → SG mapping
    irrep_sg = [int(x) for x in parse_section(ir_lines, 'irrep_space_group')]
    irrep_sg_ptr = [int(x) for x in parse_section(ir_lines, 'irrep_space_group_pointer')]

    # Irrep → isotropy subgroup range
    iso_irrep_ptr = [int(x) for x in parse_section(iso_lines, 'isotropy_irrep_pointer')]

    # Basis and origin
    basis_raw = [float(x) for x in parse_section(iso_lines, 'isotropy_basis')]
    origin_raw = [float(x) for x in parse_section(iso_lines, 'isotropy_origin')]

    # Per-SG extraction
    sg_basis = []   # 9 f64 per SG (3x3 row-major)
    sg_origin = []  # 3 f64 per SG

    for sg in range(1, 231):
        start_irrep = irrep_sg_ptr[sg - 1]  # 1-based
        first_irrep_idx = None
        for i in range(start_irrep - 1, len(irrep_sg)):
            if irrep_sg[i] == sg:
                first_irrep_idx = i
                break

        if first_irrep_idx is None:
            sg_basis.extend([1,0,0, 0,1,0, 0,0,1])
            sg_origin.extend([0,0,0])
            continue

        if first_irrep_idx < len(iso_irrep_ptr):
            iso_start = iso_irrep_ptr[first_irrep_idx] - 1  # → 0-based
        else:
            iso_start = 0

        b_start = iso_start * 9
        if b_start + 9 <= len(basis_raw):
            sg_basis.extend(basis_raw[b_start:b_start+9])
        else:
            sg_basis.extend([1,0,0, 0,1,0, 0,0,1])

        o_start = iso_start * 3
        if o_start + 3 <= len(origin_raw):
            o = origin_raw[o_start:o_start+3]
        else:
            o = [0,0,0]
        # Convert origin to rational form: origin values are fractions with denominator 1,2,4
        sg_origin.extend(o)

    # Generate Rust arrays
    out_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                            "src", "irrep", "settings_data.rs")

    with open(out_path, 'w') as f:
        f.write("// Auto-generated SG setting data from ISOTROPY iso.zip.\n")
        f.write("// Generated by scripts/extract_sg_settings.py\n")
        f.write("// Do not edit manually.\n\n")

        # SG_SETTING_BASIS: 230 * 9 = 2070 f64
        f.write("/// Per-SG basis matrix (3x3 row-major) mapping ISOTROPY setting\n")
        f.write("/// to the standard ITA setting.  Index: (sg - 1) * 9.\n")
        f.write(f"pub static SG_SETTING_BASIS: [f64; {len(sg_basis)}] = [\n")
        for i in range(0, len(sg_basis), 9):
            b = sg_basis[i:i+9]
            f.write("    " + ", ".join(f"{v:1.1f}" for v in b) + ",\n")
        f.write("];\n\n")

        # SG_SETTING_ORIGIN: 230 * 3 = 690 f64
        f.write("/// Per-SG origin shift vector (fractional coordinates) from\n")
        f.write("/// ISOTROPY to standard ITA setting.  Index: (sg - 1) * 3.\n")
        f.write(f"pub static SG_SETTING_ORIGIN: [f64; {len(sg_origin)}] = [\n")
        for i in range(0, len(sg_origin), 3):
            o = sg_origin[i:i+3]
            f.write("    " + ", ".join(f"{v:1.1f}" for v in o) + ",\n")
        f.write("];\n")

    print(f"Generated {out_path}:")
    print(f"  SG_SETTING_BASIS: {len(sg_basis)} f64 ({len(sg_basis)//9} SGs)")
    print(f"  SG_SETTING_ORIGIN: {len(sg_origin)} f64 ({len(sg_origin)//3} SGs)")

    # Count non-trivial settings
    n_nonid_basis = sum(1 for i in range(0, len(sg_basis), 9)
                        if sg_basis[i:i+9] != [1,0,0,0,1,0,0,0,1])
    n_nonzero_origin = sum(1 for i in range(0, len(sg_origin), 3)
                           if sg_origin[i:i+3] != [0,0,0])
    print(f"  Non-identity basis: {n_nonid_basis}/230")
    print(f"  Non-zero origin: {n_nonzero_origin}/230")
    print()
    print(f"Now add `include!(\"settings_data.rs\");` to generated_data.rs")

if __name__ == "__main__":
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    main()
