#!/usr/bin/env python3
"""Freeze the collected official direction descriptors into Rust (milestone R7).

Input : ``scripts/data/direction_descriptors_v1.json`` (see
        ``scripts/collect_direction_descriptors.py``).
Output: ``src/irrep/direction_descriptors_data.rs``.

The generated module is a read-only table keyed by ``(space group, Miller-Love
label)`` with one entry per direction label; the query API lives in
``irrep::isotropy``.  ``--check`` regenerates in memory and exits non-zero when
the committed file differs, which is how the gate keeps the two in sync.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys

HEADER = '''//! Official direction descriptors of the ISOTROPY program (milestone R7).
//!
//! **Generated by `scripts/freeze_direction_descriptors.py` -- do not edit.**
//!
//! Source: `scripts/data/direction_descriptors_v1.json` (sha256 `{json_sha}`),
//! collected by `scripts/collect_direction_descriptors.py` from
//! `SHOW DIRECTION VECTOR` of the bundled program:
//!
//! * `iso` sha256 `{iso_sha}`
//! * `data_irreps.txt` sha256 `{irreps_sha}`
//! * `data_isotropy.txt` sha256 `{isotropy_sha}`
//!
//! The strings here are the program's **own**; the bundled tables' notation
//! (the one [`crate::irrep::isotropy::IsotropyDirection::Descriptor`] matches)
//! differs for `dim = 2`, for `dim >= 4` and in its separators, so the two are
//! deliberately separate selectors.  `{records}` records are listed, `{empty}`
//! print **no** direction-vector table at all (their internal notation is not a
//! substitute: it is simply not what the program prints), and `{directions}`
//! direction strings are stored.
//!
//! Lookups go through [`record`] and [`official_of`]; the public query API is
//! [`crate::irrep::isotropy::official_direction_descriptor`].

/// (direction label in the anisotropy table, the program's own component
/// string).
pub type OfficialDirection = (&'static str, &'static str);

/// One `(parent space group, Miller-Love label)` record.  Sorted by
/// `(sg, ml)`; `directions` is sorted by label.
#[derive(Debug, Clone, Copy)]
pub struct OfficialRecord {
    pub sg: u8,
    pub ml: &'static str,
    pub directions: &'static [OfficialDirection],
}

/// Every record the program prints a direction-vector table for.
pub static OFFICIAL_RECORDS: &[OfficialRecord] = &[
'''

FOOTER = '''];

/// Records whose `SHOW DIRECTION VECTOR` table is empty (the program prints no
/// direction strings for them), sorted by `(sg, ml)`.
pub static OFFICIAL_TABLE_EMPTY: &[(u8, &str)] = &[
{empty_rows}];

/// The record for `(sg, ml)`, if the program prints direction strings for it.
pub fn record(sg: u8, ml: &str) -> Option<&'static OfficialRecord> {
    OFFICIAL_RECORDS
        .binary_search_by(|record| (record.sg, record.ml).cmp(&(sg, ml)))
        .ok()
        .map(|index| &OFFICIAL_RECORDS[index])
}

/// The program's string for one direction label of one record.
pub fn official_of(sg: u8, ml: &str, label: &str) -> Option<&'static str> {
    let record = record(sg, ml)?;
    record
        .directions
        .binary_search_by(|(candidate, _)| (*candidate).cmp(label))
        .ok()
        .map(|index| record.directions[index].1)
}

/// Whether the program prints an empty direction table for `(sg, ml)`.
pub fn table_is_empty(sg: u8, ml: &str) -> bool {
    OFFICIAL_TABLE_EMPTY
        .binary_search_by(|(record_sg, record_ml)| (*record_sg, *record_ml).cmp(&(sg, ml)))
        .is_ok()
}
'''


def sha256_of(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def validate_universe(records: dict) -> None:
    """The JSON must cover exactly the machine tables, internal strings included.

    This is what makes `status: "empty"` mean "the program prints no direction
    rows for this **real** record": `iso` prints the same empty output for a
    label it does not know, so the record universe has to be checked against the
    data tables rather than inferred from the oracle's output.
    """
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import verify_isotropy_oracle as oracle  # noqa: PLC0415

    machine = oracle.machine_records()
    machine_keys = {f"{sg}|{ml}" for (sg, ml) in machine}
    json_keys = set(records)
    if machine_keys != json_keys:
        missing = sorted(machine_keys - json_keys)[:5]
        extra = sorted(json_keys - machine_keys)[:5]
        raise SystemExit(
            f"record universe mismatch: missing {missing}, extra {extra} "
            f"(machine {len(machine_keys)}, json {len(json_keys)})"
        )
    for key, entry in records.items():
        sg_text, ml = key.split("|", 1)
        expected = {
            row["label"]: row["direction"] for row in machine[(int(sg_text), ml)]
        }
        if entry["internal"] != expected:
            raise SystemExit(f"{key}: internal strings differ from the data tables")


def render(json_path: str) -> str:
    payload = json.load(open(json_path, encoding="utf-8"))
    sources = payload["sources"]
    records = payload["records"]
    validate_universe(records)
    body = []
    empty_rows = []
    directions = 0
    for key in sorted(records, key=lambda k: (int(k.split("|")[0]), k.split("|")[1])):
        sg_text, ml = key.split("|", 1)
        entry = records[key]
        if entry["status"] == "empty":
            empty_rows.append(f"    ({sg_text}, {quote(ml)}),")
            continue
        official = entry["official"]
        if not official:
            # A failed record is not silently treated as empty.
            raise SystemExit(f"{key} has status {entry['status']} but no rows")
        rows = sorted(official.items())
        directions += len(rows)
        body.append("    OfficialRecord {")
        body.append(f"        sg: {sg_text},")
        body.append(f"        ml: {quote(ml)},")
        body.append("        directions: &[")
        for label, text in rows:
            body.append(f"            ({quote(label)}, {quote(text)}),")
        body.append("        ],")
        body.append("    },")
    head = HEADER
    for name, value in {
        "json_sha": sha256_of(json_path),
        "iso_sha": sources["iso"],
        "irreps_sha": sources["data_irreps.txt"],
        "isotropy_sha": sources["data_isotropy.txt"],
        "records": len(records) - len(empty_rows),
        "empty": len(empty_rows),
        "directions": directions,
    }.items():
        head = head.replace("{" + name + "}", str(value))
    return (
        head
        + "\n".join(body)
        + "\n"
        + FOOTER.replace("{empty_rows}", "\n".join(empty_rows))
    )


def verify_empty_tables(json_path: str, jobs: int) -> int:
    """Re-ask the oracle about every `status: "empty"` record (round-15g limit).

    `validate_universe` proves such a key is a real data-table record, but not
    that the program's direction table for it is empty: the JSON could have been
    written from a stale cache.  This re-runs `SHOW DIRECTION VECTOR` for those
    records only and fails when any of them prints rows.
    """
    import concurrent.futures  # noqa: PLC0415

    payload = json.load(open(json_path, encoding="utf-8"))
    empty = sorted(
        key for key, entry in payload["records"].items() if entry["status"] == "empty"
    )
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import verify_isotropy_oracle as oracle  # noqa: PLC0415

    def check(key: str) -> tuple[str, int]:
        sg_text, ml = key.split("|", 1)
        rows = oracle.run_oracle_direction_vectors(int(sg_text), ml)
        return key, len(rows)

    findings = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=jobs) as pool:
        for key, count in pool.map(check, empty):
            if count:
                findings.append(f"{key}: {count} direction row(s) printed")
    if findings:
        for finding in findings:
            print(f"NOT EMPTY  {finding}", file=sys.stderr)
        return 1
    print(f"{len(empty)} empty program tables re-confirmed against the oracle")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", default="scripts/data/direction_descriptors_v1.json")
    parser.add_argument("--output", default="src/irrep/direction_descriptors_data.rs")
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--verify-empty",
        action="store_true",
        help="re-ask the oracle about every empty-table record (needs the iso binary)",
    )
    parser.add_argument("--jobs", type=int, default=0, help="0 = min(8, cores)")
    args = parser.parse_args()

    if args.verify_empty:
        return verify_empty_tables(args.json, args.jobs or min(8, os.cpu_count() or 1))

    rendered = render(args.json)
    if args.check:
        if not os.path.isfile(args.output):
            print(f"{args.output} is missing", file=sys.stderr)
            return 1
        current = open(args.output, encoding="utf-8").read()
        if current != rendered:
            print(
                f"{args.output} is stale; re-run {os.path.basename(__file__)}",
                file=sys.stderr,
            )
            return 1
        print(f"{args.output} matches {args.json}")
        return 0
    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write(rendered)
    print(f"wrote {args.output} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
