#!/usr/bin/env python3
"""Extract small full-star CIR trace fixtures directly from the pinned archive.

No induction or Hall reordering is used: the expected traces are the sums of
all diagonal entries of the archived complex matrices. Only special k points
are supported here, so no parameter substitution is implicit.
"""

import argparse
from fractions import Fraction
import hashlib
import io
from pathlib import Path
import zipfile

try:
    from . import generate_irrep_data as source
    from .iso_irrep_exact import CIR_ARCHIVE_SHA256
except ImportError:
    import generate_irrep_data as source
    from iso_irrep_exact import CIR_ARCHIVE_SHA256


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "tests/data/subduction_star_cir.rs"
# Fixed source identities, not an inferred label-to-star lookup.
CASES = {
    (92, "X1"): 4557,
    (139, "X1+"): 7301,
    (139, "N1+"): 7319,
    (139, "P1"): 7323,
    (198, "X1"): 9845,
    (221, "X1+"): 10719,
    (221, "X5+"): 10723,
    (221, "M5-"): 10738,
    (225, "L1+"): 10943,
    (225, "X1+"): 10949,
}


def fractions(values):
    return "[" + ", ".join(f"({v.numerator}, {v.denominator})" for v in values) + "]"


def scalar_literal(value):
    # Match the exact archived radical, never infer a constant by tolerance.
    if value.a == value.c == value.d == 0 and abs(value.b) == 2:
        sign = "-" if value.b < 0 else ""
        return sign + "std::f64::consts::FRAC_1_SQRT_2"
    return repr(value.materialize())


def render(cases=CASES, command="scripts/generate_subduction_star_fixtures.py --write"):
    archive = (ROOT / "isotropy_subgroup/CIR_data.zip").read_bytes()
    if hashlib.sha256(archive).hexdigest() != CIR_ARCHIVE_SHA256:
        raise ValueError("CIR archive checksum differs from the pinned source")
    with zipfile.ZipFile(io.BytesIO(archive)) as zipped:
        lines = zipped.read("CIR_data.txt").decode("ascii").splitlines()
    out = [
        f"// Generated by {command}.",
        f"// CIR_data.zip SHA256: {CIR_ARCHIVE_SHA256}",
        "// Matrices, operations and arms are in the original CIR source frame.",
        "const SOURCE_CASES: &[SourceCase] = &[",
    ]
    found = set()
    for start, line in enumerate(lines):
        if '"' not in line:
            continue
        header = source._parse_cir_header(line, start + 1)
        key = (header["sg"], header["label"])
        if key not in cases:
            continue
        if key in found or header["irnumber"] != cases[key]:
            raise ValueError(f"duplicate or changed source identity: {key}")
        found.add(key)
        dim, count = header["dim"], header["kcount"]
        raw_k, index = source._read_exact_cir_block(
            lines, start + 1, 16 * count, str(key), source._parse_cir_integer
        )
        arms = []
        for arm in range(count):
            raw = raw_k[16 * arm:16 * (arm + 1)]
            if any(raw[offset] for offset in (4, 5, 6, 8, 9, 10, 12, 13, 14)):
                raise ValueError(f"parameterized arm in fixture: {key}")
            arms.append([Fraction(raw[axis], raw[3]) for axis in range(3)])
        out.extend([
            "    SourceCase {",
            f'        sg: {key[0]}, ml: "{key[1]}", irnumber: {header["irnumber"]}, dimension: {dim},',
            "        arms: &[" + ", ".join(fractions(arm) for arm in arms) + "],",
            "        operations: &[",
        ])
        for operation in range(header["opcount"]):
            context = f"{key} operation {operation}"
            raw, index = source._parse_cir_operation_row(lines, index, context)
            matrix, _, index = source._parse_cir_complex_block(lines, index, dim * dim, context)
            rotation = [raw[i] // raw[15] for i in (0, 1, 2, 4, 5, 6, 8, 9, 10)]
            translation = [Fraction(raw[i], raw[15]) for i in (3, 7, 11)]
            real = sum((matrix[i * dim + i][0] for i in range(dim)), source.Radical4(0, 0, 0, 0))
            imag = sum((matrix[i * dim + i][1] for i in range(dim)), source.Radical4(0, 0, 0, 0))
            blocks = []
            if dim % count:
                raise ValueError(f"dimension/star size mismatch: {key}")
            for arm in range(count):
                indices = range(arm * (dim // count), (arm + 1) * (dim // count))
                block_real = sum((matrix[i * dim + i][0] for i in indices), source.Radical4(0, 0, 0, 0))
                block_imag = sum((matrix[i * dim + i][1] for i in indices), source.Radical4(0, 0, 0, 0))
                blocks.append(f"({scalar_literal(block_real)}, {scalar_literal(block_imag)})")
            out.append(
                "            (" + str(rotation) + ", " + fractions(translation)
                + f", ({scalar_literal(real)}, {scalar_literal(imag)}), &["
                + ", ".join(blocks) + "]),"
            )
        if index < len(lines) and '"' not in lines[index]:
            raise ValueError(f"fixture did not end at the next record: {key}")
        out.extend(["        ],", "    },"])
    if found != cases.keys():
        raise ValueError(f"missing fixtures: {cases.keys() - found}")
    out.append("];\n")
    return "\n".join(out)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate instead of checking")
    args = parser.parse_args()
    expected = render()
    if args.write:
        OUTPUT.write_text(expected)
    elif OUTPUT.read_text() != expected:
        raise SystemExit("full-star source fixtures differ; regenerate with --write")
    print(f"full-star CIR fixtures: {len(CASES)} records, archive checksum verified")
