"""Integrity check for the generated little-group character table.

Run with:
    python3 -m unittest discover -s scripts -p test_frozen_w_little_characters.py

`src/irrep/w_little_characters_data.rs` is generated by
`scripts/freeze_w_little_characters.py --rust` from the pinned ISOTROPY archive.
This test parses the checked-in file (no cargo, no `iso` run) and pins the shape
and the anchors the Rust test `tests/w_little_characters.rs` also asserts, so a
hand edit or a stale regeneration is caught on the Python side too.
"""

import re
import sys
import unittest

SCRIPT_DIR = __import__("os").path.dirname(__import__("os").path.abspath(__file__))
REPO_DIR = __import__("os").path.dirname(SCRIPT_DIR)
DATA_PATH = __import__("os").path.join(REPO_DIR, "src", "irrep", "w_little_characters_data.rs")

TABLE_RE = re.compile(
    r"LittleCharacterTable \{(?P<body>.*?)\n    \},", re.S
)
OP_RE = re.compile(
    r'LittleOperation \{ element: "(?P<element>[^"]*)", '
    r"rotation: \[(?P<rotation>.*?)\], translation: \[(?P<translation>.*?)\], "
    r"character: \[(?P<real>-?\d+), (?P<imaginary>-?\d+)\] \}",
    re.S,
)
UNRESOLVED_RE = re.compile(r'\((\d+), "([A-Z0-9]+)"\)')


def parse_tables():
    text = open(DATA_PATH, encoding="utf-8").read()
    tables = []
    for match in TABLE_RE.finditer(text):
        body = match.group("body")
        entry = {
            "space_group": int(re.search(r"space_group: (\d+)", body).group(1)),
            "label": re.search(r'label: "([^"]*)"', body).group(1),
            "k_label": re.search(r'k_label: "([^"]*)"', body).group(1),
            "dimension": int(re.search(r"dimension: (\d+)", body).group(1)),
            "operations": [
                {
                    "element": op.group("element"),
                    "rotation": op.group("rotation"),
                    "character": (int(op.group("real")), int(op.group("imaginary"))),
                }
                for op in OP_RE.finditer(body)
            ],
        }
        tables.append(entry)
    unresolved = [
        (int(sg), label)
        for sg, label in UNRESOLVED_RE.findall(text.split("W_LITTLE_CHARACTERS_UNRESOLVED", 1)[1])
    ]
    return tables, unresolved


class FrozenCharacterTableTests(unittest.TestCase):
    def setUp(self):
        self.tables, self.unresolved = parse_tables()

    def test_size_and_unresolved_set(self):
        self.assertEqual(len(self.tables), 73)
        self.assertEqual(self.unresolved, [])
        keys = {(t["space_group"], t["label"]) for t in self.tables}
        self.assertEqual(len(keys), 73, "duplicate table")

    def test_every_table_starts_at_the_identity(self):
        for table in self.tables:
            operations = table["operations"]
            self.assertTrue(operations, table)
            first = operations[0]
            self.assertEqual(first["element"], "x,y,z")
            self.assertEqual(first["character"], (table["dimension"], 0), table)
            for op in operations:
                real, imaginary = op["character"]
                self.assertLessEqual(
                    real * real + imaginary * imaginary,
                    table["dimension"] ** 2,
                    table,
                )

    def test_sg196_anchors(self):
        by_key = {(t["space_group"], t["label"]): t for t in self.tables}
        dt1 = by_key[(196, "DT1")]
        self.assertEqual(dt1["k_label"], "DT")
        self.assertEqual(
            [op["character"] for op in dt1["operations"]], [(1, 0), (1, 0)]
        )
        dt2 = by_key[(196, "DT2")]
        self.assertEqual(
            [op["character"] for op in dt2["operations"]], [(1, 0), (-1, 0)]
        )
        sm1 = by_key[(196, "SM1")]
        self.assertEqual([op["character"] for op in sm1["operations"]], [(1, 0)])
        self.assertNotEqual(dt1["operations"], dt2["operations"])

    def test_cubic_dt_pairs(self):
        """The pair the Gamma rows leave open, from the little cogroup route."""
        determined = {
            "DT1": [(1, 0), (1, 0), (1, 0), (1, 0)],
            "DT2": [(1, 0), (1, 0), (-1, 0), (-1, 0)],
        }
        real_pair = {
            "DT3": [(1, 0), (-1, 0), (1, 0), (-1, 0)],
            "DT4": [(1, 0), (-1, 0), (-1, 0), (1, 0)],
        }
        complex_pair = {
            "DT3": [(1, 0), (-1, 0), (0, 1), (0, -1)],
            "DT4": [(1, 0), (-1, 0), (0, -1), (0, 1)],
        }
        by_key = {(t["space_group"], t["label"]): t for t in self.tables}
        for space_group, pair in (
            (202, real_pair),
            (203, real_pair),
            (209, complex_pair),
            (210, complex_pair),
        ):
            expected = dict(determined, **pair)
            for label, characters in expected.items():
                table = by_key[(space_group, label)]
                self.assertEqual(table["k_label"], "DT", (space_group, label))
                self.assertEqual(
                    [op["character"] for op in table["operations"]],
                    characters,
                    (space_group, label),
                )


if __name__ == "__main__":
    sys.exit(unittest.main())
