"""Integrity check for the generated little-group character table.

Run with:
    python3 -m unittest discover -s scripts -p test_frozen_w_little_characters.py

`src/irrep/w_little_characters_data.rs` is generated by
`scripts/freeze_w_little_characters.py --rust` from the pinned ISOTROPY archive.
This test parses the checked-in file (no cargo, no `iso` run) and pins the shape
and the anchors the Rust test `tests/w_little_characters.rs` also asserts, so a
hand edit or a stale regeneration is caught on the Python side too.
"""

import re
import sys
import unittest

SCRIPT_DIR = __import__("os").path.dirname(__import__("os").path.abspath(__file__))
REPO_DIR = __import__("os").path.dirname(SCRIPT_DIR)
DATA_PATH = __import__("os").path.join(REPO_DIR, "src", "irrep", "w_little_characters_data.rs")

TABLE_RE = re.compile(
    r"LittleCharacterTable \{(?P<body>.*?)\n    \},", re.S
)
OP_RE = re.compile(
    r'LittleOperation \{ element: "(?P<element>[^"]*)", '
    r"rotation: \[(?P<rotation>.*?)\], translation: \[(?P<translation>.*?)\], "
    r"character: (?P<character>-?\d+) \}",
    re.S,
)
UNRESOLVED_RE = re.compile(r'\((\d+), "([A-Z0-9]+)"\)')


def parse_tables():
    text = open(DATA_PATH, encoding="utf-8").read()
    tables = []
    for match in TABLE_RE.finditer(text):
        body = match.group("body")
        entry = {
            "space_group": int(re.search(r"space_group: (\d+)", body).group(1)),
            "label": re.search(r'label: "([^"]*)"', body).group(1),
            "k_label": re.search(r'k_label: "([^"]*)"', body).group(1),
            "dimension": int(re.search(r"dimension: (\d+)", body).group(1)),
            "operations": [
                {
                    "element": op.group("element"),
                    "rotation": op.group("rotation"),
                    "character": int(op.group("character")),
                }
                for op in OP_RE.finditer(body)
            ],
        }
        tables.append(entry)
    unresolved = [
        (int(sg), label)
        for sg, label in UNRESOLVED_RE.findall(text.split("W_LITTLE_CHARACTERS_UNRESOLVED", 1)[1])
    ]
    return tables, unresolved


class FrozenCharacterTableTests(unittest.TestCase):
    def setUp(self):
        self.tables, self.unresolved = parse_tables()

    def test_size_and_unresolved_set(self):
        self.assertEqual(len(self.tables), 65)
        self.assertEqual(
            sorted(self.unresolved),
            [(202, "DT3"), (202, "DT4"), (203, "DT3"), (203, "DT4"),
             (209, "DT3"), (209, "DT4"), (210, "DT3"), (210, "DT4")],
        )
        keys = {(t["space_group"], t["label"]) for t in self.tables}
        self.assertEqual(len(keys), 65, "duplicate table")
        for key in self.unresolved:
            self.assertNotIn(key, keys)

    def test_every_table_starts_at_the_identity(self):
        for table in self.tables:
            operations = table["operations"]
            self.assertTrue(operations, table)
            first = operations[0]
            self.assertEqual(first["element"], "x,y,z")
            self.assertEqual(first["character"], table["dimension"], table)
            for op in operations:
                self.assertLessEqual(abs(op["character"]), table["dimension"], table)

    def test_sg196_anchors(self):
        by_key = {(t["space_group"], t["label"]): t for t in self.tables}
        dt1 = by_key[(196, "DT1")]
        self.assertEqual(dt1["k_label"], "DT")
        self.assertEqual([op["character"] for op in dt1["operations"]], [1, 1])
        dt2 = by_key[(196, "DT2")]
        self.assertEqual([op["character"] for op in dt2["operations"]], [1, -1])
        sm1 = by_key[(196, "SM1")]
        self.assertEqual([op["character"] for op in sm1["operations"]], [1])
        self.assertNotEqual(dt1["operations"], dt2["operations"])


if __name__ == "__main__":
    sys.exit(unittest.main())
